package ec2

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"log/slog"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/junioryono/billet/internal/awscreds"
	"github.com/junioryono/billet/internal/config"
	"github.com/junioryono/billet/internal/provider"
)

// TestLiveSmoke drives this provider against a REAL AWS account.
//
// EVERY OTHER TEST IN THIS PACKAGE TALKS TO A FAKE, which is the standing caveat
// on the whole backend: the signer is pinned to vectors generated by AWS's own
// SDK, the request shapes are pinned to documentation, and neither is the same as
// EC2 accepting them. This is the one test that closes that gap, and it is opt-in
// because it costs money and needs an account.
//
//	BILLET_LIVE_EC2_REGION=us-west-2 \
//	BILLET_LIVE_EC2_SUBNET=subnet-... \
//	BILLET_LIVE_EC2_SG=sg-... \
//	BILLET_LIVE_EC2_IMAGE=ami-... \
//	AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... AWS_SESSION_TOKEN=... \
//	go test ./internal/provider/ec2/ -run TestLiveSmoke -v -count=1
//
// IT DESTROYS WHAT IT LAUNCHES, in a cleanup that runs even on failure, and it
// launches exactly one instance of the smallest shape it is given. What it cannot
// do is prove the absence of a leak: if the process is killed between RunInstances
// and the cleanup, OR if Launch itself fails after RunInstances has already
// committed — a response that will not parse, a context expiring mid-reply — an
// instance survives and this test never learns its id. It is findable by the
// per-run owner tag.
func TestLiveSmoke(t *testing.T) {
	region := os.Getenv("BILLET_LIVE_EC2_REGION")
	if region == "" {
		t.Skip("BILLET_LIVE_EC2_REGION is unset; this test spends money and is opt-in")
	}

	cfg := config.EC2Config{
		Region:           region,
		SubnetID:         os.Getenv("BILLET_LIVE_EC2_SUBNET"),
		SecurityGroupIDs: []string{os.Getenv("BILLET_LIVE_EC2_SG")},
		AssignPublicIP:   false,
		InstanceTypes: []config.EC2InstanceType{
			{Type: "t3.micro", VCPU: 2, Memory: 1 * config.GiB},
		},
	}

	image := os.Getenv("BILLET_LIVE_EC2_IMAGE")

	log := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))

	// A DISTINCT OWNER PER RUN, so this cannot see or destroy anything belonging to
	// a real deployment in the same account.
	owner := "live-smoke-" + time.Now().UTC().Format("20060102150405")

	p, err := New(owner, cfg,
		WithCredentials(awscreds.Env{}),
		WithLogger(log))
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	ctx, cancel := context.WithTimeout(t.Context(), 5*time.Minute)
	defer cancel()

	// 1. THE SIGNER, against real EC2, before anything is bought. A hand-rolled
	// SigV4 that matches AWS's own output byte for byte is still only a claim until
	// EC2 answers something other than 403.
	t.Log("=== 1. can billet's signer talk to EC2 at all? ===")

	before, err := p.List(ctx)
	if err != nil {
		t.Fatalf("List against real EC2: %v", err)
	}

	t.Logf("    List returned %d instances for owner %q (expected 0)", len(before), owner)

	// 2. LAUNCH.
	t.Log("=== 2. does the RunInstances request billet builds actually launch? ===")

	// REFUSED IF THE IMAGE WOULD LEAVE A VOLUME BEHIND. Destroy terminates the
	// instance; it does not delete volumes, and this client cannot. An AMI whose
	// non-root mapping says DeleteOnTermination=false would leave a tagged,
	// billable disk behind even on a completely successful run — a leak with no
	// failure attached to notice it by.
	if layout, err := p.imageLayout(ctx, image); err != nil {
		t.Fatalf("inspect %s before launching it: %v", image, err)
	} else {
		for _, d := range layout.devices {
			if d.keep == "false" {
				t.Fatalf("%s keeps %s past termination, and this test cannot delete volumes; "+
					"pick an image whose devices are all deleted on termination", image, d.name)
			}
		}
	}

	// A FRESH LEASE ID PER RUN, and the first attempt at this test taught why. A
	// fixed one made the second run fail with IdempotentParameterMismatch: the
	// lease id IS the ClientToken, and the same token with different parameters is
	// refused. That is the launch-idempotency design working — confirmed by EC2
	// rather than by reading — and it means a retried launch cannot quietly buy a
	// second instance for one job.
	//
	// HOW LONG EC2 REMEMBERS A TOKEN IS NOT STATED HERE, because I do not know it.
	// The runs that produced the mismatch were MINUTES apart, so minutes is what
	// was observed; AWS's current idempotency page and RunInstances reference both
	// document the mismatch behaviour and neither gives a duration. An earlier
	// version of this comment said 24 hours, which came from nowhere I can cite.
	sum := sha256.Sum256([]byte(owner))
	lease := hex.EncodeToString(sum[:])[:32]

	spec := provider.Spec{
		Name:   provider.InstanceName(lease),
		Image:  image,
		VCPU:   2,
		Memory: 1 * config.GiB,
		// A COMMAND THAT IS NOT A RUNNER. This test is about the API path, not about
		// running a job: there is no AMI containing the GitHub runner yet, so the
		// instance boots, runs this, and is destroyed.
		Command:   []string{"/bin/true"},
		Trust:     provider.TrustTrusted,
		JITConfig: "not-a-real-jit-config",
	}

	// REGISTERED BEFORE THE LAUNCH, AND KEYED ON THE NAME, because the id is not
	// the only way an instance can exist.
	//
	// Launch can return (nil, error) after AWS has already accepted RunInstances —
	// a context expiring mid-reply, a response that will not parse, a read that
	// fails. The instance is then real, billable, and has no id this test ever saw.
	// The name is knowable BEFORE the call, though, and the provider offers Find
	// for exactly this ambiguity, so cleanup does not depend on Launch having
	// returned anything.
	//
	// IT RETRIES until its own deadline rather than reporting one failure and
	// exiting, since a single failed Destroy leaves a machine running indefinitely.
	t.Cleanup(func() {
		//nolint:usetesting // t.Context() is already cancelled when cleanup runs.
		clean, stop := context.WithTimeout(context.Background(), 3*time.Minute)
		defer stop()

		for {
			found, ok, err := p.Find(clean, spec.Name)
			if err == nil && !ok {
				return
			}

			if err == nil && ok {
				if _, err = p.Destroy(clean, found.ID); err == nil {
					return
				}
			}

			select {
			case <-clean.Done():
				t.Errorf("CLEANUP EXHAUSTED ITS DEADLINE. An instance named %q, tagged "+
					"owner=%q, may still be running and billing: %v", spec.Name, owner, err)

				return
			case <-time.After(5 * time.Second):
			}
		}
	})

	inst, err := p.Launch(ctx, spec)

	if err != nil {
		t.Fatalf("Launch: %v", err)
	}

	t.Logf("    launched %s", inst.ID)

	// 2b. THE SAME LEASE CANNOT BUY A SECOND INSTANCE, which was previously
	// established by accident — a fixed lease id across two manual runs — and so
	// was not exercised by anything committed.
	//
	// The lease id IS the ClientToken. Relaunching the same lease with DIFFERENT
	// parameters is what AWS refuses, so this asks for a different disk size and
	// expects to be turned down. That is the property the whole
	// escrow-before-advertisement design leans on: a retried launch must not
	// quietly produce a second billable machine for one job.
	t.Log("=== 2b. does the lease id actually prevent a second instance? ===")

	again := spec
	again.Disk = 30 * config.GiB

	dup, dupErr := p.Launch(ctx, again)

	switch {
	case dupErr == nil && dup != nil && dup.ID == inst.ID:
		t.Errorf("    relaunching with different parameters returned the SAME instance (%s); "+
			"expected AWS to refuse the token reuse", dup.ID)
	case dupErr == nil:
		t.Errorf("    relaunching the same lease with different parameters SUCCEEDED and "+
			"produced %v — one job, two machines", dup)
	case strings.Contains(dupErr.Error(), "IdempotentParameterMismatch"):
		t.Log("    refused with IdempotentParameterMismatch, which is the token doing its job")
	default:
		t.Errorf("    relaunch was refused, but not for the reason expected: %v", dupErr)
	}

	// 3. LIST FINDS IT, which exercises the owner tag and the name-to-lease
	// mapping that is the only durable link between compute and a lease.
	t.Log("=== 3. does List find it by owner tag and recover the lease id? ===")

	// POLLED, NOT ASKED ONCE, because the first version of this asked once and got
	// two different answers on two runs of the same code. DescribeInstances is
	// EVENTUALLY CONSISTENT: an instance RunInstances has already returned an id
	// for may not be in the next DescribeInstances response.
	//
	// That is not a curiosity for this backend. Recover enumerates live compute
	// through List, so an instance invisible in the seconds after launch is one a
	// reconciliation pass can conclude does not exist — and act on.
	launched := time.Now()

	var (
		seen    *provider.Instance
		visible time.Duration
	)

	for time.Since(launched) < 90*time.Second {
		found, err := p.List(ctx)
		if err != nil {
			t.Fatalf("List after launch: %v", err)
		}

		for _, i := range found {
			if i.ID == inst.ID {
				seen = i
				visible = time.Since(launched)
			}
		}

		if seen != nil {
			break
		}

		time.Sleep(time.Second)
	}

	if seen == nil {
		t.Errorf("    List never returned the instance within 90s of launching it")
	} else {
		t.Logf("    List first saw it %s after Launch returned; name = %q",
			visible.Round(100*time.Millisecond), seen.Name)

		// ASSERTED, NOT JUST LOGGED. The name is the ONLY durable link between a
		// running instance and the lease that paid for it — recovery reads it back
		// out — and the first version of this test logged it and checked nothing,
		// so a tag round-trip that mangled the name would have passed while the
		// coverage notes claimed this was covered.
		if seen.Name != spec.Name {
			t.Errorf("    the name came back as %q, want %q: the lease id cannot be "+
				"recovered from a running instance", seen.Name, spec.Name)
		}
	}

	// 4. DESTROY, and what it means. This is the requested-versus-stopped
	// distinction, and it is now the assertion rather than the finding: this
	// backend must report the teardown as REQUESTED, because that is all
	// TerminateInstances establishes.
	t.Log("=== 4. what is true at the moment Destroy returns? ===")

	start := time.Now()

	state, err := p.Destroy(ctx, inst.ID)
	if err != nil {
		t.Fatalf("Destroy: %v", err)
	}

	if state != provider.TeardownRequested {
		t.Errorf("    Destroy returned %s, want REQUESTED; the measurement below is how long "+
			"the guest keeps running after that request", state)
	}

	t.Logf("    Destroy returned after %s", time.Since(start).Round(time.Millisecond))

	after, err := p.List(ctx)
	if err != nil {
		t.Fatalf("List after destroy: %v", err)
	}

	still := false

	for _, i := range after {
		if i.ID == inst.ID {
			still = true

			t.Logf("    IMMEDIATELY AFTER Destroy, List still reports it: running=%v", i.Running)
		}
	}

	if !still {
		t.Log("    immediately after Destroy, List no longer reports it")
	}

	// WHAT THIS MEASURES, EXACTLY, because the first version of this comment claimed
	// more than the code can see.
	//
	// Instance.Running is true for every EC2 state except stopped and terminated —
	// including shutting-down, which the provider reports as running on purpose,
	// since a backend that cannot tell must not report a live job as finished. So
	// this measures HOW LONG LIST KEEPS CLASSIFYING THE INSTANCE AS POTENTIALLY
	// EXECUTING, which is not the same as the guest executing work. The command
	// here is /bin/true; there is no workload to observe.
	//
	// That is still the number that matters, because billet's listener reads
	// exactly this signal: it treats a successful Destroy as proof the compute is
	// gone. The window is the interval in which that belief is wrong by the
	// provider's own account of the world.
	t.Log("=== 4b. how long does the guest keep running after Destroy returned? ===")

	deadline := time.Now().Add(3 * time.Minute)

	for time.Now().Before(deadline) {
		list, err := p.List(ctx)
		if err != nil {
			t.Fatalf("List while waiting for the guest to stop: %v", err)
		}

		running := false

		for _, i := range list {
			if i.ID == inst.ID && i.Running {
				running = true
			}
		}

		if !running {
			// MEASURED FROM BEFORE THE CALL, and said so: start is taken before
			// Destroy, so this includes Destroy's own ~410ms.
			t.Logf("    List stopped classifying it as running %s after Destroy was CALLED",
				time.Since(start).Round(time.Second))

			break
		}

		time.Sleep(5 * time.Second)
	}

	// 5. DESTROY IS IDEMPOTENT, which the listener relies on across retries.
	t.Log("=== 5. is a second Destroy safe? ===")

	if _, err := p.Destroy(ctx, inst.ID); err != nil {
		t.Errorf("    second Destroy returned an error, so a retry would read as "+
			"'the compute may still exist': %v", err)
	} else {
		t.Log("    second Destroy succeeded, which is what makes a retry safe")
	}
}
