package ec2

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"log/slog"
	"os"
	"testing"
	"time"

	"github.com/junioryono/billet/internal/config"
	"github.com/junioryono/billet/internal/provider"
)

// TestLiveSmoke drives this provider against a REAL AWS account.
//
// EVERY OTHER TEST IN THIS PACKAGE TALKS TO A FAKE, which is the standing caveat
// on the whole backend: the signer is pinned to vectors generated by AWS's own
// SDK, the request shapes are pinned to documentation, and neither is the same as
// EC2 accepting them. This is the one test that closes that gap, and it is opt-in
// because it costs money and needs an account.
//
//	BILLET_LIVE_EC2_REGION=us-west-2 \
//	BILLET_LIVE_EC2_SUBNET=subnet-... \
//	BILLET_LIVE_EC2_SG=sg-... \
//	BILLET_LIVE_EC2_IMAGE=ami-... \
//	AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... AWS_SESSION_TOKEN=... \
//	go test ./internal/provider/ec2/ -run TestLiveSmoke -v -count=1
//
// IT DESTROYS WHAT IT LAUNCHES, in a cleanup that runs even on failure, and it
// launches exactly one instance of the smallest shape it is given. What it cannot
// do is prove the absence of a leak: if the process is killed between RunInstances
// and the cleanup, OR if Launch itself fails after RunInstances has already
// committed — a response that will not parse, a context expiring mid-reply — an
// instance survives and this test never learns its id. It is findable by the
// per-run owner tag.
func TestLiveSmoke(t *testing.T) {
	region := os.Getenv("BILLET_LIVE_EC2_REGION")
	if region == "" {
		t.Skip("BILLET_LIVE_EC2_REGION is unset; this test spends money and is opt-in")
	}

	cfg := config.EC2Config{
		Region:           region,
		SubnetID:         os.Getenv("BILLET_LIVE_EC2_SUBNET"),
		SecurityGroupIDs: []string{os.Getenv("BILLET_LIVE_EC2_SG")},
		AssignPublicIP:   false,
		InstanceTypes: []config.EC2InstanceType{
			{Type: "t3.micro", VCPU: 2, Memory: 1 * config.GiB},
		},
	}

	image := os.Getenv("BILLET_LIVE_EC2_IMAGE")

	log := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))

	// A DISTINCT OWNER PER RUN, so this cannot see or destroy anything belonging to
	// a real deployment in the same account.
	owner := "live-smoke-" + time.Now().UTC().Format("20060102150405")

	p, err := New(owner, cfg,
		WithCredentials(EnvCredentials{}),
		WithLogger(log))
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	ctx, cancel := context.WithTimeout(t.Context(), 5*time.Minute)
	defer cancel()

	// 1. THE SIGNER, against real EC2, before anything is bought. A hand-rolled
	// SigV4 that matches AWS's own output byte for byte is still only a claim until
	// EC2 answers something other than 403.
	t.Log("=== 1. can billet's signer talk to EC2 at all? ===")

	before, err := p.List(ctx)
	if err != nil {
		t.Fatalf("List against real EC2: %v", err)
	}

	t.Logf("    List returned %d instances for owner %q (expected 0)", len(before), owner)

	// 2. LAUNCH.
	t.Log("=== 2. does the RunInstances request billet builds actually launch? ===")

	// A FRESH LEASE ID PER RUN, and the first attempt at this test taught why. A
	// fixed one made the second run fail with IdempotentParameterMismatch: the
	// lease id IS the ClientToken, and the same token with different parameters is
	// refused. That is the launch-idempotency design working — confirmed by EC2
	// rather than by reading — and it means a retried launch cannot quietly buy a
	// second instance for one job.
	//
	// HOW LONG EC2 REMEMBERS A TOKEN IS NOT STATED HERE, because I do not know it.
	// The runs that produced the mismatch were MINUTES apart, so minutes is what
	// was observed; AWS's current idempotency page and RunInstances reference both
	// document the mismatch behaviour and neither gives a duration. An earlier
	// version of this comment said 24 hours, which came from nowhere I can cite.
	sum := sha256.Sum256([]byte(owner))
	lease := hex.EncodeToString(sum[:])[:32]

	spec := provider.Spec{
		Name:   provider.InstanceName(lease),
		Image:  image,
		VCPU:   2,
		Memory: 1 * config.GiB,
		// A COMMAND THAT IS NOT A RUNNER. This test is about the API path, not about
		// running a job: there is no AMI containing the GitHub runner yet (#42), so
		// the instance boots, runs this, and is destroyed.
		Command:   []string{"/bin/true"},
		Trust:     provider.TrustTrusted,
		JITConfig: "not-a-real-jit-config",
	}

	inst, err := p.Launch(ctx, spec)

	if inst != nil {
		t.Cleanup(func() {
			// UNCONDITIONAL, because a test failure must not leave an instance
			// running.
			//
			// A FRESH CONTEXT, AND NOT t.Context(), which the linter asks for and
			// which would be wrong here: Go cancels the test context just BEFORE
			// running cleanup functions, so using it would hand a cancelled context
			// to the one call whose whole job is to stop a machine that costs money.
			// The failure mode is a running instance and a passing test.
			//nolint:usetesting // t.Context() is already cancelled when cleanup runs.
			clean, stop := context.WithTimeout(context.Background(), 2*time.Minute)
			defer stop()

			if err := p.Destroy(clean, inst.ID); err != nil {
				t.Errorf("CLEANUP FAILED, instance %s may still be running: %v", inst.ID, err)
			}
		})
	}

	if err != nil {
		t.Fatalf("Launch: %v", err)
	}

	t.Logf("    launched %s", inst.ID)

	// 3. LIST FINDS IT, which exercises the owner tag and the name-to-lease
	// mapping that is the only durable link between compute and a lease.
	t.Log("=== 3. does List find it by owner tag and recover the lease id? ===")

	// POLLED, NOT ASKED ONCE, because the first version of this asked once and got
	// two different answers on two runs of the same code. DescribeInstances is
	// EVENTUALLY CONSISTENT: an instance RunInstances has already returned an id
	// for may not be in the next DescribeInstances response.
	//
	// That is not a curiosity for this backend. Recover enumerates live compute
	// through List, so an instance invisible in the seconds after launch is one a
	// reconciliation pass can conclude does not exist — and act on.
	launched := time.Now()

	var (
		seen    *provider.Instance
		visible time.Duration
	)

	for time.Since(launched) < 90*time.Second {
		found, err := p.List(ctx)
		if err != nil {
			t.Fatalf("List after launch: %v", err)
		}

		for _, i := range found {
			if i.ID == inst.ID {
				seen = i
				visible = time.Since(launched)
			}
		}

		if seen != nil {
			break
		}

		time.Sleep(time.Second)
	}

	if seen == nil {
		t.Errorf("    List never returned the instance within 90s of launching it")
	} else {
		t.Logf("    List first saw it %s after Launch returned; name = %q",
			visible.Round(100*time.Millisecond), seen.Name)

		// ASSERTED, NOT JUST LOGGED. The name is the ONLY durable link between a
		// running instance and the lease that paid for it — recovery reads it back
		// out — and the first version of this test logged it and checked nothing,
		// so a tag round-trip that mangled the name would have passed while the
		// coverage notes claimed this was covered.
		if seen.Name != spec.Name {
			t.Errorf("    the name came back as %q, want %q: the lease id cannot be "+
				"recovered from a running instance", seen.Name, spec.Name)
		}
	}

	// 4. DESTROY, and what it means. This is #46: billet treats a successful
	// Destroy as proof the compute is gone before releasing the lease.
	t.Log("=== 4. what is true at the moment Destroy returns? (#46) ===")

	start := time.Now()

	if err := p.Destroy(ctx, inst.ID); err != nil {
		t.Fatalf("Destroy: %v", err)
	}

	t.Logf("    Destroy returned after %s", time.Since(start).Round(time.Millisecond))

	after, err := p.List(ctx)
	if err != nil {
		t.Fatalf("List after destroy: %v", err)
	}

	still := false

	for _, i := range after {
		if i.ID == inst.ID {
			still = true

			t.Logf("    IMMEDIATELY AFTER Destroy, List still reports it: running=%v", i.Running)
		}
	}

	if !still {
		t.Log("    immediately after Destroy, List no longer reports it")
	}

	// HOW LONG THE WINDOW ACTUALLY IS. The ADR says the guest "keeps running for a
	// minute or two" and cites nothing; this measures it. The number is the length
	// of time billet's listener believes the compute is gone while it is not.
	t.Log("=== 4b. how long does the guest keep running after Destroy returned? ===")

	deadline := time.Now().Add(3 * time.Minute)

	for time.Now().Before(deadline) {
		list, err := p.List(ctx)
		if err != nil {
			t.Fatalf("List while waiting for the guest to stop: %v", err)
		}

		running := false

		for _, i := range list {
			if i.ID == inst.ID && i.Running {
				running = true
			}
		}

		if !running {
			t.Logf("    the guest stopped being reported as running %s after Destroy returned",
				time.Since(start).Round(time.Second))

			break
		}

		time.Sleep(5 * time.Second)
	}

	// 5. DESTROY IS IDEMPOTENT, which the listener relies on across retries.
	t.Log("=== 5. is a second Destroy safe? ===")

	if err := p.Destroy(ctx, inst.ID); err != nil {
		t.Errorf("    second Destroy returned an error, so a retry would read as "+
			"'the compute may still exist': %v", err)
	} else {
		t.Log("    second Destroy succeeded, which is what makes a retry safe")
	}
}
