package ec2

import (
	"net/http"
	"net/url"
	"time"

	"github.com/junioryono/billet/internal/awssig"
)

const (
	ec2Service = "ec2"
)

// sign adds the SigV4 headers required by the EC2 Query API.
//
// The implementation is shared with the AWS storage backend. The vectors in
// sign_test.go were generated by aws-sdk-go-v2 and therefore pin the shared
// signer to AWS's own output rather than to billet's reading of the spec.
func sign(req *http.Request, body []byte, creds Credentials, region string, now time.Time) error {
	return signService(req, body, creds, region, ec2Service, now)
}

func signService(
	req *http.Request,
	body []byte,
	creds Credentials,
	region, service string,
	now time.Time,
) error {
	if creds.AccessKeyID == "" || creds.SecretAccessKey == "" {
		return errNoCredentials
	}

	return awssig.Sign(req, body, awssig.Credentials{
		AccessKeyID:     creds.AccessKeyID,
		SecretAccessKey: creds.SecretAccessKey,
		SessionToken:    creds.SessionToken,
	}, region, service, now)
}

func canonicalQuery(u *url.URL) (string, error) { return awssig.CanonicalQuery(u) }
