package ec2

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/url"
	"sort"
	"strconv"
	"strings"
	"time"
)

// The signing algorithm and the terminator AWS requires in the credential scope.
const (
	algorithm  = "AWS4-HMAC-SHA256"
	terminator = "aws4_request"
	// service is the signing name for EC2, which is part of the credential scope
	// and therefore part of the signature.
	service = "ec2"
)

// amzDateFormat is the compact ISO 8601 AWS wants in X-Amz-Date, and the date
// half of it is the credential scope's first element.
const (
	amzDateFormat = "20060102T150405Z"
	amzDayFormat  = "20060102"
)

// sign adds the SigV4 headers a request needs to be accepted.
//
// HAND-WRITTEN RATHER THAN TAKEN FROM THE AWS SDK, and the reason is measured
// rather than assumed: a program doing nothing but constructing an EC2 client and
// calling RunInstances once builds to 13.2MB and pulls in 15 modules, against a
// whole billet of 21.8MB and 4 direct dependencies. Every node in a fleet would
// carry that, including the bare-metal hosts this backend exists to fall back
// FROM. billet's docker backend refused the Docker SDK for the same reason and a
// far smaller library.
//
// What makes the trade acceptable is that the output is CHECKED AGAINST AWS'S OWN
// SIGNER rather than against a reading of the specification — see sign_test.go,
// which carries a vector generated by aws-sdk-go-v2 and the command that
// regenerates it. A rule about somebody else's API is pinned to what their code
// does.
//
// The body is passed separately because the signature covers its hash, and
// re-reading it off the request would consume the reader the caller is about to
// send.
func sign(req *http.Request, body []byte, creds Credentials, region string, now time.Time) error {
	if creds.AccessKeyID == "" || creds.SecretAccessKey == "" {
		return errNoCredentials
	}

	if req.URL == nil {
		return fmt.Errorf("ec2: cannot sign a request with no url")
	}

	now = now.UTC()
	amzDate := now.Format(amzDateFormat)
	day := now.Format(amzDayFormat)

	// SET BEFORE THE HEADERS ARE CANONICALIZED, because both are signed. A token
	// added afterwards produces a valid-looking signature over a request the
	// service reads differently, which fails as a generic 403.
	req.Header.Set("X-Amz-Date", amzDate)

	if creds.SessionToken != "" {
		req.Header.Set("X-Amz-Security-Token", creds.SessionToken)
	}

	// HOST IS SIGNED BUT IS NOT IN Header. Go carries it on the Request itself and
	// writes it onto the wire separately, so canonicalization has to reach for it
	// explicitly — omitting it yields a signature over a request nobody sent.
	host := req.Host
	if host == "" {
		host = req.URL.Host
	}

	payloadHash := sha256Hex(body)

	canonicalHeaders, signedHeaders := canonicalizeHeaders(req.Header, host, req.ContentLength)

	query, err := canonicalQuery(req.URL)
	if err != nil {
		return err
	}

	canonicalRequest := strings.Join([]string{
		req.Method,
		canonicalURI(req.URL),
		query,
		canonicalHeaders,
		signedHeaders,
		payloadHash,
	}, "\n")

	scope := strings.Join([]string{day, region, service, terminator}, "/")

	stringToSign := strings.Join([]string{
		algorithm,
		amzDate,
		scope,
		sha256Hex([]byte(canonicalRequest)),
	}, "\n")

	signature := hex.EncodeToString(hmacSHA256(signingKey(creds.SecretAccessKey, day, region), stringToSign))

	req.Header.Set("Authorization", fmt.Sprintf(
		"%s Credential=%s/%s, SignedHeaders=%s, Signature=%s",
		algorithm, creds.AccessKeyID, scope, signedHeaders, signature))

	return nil
}

// signingKey derives the request key by chaining HMACs over the scope, which is
// what keeps a leaked signature from being reusable in another region, service or
// day.
func signingKey(secret, day, region string) []byte {
	k := hmacSHA256([]byte("AWS4"+secret), day)
	k = hmacSHA256(k, region)
	k = hmacSHA256(k, service)

	return hmacSHA256(k, terminator)
}

// unsignedHeaders are excluded from the signature, and every one of them is a
// header something OTHER than billet writes.
//
// Authorization is the output, so signing it is circular — and reachable, since a
// retry re-signs a request that already carries the previous attempt's answer.
// The rest are added by Go's transport AFTER this runs (User-Agent), or rewritten
// in flight by proxies and the transport's own chunking (Expect,
// Transfer-Encoding, the trace id). A header billet does not control cannot be
// signed, because the value on the wire would not be the value that was hashed,
// and the request arrives as a bare 403 that says nothing about which header
// moved.
//
// This is AWS's own ignore list, which is the reason to trust it: their signer
// and this one must agree, and sign_test.go asserts they do byte for byte.
var unsignedHeaders = map[string]struct{}{
	"authorization":     {},
	"user-agent":        {},
	"x-amzn-trace-id":   {},
	"expect":            {},
	"transfer-encoding": {},
}

// canonicalizeHeaders renders the headers AWS signs, and the list of their names.
//
// Sorted, lowercased, and with runs of whitespace in the VALUE collapsed — all
// three are the specification's, and all three change the signature, so none of
// them is cosmetic.
func canonicalizeHeaders(h http.Header, host string, contentLength int64) (string, string) {
	// HOST AND CONTENT-LENGTH ARE SIGNED AND NEITHER IS IN THE MAP. Go keeps both
	// on the Request itself and writes them onto the wire separately, so they have
	// to be reached for explicitly. Content-Length only when it is positive, which
	// is the rule AWS's signer applies — including a zero would sign a header the
	// transport then omits.
	values := map[string]string{"host": host}

	if contentLength > 0 {
		values["content-length"] = strconv.FormatInt(contentLength, 10)
	}

	for name, vs := range h {
		lower := strings.ToLower(name)

		if _, skip := unsignedHeaders[lower]; skip {
			continue
		}

		// HOST AND CONTENT-LENGTH ARE ALREADY SET ABOVE, from the Request rather
		// than from this map, because that is where Go keeps the values it actually
		// sends. A caller who also put them in Header would otherwise overwrite the
		// sent value with one the transport ignores — a signature over a request
		// nobody made.
		if lower == "host" || lower == "content-length" {
			continue
		}

		trimmed := make([]string, 0, len(vs))
		for _, v := range vs {
			trimmed = append(trimmed, collapseSpace(v))
		}

		values[lower] = strings.Join(trimmed, ",")
	}

	names := make([]string, 0, len(values))
	for name := range values {
		names = append(names, name)
	}

	sort.Strings(names)

	var b strings.Builder

	for _, name := range names {
		b.WriteString(name)
		b.WriteByte(':')
		b.WriteString(values[name])
		b.WriteByte('\n')
	}

	return b.String(), strings.Join(names, ";")
}

// canonicalURI is the escaped path, with an empty path spelled "/".
func canonicalURI(u *url.URL) string {
	if u.EscapedPath() == "" {
		return "/"
	}

	return u.EscapedPath()
}

// canonicalQuery is the query sorted by name and re-encoded the way SigV4 wants.
//
// IT REFUSES A QUERY IT CANNOT PARSE FAITHFULLY, which is the half that is not
// about encoding. url.Values.Encode is reached through url.Query(), and Query
// DISCARDS ParseQuery's error — so a query Go dislikes is silently reduced rather
// than rejected. Measured: `a=1;b=2` parses to an EMPTY map, because Go has
// refused the semicolon as a separator since 1.17, and `a=1&b=%zz` quietly loses
// b. Either way the signature covers a query the wire does not send, and the
// service answers 403 naming nothing.
//
// NOT url.Values.Encode ALONE for the escaping either, which the previous
// implementation was, described as "the one place Go's normalization and the
// specification happen to agree". They agree on sorting and on most escapes and
// they disagree on SPACE: Encode writes `+` and SigV4 requires `%20`. A literal
// plus is unaffected — Encode has already written it as `%2B` — so replacing
// after the fact can only ever touch an encoded space.
//
// Both faults are latent for this client, which puts every parameter in the POST
// body where the payload hash covers the exact bytes. They are fixed because the
// signer is a general thing, and the next caller to use a query string would
// otherwise inherit a confident comment and an unexplainable 403.
func canonicalQuery(u *url.URL) (string, error) {
	if u.RawQuery == "" {
		return "", nil
	}

	values, err := url.ParseQuery(u.RawQuery)
	if err != nil {
		return "", fmt.Errorf("ec2: refusing to sign a request whose query billet cannot read "+
			"the same way it will be sent, because the signature would cover something else: %w",
			err)
	}

	return strings.ReplaceAll(values.Encode(), "+", "%20"), nil
}

// collapseSpace trims a header value and squeezes internal runs of spaces to
// one, which is what the specification means by a trimmed value.
func collapseSpace(v string) string {
	return strings.Join(strings.Fields(v), " ")
}

func hmacSHA256(key []byte, data string) []byte {
	m := hmac.New(sha256.New, key)
	// hash.Hash documents Write as never returning an error.
	m.Write([]byte(data))

	return m.Sum(nil)
}

func sha256Hex(b []byte) string {
	sum := sha256.Sum256(b)

	return hex.EncodeToString(sum[:])
}
