package ec2

import (
	"net/http"
	"net/url"
	"time"

	"github.com/junioryono/billet/internal/awssig"
)

const (
	ec2Service = "ec2"
)

// sign adds the SigV4 headers required by the EC2 Query API.
//
// The implementation is shared with the AWS storage backend. The vectors in
// sign_test.go were generated by aws-sdk-go-v2 and therefore pin the shared
// signer to AWS's own output rather than to billet's reading of the spec.
func sign(req *http.Request, body []byte, creds awssig.Credentials, region string, now time.Time) error {
	return signService(req, body, creds, region, ec2Service, now)
}

func signService(
	req *http.Request,
	body []byte,
	creds awssig.Credentials,
	region, service string,
	now time.Time,
) error {
	// THE EMPTINESS CHECK AND THE CONVERSION BOTH WENT WITH THE CHAIN. This used to
	// hold ec2's own credential type and its own "no credentials" sentinel, so it
	// checked the key pair itself and then copied three fields into the signer's
	// type. Both were duplicates: awssig.Sign makes the identical check and answers
	// awssig.ErrNoCredentials, and the type it wants is now the type the chain
	// returns. A second reading of the same rule is a second place for it to drift.
	return awssig.Sign(req, body, creds, region, service, now)
}

func canonicalQuery(u *url.URL) (string, error) { return awssig.CanonicalQuery(u) }
