#!/usr/bin/env python3
"""Claude Code hooks for billet: refuse the edits and commands the repository forbids.

usage: guard.py edit|bash|format   (the hook's JSON arrives on stdin)

Exit 0 lets the tool run; exit 2 refuses it, and Claude Code shows stderr to the
session as the reason. A question this script cannot answer refuses too, saying
so: could-not-tell never collapses into permission.
"""
import json
import os
import re
import shlex
import shutil
import subprocess
import sys

MIGRATIONS = ("internal/state/migrations/", "internal/state/pgmigrations/")
GENERATED = "internal/state/ledgerdb/"
DEFAULT_BRANCH = "main"


def refuse(reason):
    print(reason, file=sys.stderr)
    sys.exit(2)


def project_root(payload):
    root = os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd")
    if not root:
        refuse("billet hook: no CLAUDE_PROJECT_DIR and no cwd in the hook input, so the edit cannot be judged")
    return os.path.realpath(root)


def git(root, *args):
    return subprocess.run(["git", "-C", root, *args], capture_output=True, text=True, check=False)


def published(root, rel):
    """True when rel exists on the default branch, False when it does not."""
    for ref in (f"origin/{DEFAULT_BRANCH}", DEFAULT_BRANCH):
        if git(root, "rev-parse", "--verify", "--quiet", ref + "^{commit}").returncode != 0:
            continue
        found = git(root, "cat-file", "-e", f"{ref}:{rel}")
        return found.returncode == 0
    refuse(
        f"billet hook: neither origin/{DEFAULT_BRANCH} nor {DEFAULT_BRANCH} is a commit here, so it cannot tell "
        f"whether {rel} is a published migration; fetch {DEFAULT_BRANCH} and try again"
    )


def judge_edit(payload):
    tool_input = payload.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not path:
        return
    root = project_root(payload)
    full = path if os.path.isabs(path) else os.path.join(payload.get("cwd") or root, path)
    # Judged by the name the tool was given, not where a link resolves: a write
    # through .agents/ is refused even though it would land under .claude/.
    lexical = os.path.normpath(full)
    rel = os.path.relpath(lexical, root)
    if rel.startswith(".."):
        rel = os.path.relpath(os.path.realpath(lexical), root)
        if rel.startswith(".."):
            return

    if rel.startswith(GENERATED):
        refuse(
            f"{rel} is generated by sqlc. Edit the SQL under internal/state/queries/ (or add a migration) and run "
            "`make sqlc`; see the billet-state skill."
        )
    if rel.startswith(MIGRATIONS) and published(root, rel):
        refuse(
            f"{rel} is a published migration: its statement bytes are checksummed in every deployment's ledger "
            "and migrationsAreFrozen holds the sum. Add a new migration with the next version instead; see "
            "internal/state/migrations/README.md and the billet-state skill."
        )
    if rel == "AGENTS.md" or rel.startswith(".agents/"):
        refuse(
            f"{rel} is a committed symlink for Codex. Edit the canonical file instead: CLAUDE.md, or "
            ".claude/skills/<name>/ for a skill."
        )


SEPARATORS = {"&&", "||", ";", "|", "&", "\n"}


def commands(text):
    """Split a shell command line into simple commands, as words."""
    lexer = shlex.shlex(text, posix=True, punctuation_chars=";&|")
    lexer.whitespace_split = True
    lexer.commenters = ""
    try:
        words = list(lexer)
    except ValueError:
        return None
    out, current = [], []
    for w in words:
        if w in SEPARATORS or set(w) <= set(";&|"):
            if current:
                out.append(current)
            current = []
        else:
            current.append(w)
    if current:
        out.append(current)
    return out


def git_subcommand(words):
    """The git subcommand and its arguments, or None when words is not git."""
    while words and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*=.*", words[0]):
        words = words[1:]
    if not words or os.path.basename(words[0]) != "git":
        return None
    rest = words[1:]
    # git's own options before the subcommand; -C and -c take a value
    while rest and rest[0].startswith("-"):
        opt = rest.pop(0)
        if opt in ("-C", "-c", "--git-dir", "--work-tree", "--namespace") and rest:
            rest.pop(0)
    if not rest:
        return None
    return rest[0], rest[1:]


def judge_bash(payload):
    text = (payload.get("tool_input") or {}).get("command") or ""
    if "git" not in text:
        return
    parsed = commands(text)
    if parsed is None:
        if re.search(r"\bgit\b.*\b(push|rebase|commit)\b", text):
            refuse("billet hook: this command line could not be parsed, and it names git push, rebase or commit")
        return
    for words in parsed:
        found = git_subcommand(words)
        if not found:
            continue
        sub, args = found
        if sub == "rebase" or (sub == "pull" and any(a == "--rebase" or a.startswith("--rebase=") for a in args)):
            refuse("billet integrates by merging, never by rebasing; see the billet-git-flow skill.")
        if sub == "push":
            if any(a in ("-f", "--force") or a.startswith("--force") for a in args) or any(
                a.startswith("+") for a in args if not a.startswith("-")
            ):
                refuse("billet never force-pushes, --force-with-lease included; see the billet-git-flow skill.")
            positional = [a for a in args if not a.startswith("-")]
            for refspec in positional[1:]:
                dest = refspec.split(":")[-1]
                if dest in (DEFAULT_BRANCH, f"refs/heads/{DEFAULT_BRANCH}"):
                    refuse(f"billet never pushes to {DEFAULT_BRANCH}; push a branch and open a pull request.")
        if sub == "commit":
            cwd = payload.get("cwd") or project_root(payload)
            branch = git(cwd, "rev-parse", "--abbrev-ref", "HEAD")
            if branch.returncode != 0:
                refuse("billet hook: could not read the current branch, so it cannot tell whether this commits to main")
            if branch.stdout.strip() == DEFAULT_BRANCH:
                refuse(f"billet never commits to {DEFAULT_BRANCH}; create a branch first (billet-git-flow).")


def format_go(payload):
    tool_input = payload.get("tool_input") or {}
    path = tool_input.get("file_path")
    if not path or not path.endswith(".go") or not os.path.isfile(path):
        return
    gofmt = shutil.which("gofmt")
    if gofmt:
        # A file mid-edit may not parse yet; gofmt then leaves it alone.
        subprocess.run([gofmt, "-w", path], capture_output=True, check=False)


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in ("edit", "bash", "format"):
        refuse("usage: guard.py edit|bash|format")
    try:
        payload = json.load(sys.stdin)
    except ValueError as err:
        refuse(f"billet hook: the hook input is not JSON ({err}), so the tool call cannot be judged")
    {"edit": judge_edit, "bash": judge_bash, "format": format_go}[sys.argv[1]](payload)
    sys.exit(0)


if __name__ == "__main__":
    main()
