// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package a

import (
	"context"
	"database/sql"
)

// GENERATED CODE IS THE COMPILED QUERY SET, and its statements ARE the .sql
// files -- so nothing here is expected to be reported. This file exists because
// the skip has to be exercised: without it, every one of the ~180 calls sqlc
// emits into internal/state/sqlitedb would be reported, which is a gate nobody
// could turn on.
const readLeaseEpoch = `-- name: ReadLeaseEpoch :one
SELECT epoch FROM leases WHERE id = ?1
`

type queries struct{ db *sql.DB }

func (q *queries) ReadLeaseEpoch(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, readLeaseEpoch, id)

	var epoch int64
	err := row.Scan(&epoch)

	return epoch, err
}
