package guestassets

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// The filter is the one thing standing between a resolver file and dockerd's dns
// list: a value the daemon rejects there stops it starting, and starting it is a
// precondition for the job, so a bad upstream must never survive. These cases run
// the real script against fixtures and assert the emitted array, so deleting a
// guard changes the output rather than passing a text match.
func TestDNSUpstreamsKeepsOnlyRealGlobalUpstreams(t *testing.T) {
	t.Parallel()

	python, err := exec.LookPath("python3")
	if err != nil {
		t.Skip("python3 is not installed on this development host")
	}

	path := filepath.Join(t.TempDir(), "dns-upstreams.py")
	if err := os.WriteFile(path, []byte(DNSUpstreamsScript), 0o700); err != nil {
		t.Fatalf("write filter: %v", err)
	}

	const gateway = "172.17.0.1"
	for _, tc := range []struct {
		name   string
		resolv string
		want   []string // nil means: emit nothing (do not remap)
	}{
		{
			name:   "a real IPv4 upstream is kept behind the gateway",
			resolv: "nameserver 192.168.1.1\n",
			want:   []string{gateway, "192.168.1.1"},
		},
		{
			name:   "the systemd-resolved stub alone yields no list",
			resolv: "nameserver 127.0.0.53\n",
			want:   nil,
		},
		{
			name:   "a zoned link-local nameserver is dropped, not passed to dockerd",
			resolv: "nameserver fe80::1%eth0\nnameserver 10.0.0.1\n",
			want:   []string{gateway, "10.0.0.1"},
		},
		{
			name:   "an out-of-range octet is rejected rather than breaking the daemon",
			resolv: "nameserver 999.999.999.999\nnameserver 8.8.8.8\n",
			want:   []string{gateway, "8.8.8.8"},
		},
		{
			name:   "a leading-zero octet, which Go rejects, is dropped",
			resolv: "nameserver 010.0.0.1\nnameserver 8.8.4.4\n",
			want:   []string{gateway, "8.8.4.4"},
		},
		{
			name:   "malformed IPv6 (bad group count, double compression, oversize group) is rejected",
			resolv: "nameserver 1:2:3\nnameserver 2001::db8::1\nnameserver 12345::1\nnameserver ::::\nnameserver 8.8.8.8\n",
			want:   []string{gateway, "8.8.8.8"},
		},
		{
			name:   "a native IPv6 upstream is not a reachable fallback on the IPv4 bridge",
			resolv: "nameserver 2001:4860:4860::8888\nnameserver fc00::1\n",
			want:   nil,
		},
		{
			name:   "an IPv4-mapped upstream is emitted as the plain IPv4 it carries",
			resolv: "nameserver ::ffff:8.8.8.8\nnameserver 1.1.1.1\n",
			want:   []string{gateway, "1.1.1.1", "8.8.8.8"},
		},
		{
			name:   "loopback, unspecified and link-local IPv4 are all dropped",
			resolv: "nameserver 127.0.0.1\nnameserver 0.0.0.0\nnameserver 169.254.0.1\n",
			want:   nil,
		},
		{
			name:   "the whole fe80::/10 range is link-local, not just fe80::/16",
			resolv: "nameserver febf::1\nnameserver fe90::1\nnameserver 1.1.1.1\n",
			want:   []string{gateway, "1.1.1.1"},
		},
		{
			name:   "expanded loopback and unspecified spellings are dropped",
			resolv: "nameserver 0:0:0:0:0:0:0:1\nnameserver 0:0:0:0:0:0:0:0\nnameserver 1.0.0.1\n",
			want:   []string{gateway, "1.0.0.1"},
		},
		{
			name:   "IPv4-mapped loopback, link-local and multicast are dropped",
			resolv: "nameserver ::ffff:7f00:1\nnameserver ::ffff:a9fe:1\nnameserver ::ffff:e000:1\nnameserver 9.9.9.9\n",
			want:   []string{gateway, "9.9.9.9"},
		},
		{
			name:   "multicast is not an upstream",
			resolv: "nameserver 239.255.255.250\nnameserver ff02::1\nnameserver 9.9.9.9\n",
			want:   []string{gateway, "9.9.9.9"},
		},
		{
			name:   "broadcast, reserved and this-network are not upstreams, private IPv4 is",
			resolv: "nameserver 255.255.255.255\nnameserver 240.0.0.1\nnameserver 0.0.0.1\nnameserver ::ffff:255.255.255.255\nnameserver 192.168.0.1\n",
			want:   []string{gateway, "192.168.0.1"},
		},
		{
			name:   "the gateway itself is never a fallback, so a gateway-only resolver yields nothing",
			resolv: "nameserver 172.17.0.1\n",
			want:   nil,
		},
		{
			name:   "an IPv4-mapped spelling of the gateway is still the gateway, not a fallback",
			resolv: "nameserver ::ffff:172.17.0.1\n",
			want:   nil,
		},
		{
			name:   "duplicates collapse and order is gateway-first",
			resolv: "nameserver 8.8.8.8\nnameserver 8.8.8.8\nnameserver 1.1.1.1\n",
			want:   []string{gateway, "1.1.1.1", "8.8.8.8"},
		},
		{
			name:   "a comment-only resolver yields nothing",
			resolv: "# generated by something\nsearch example.com\n",
			want:   nil,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			resolv := filepath.Join(t.TempDir(), "resolv.conf")
			if err := os.WriteFile(resolv, []byte(tc.resolv), 0o600); err != nil {
				t.Fatalf("write resolv: %v", err)
			}
			out, err := exec.CommandContext(t.Context(), python, path, gateway, resolv).Output()
			if err != nil {
				t.Fatalf("run filter: %v", err)
			}
			if tc.want == nil {
				if len(out) != 0 {
					t.Fatalf("expected no list, got %q", out)
				}
				return
			}
			var got []string
			if err := json.Unmarshal(out, &got); err != nil {
				t.Fatalf("filter emitted invalid JSON %q: %v", out, err)
			}
			if len(got) != len(tc.want) {
				t.Fatalf("dns list = %v, want %v", got, tc.want)
			}
			for i := range tc.want {
				if got[i] != tc.want[i] {
					t.Fatalf("dns list = %v, want %v", got, tc.want)
				}
			}
		})
	}
}
