# A NARROW STATE-CONNECTION OBJECT AND NOTHING ELSE.
#
# This module exposes "only a narrow state-connection object", and the
# narrowness is the contract rather than tidiness: a control-plane module has no
# business resizing somebody's database, so it gets no instance handle and no ARN
# it could pass to a modify call.
#
# NOTHING HERE IS A SECRET. The DSN carries a password, and billet's own
# `server.state.postgres.dsn_env` names an ENVIRONMENT VARIABLE rather than
# carrying a connection string precisely so the password never lands in YAML, a
# plan, a state file or cloud-init. What crosses this boundary is the ARN of a
# secret and the IAM statement that reads it — identifiers, not credentials.

output "connection" {
  description = "What a billet control plane needs in order to reach this ledger: the host, the port, the database and the username. Everything except the password, which is what dsn_env exists to keep out of this object."
  value = {
    endpoint = local.endpoint
    port     = local.port
    database = local.database
    username = local.username
    # ADOPTED SAYS WHICH SIDE IS REAL, so a caller can tell "billet made this and
    # its backups are configured here" from "this is yours" without inferring it
    # from which other outputs happen to be empty.
    adopted = !local.create
  }
}

output "dsn_template" {
  description = <<-EOT
    The BILLET_STATE_DSN this deployment needs, with the password left as a
    placeholder — so its shape is stated once here rather than reconstructed by
    hand on every host.

    THE PASSWORD MUST BE PERCENT-ENCODED when you substitute it. This is a URI,
    and RDS generates passwords containing punctuation: a `#` truncates
    everything after it, a `%` starts an escape, and a `?` starts the query
    string — so a pasted password can silently change which database, user or
    options billet connects with, or fail to parse at all. See the module README
    for the substitution that encodes it.

    sslrootcert IS PART OF THE TEMPLATE, and without it verify-full cannot
    succeed against RDS. RDS server certificates are issued by self-signed
    per-region "Amazon RDS ... Root CA" authorities (measured against the
    published bundle) which are in NO operating system trust store, so a
    verify-full connection with nothing to verify against fails on every stock
    host. ssl_bundle_url is where that file comes from.

    search_path is NOT here, and that is deliberate rather than an omission: it
    is the one part of this that depends on how YOU laid the database out. Two
    billet deployments sharing one PostgreSQL need a schema each (billet's
    catalogue questions are scoped to current_schema()), and this module cannot
    know what you called them — append `&options=-csearch_path%%3D<schema>` when
    that is the shape you chose.
  EOT
  value       = "postgres://${local.username}:PASSWORD@${local.endpoint}:${local.port}/${local.database}?sslmode=${var.sslmode}&sslrootcert=${var.ssl_root_cert_path}"
}

output "ssl_bundle_url" {
  description = "Where the RDS certificate bundle for this region comes from. Install it at ssl_root_cert_path on the controller — the junioryono.billet.host role does it from billet_state_ca_bundle_src — or verify-full has nothing to verify against. Empty for an adopted endpoint, whose TLS is yours."
  value       = local.create ? "https://truststore.pki.rds.amazonaws.com/${data.aws_region.this.region}/${data.aws_region.this.region}-bundle.pem" : ""
}

output "ssl_root_cert_path" {
  description = "Where the controller is expected to keep that bundle; it is what dsn_template names as sslrootcert."
  value       = var.ssl_root_cert_path
}

output "security_group_id" {
  description = "The created database's own security group, or empty for an adopted endpoint. A control plane's egress does not need it — the ingress rule here references the CONTROLLER's group — but a caller adding a second client does."
  value       = local.create ? aws_security_group.ledger[0].id : ""
}

output "master_secret_arn" {
  description = "The ARN of the AWS-managed master credential for a created instance, or empty. It holds {username, password} as JSON, is generated by AWS and never passes through Terraform, and is what a host resolves into BILLET_STATE_DSN at install time. Empty for an adopted endpoint, whose credential story stays yours."
  value       = local.master_secret_arn
}

output "dsn_secret_arn" {
  description = "The secret holding a complete DSN, if you keep one — this module never creates it, because writing a DSN would mean this module knowing the password. Passed through from var.dsn_secret_arn so a control-plane module can grant read on it in the same breath as the master credential."
  value       = var.dsn_secret_arn
}

output "secret_read_policy_json" {
  description = <<-EOT
    An IAM policy granting read on exactly the secrets above, and nothing else —
    attach it to the control plane's role so a host can assemble
    BILLET_STATE_DSN without a long-lived credential of its own.

    IT CARRIES kms:Decrypt WHEN A CUSTOMER KEY IS SET, and must. Secrets Manager
    decrypts the value on the caller's behalf, so GetSecretValue against a secret
    encrypted with a customer-managed key ALSO requires kms:Decrypt on that key —
    a grant with the Secrets Manager actions alone returns AccessDenied, and it
    does so only for the deployments that hardened their encryption, which is the
    worst possible set to break.

    EMPTY WHEN THERE IS NOTHING TO GRANT (an adopted endpoint with no
    dsn_secret_arn), because an IAM policy with an empty Resource list is not a
    narrower grant, it is an invalid document.
  EOT
  value = length(local.readable_secret_arns) == 0 ? "" : jsonencode({
    Version = "2012-10-17"
    Statement = concat(
      [{
        Sid      = "BilletReadLedgerCredential"
        Effect   = "Allow"
        Action   = ["secretsmanager:GetSecretValue", "secretsmanager:DescribeSecret"]
        Resource = local.readable_secret_arns
      }],
      var.kms_key_arn == "" ? [] : [{
        Sid      = "BilletDecryptLedgerCredential"
        Effect   = "Allow"
        Action   = ["kms:Decrypt"]
        Resource = [var.kms_key_arn]
        # SCOPED TO SECRETS MANAGER, so the key cannot be called directly — the
        # same condition the backup bucket's grant puts on its own key.
        Condition = {
          StringEquals = {
            "kms:ViaService" = "secretsmanager.${data.aws_region.this.region}.${data.aws_partition.this.dns_suffix}"
          }
        }
      }],
    )
  })
}
