package scripts_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// claudeGuardScript is the one program every billet hook runs.
const claudeGuardScript = "../.claude/hooks/guard.py"

// claudeHookRepo is a throwaway repository shaped like billet's: one published
// migration on main (and origin/main), a working branch, and nothing else.
func claudeHookRepo(t *testing.T, withMain bool) string {
	t.Helper()

	dir := t.TempDir()

	run := func(args ...string) {
		t.Helper()

		cmd := exec.CommandContext(t.Context(), "git", append([]string{"-C", dir}, args...)...)
		cmd.Env = append(os.Environ(), "GIT_CONFIG_GLOBAL=/dev/null", "GIT_CONFIG_SYSTEM=/dev/null")

		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}

	branch := "main"
	if !withMain {
		branch = "trunk"
	}

	run("init", "-q", "-b", branch)
	run("config", "user.email", "test@example.com")
	run("config", "user.name", "test")

	migration := filepath.Join(dir, "internal", "state", "migrations", "0001_init.sql")
	if err := os.MkdirAll(filepath.Dir(migration), 0o755); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(migration, []byte("-- +billet:statement\nSELECT 1;\n-- +billet:end\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	run("add", ".")
	run("commit", "-q", "-m", "init")

	if withMain {
		run("update-ref", "refs/remotes/origin/main", "HEAD")
	}

	run("checkout", "-q", "-b", "junior-oct03-work")

	return dir
}

// runClaudeGuard runs one hook and answers its exit status and stderr.
func runClaudeGuard(t *testing.T, mode, root string, payload map[string]any) (int, string) {
	t.Helper()

	body, err := json.Marshal(payload)
	if err != nil {
		t.Fatal(err)
	}

	return runClaudeGuardRaw(t, mode, root, body)
}

func runClaudeGuardRaw(t *testing.T, mode, root string, body []byte) (int, string) {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "python3", claudeGuardScript, mode)
	cmd.Stdin = bytes.NewReader(body)
	cmd.Env = append(os.Environ(), "CLAUDE_PROJECT_DIR="+root, "GIT_CONFIG_GLOBAL=/dev/null",
		"GIT_CONFIG_SYSTEM=/dev/null")

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err == nil {
		return 0, stderr.String()
	}

	if exit, ok := errors.AsType[*exec.ExitError](err); ok {
		return exit.ExitCode(), stderr.String()
	}

	t.Fatalf("run %s: %v", claudeGuardScript, err)

	return -1, ""
}

func editPayload(root, rel string) map[string]any {
	return map[string]any{
		"tool_name": "Edit", "cwd": root,
		"tool_input": map[string]any{"file_path": filepath.Join(root, rel)},
	}
}

func bashPayload(root, command string) map[string]any {
	return map[string]any{"tool_name": "Bash", "cwd": root, "tool_input": map[string]any{"command": command}}
}

// THE EDIT GUARD REFUSES WHAT THE REPOSITORY SAYS NOBODY EDITS, AND NOTHING ELSE.
func TestTheEditHookRefusesGeneratedCodePublishedMigrationsAndSymlinkPaths(t *testing.T) {
	t.Parallel()

	root := claudeHookRepo(t, true)

	for _, tc := range []struct {
		rel    string
		refuse string // a clause the refusal must carry; empty means allowed
	}{
		{"internal/state/ledgerdb/queries.sql.go", "generated by sqlc"},
		{"internal/state/migrations/0001_init.sql", "published migration"},
		{"internal/state/pgmigrations/0001_init.sql", ""},
		{"internal/state/migrations/0002_new.sql", ""},
		{"internal/state/queries/leases.sql", ""},
		{"AGENTS.md", "committed symlink"},
		{".agents/skills/billet-state/SKILL.md", "committed symlink"},
		{"CLAUDE.md", ""},
		{"internal/server/listener.go", ""},
	} {
		code, stderr := runClaudeGuard(t, "edit", root, editPayload(root, tc.rel))

		switch {
		case tc.refuse == "" && code != 0:
			t.Errorf("%s: refused (%d) though nothing forbids it: %s", tc.rel, code, stderr)
		case tc.refuse != "" && code != 2:
			t.Errorf("%s: exit %d, want 2 (refused)", tc.rel, code)
		case tc.refuse != "" && !strings.Contains(stderr, tc.refuse):
			t.Errorf("%s: refused with %q, want it to say %q", tc.rel, stderr, tc.refuse)
		}
	}

	// A relative path is the cwd's, and a path outside the project is not judged.
	rel := map[string]any{"tool_name": "Write", "cwd": root, "tool_input": map[string]any{
		"file_path": "internal/state/ledgerdb/models.go",
	}}
	if code, _ := runClaudeGuard(t, "edit", root, rel); code != 2 {
		t.Errorf("a relative path into ledgerdb: exit %d, want 2", code)
	}

	outside := editPayload(t.TempDir(), "internal/state/ledgerdb/models.go")
	if code, stderr := runClaudeGuard(t, "edit", root, outside); code != 0 {
		t.Errorf("a path outside the project was judged: exit %d: %s", code, stderr)
	}
}

// COULD NOT TELL IS NOT PERMISSION. Without main or origin/main the hook cannot
// know a migration is unpublished, so it refuses and says why.
func TestTheEditHookRefusesAMigrationItCannotJudge(t *testing.T) {
	t.Parallel()

	root := claudeHookRepo(t, false)

	code, stderr := runClaudeGuard(t, "edit", root, editPayload(root, "internal/state/migrations/0002_new.sql"))
	if code != 2 || !strings.Contains(stderr, "cannot tell") {
		t.Errorf("exit %d, stderr %q; want a refusal saying it cannot tell", code, stderr)
	}

	if code, stderr := runClaudeGuardRaw(t, "edit", root, []byte("not json")); code != 2 || !strings.Contains(stderr, "not JSON") {
		t.Errorf("unparseable input: exit %d, stderr %q; want a refusal", code, stderr)
	}
}

// THE BASH GUARD HOLDS THE GIT FLOW: NO FORCE, NO REBASE, NOTHING ONTO MAIN.
func TestTheBashHookHoldsTheGitFlow(t *testing.T) {
	t.Parallel()

	root := claudeHookRepo(t, true)

	for _, tc := range []struct {
		command string
		refuse  string
	}{
		{"git push --force origin junior-oct03-work", "force"},
		{"git push -f", "force"},
		{"git push --force-with-lease origin junior-oct03-work", "force"},
		{"git push origin +junior-oct03-work", "force"},
		{"git push origin main", "never pushes to main"},
		{"git push origin HEAD:main", "never pushes to main"},
		{"git push origin HEAD:refs/heads/main", "never pushes to main"},
		{"git rebase main", "merging"},
		{"git -C /somewhere rebase -i main", "merging"},
		{"git pull --rebase", "merging"},
		{"GIT_EDITOR=true git rebase --continue", "merging"},
		{"make check && git push origin main", "never pushes to main"},
		{"git push -u origin junior-oct03-work", ""},
		{"git pull", ""},
		{"git commit -m 'work'", ""},
		{"echo git rebase main", ""},
		{"go test ./... | tee out.log", ""},
		{"gh pr merge 357 --merge", ""},
	} {
		code, stderr := runClaudeGuard(t, "bash", root, bashPayload(root, tc.command))

		switch {
		case tc.refuse == "" && code != 0:
			t.Errorf("%q: refused (%d) though nothing forbids it: %s", tc.command, code, stderr)
		case tc.refuse != "" && code != 2:
			t.Errorf("%q: exit %d, want 2 (refused)", tc.command, code)
		case tc.refuse != "" && !strings.Contains(stderr, tc.refuse):
			t.Errorf("%q: refused with %q, want it to say %q", tc.command, stderr, tc.refuse)
		}
	}
}

// A COMMIT ON MAIN IS REFUSED BY THE BRANCH IT WOULD LAND ON.
func TestTheBashHookRefusesACommitOnMain(t *testing.T) {
	t.Parallel()

	root := claudeHookRepo(t, true)

	checkout := exec.CommandContext(t.Context(), "git", "-C", root, "checkout", "-q", "main")
	if out, err := checkout.CombinedOutput(); err != nil {
		t.Fatalf("checkout main: %v\n%s", err, out)
	}

	code, stderr := runClaudeGuard(t, "bash", root, bashPayload(root, "git commit -m 'oops'"))
	if code != 2 || !strings.Contains(stderr, "never commits to main") {
		t.Errorf("exit %d, stderr %q; want a refusal naming main", code, stderr)
	}
}

// THE FORMAT HOOK REFORMATS GO, LEAVES EVERYTHING ELSE, AND NEVER REFUSES.
func TestTheFormatHookRunsGofmtOnGoFilesOnly(t *testing.T) {
	t.Parallel()

	if _, err := exec.LookPath("gofmt"); err != nil {
		t.Skip("gofmt is not on PATH")
	}

	root := t.TempDir()
	goFile := filepath.Join(root, "x.go")
	text := filepath.Join(root, "x.md")

	for path, body := range map[string]string{goFile: "package x\nfunc  F( ) {}\n", text: "func  F( ) {}\n"} {
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	for _, path := range []string{goFile, text} {
		payload := map[string]any{"tool_name": "Write", "cwd": root, "tool_input": map[string]any{"file_path": path}}
		if code, stderr := runClaudeGuard(t, "format", root, payload); code != 0 {
			t.Fatalf("%s: exit %d: %s", path, code, stderr)
		}
	}

	if got, err := os.ReadFile(goFile); err != nil || string(got) != "package x\n\nfunc F() {}\n" {
		t.Errorf("the Go file reads %q (%v) after the hook; want it gofmt'd", got, err)
	}

	if got, err := os.ReadFile(text); err != nil || string(got) != "func  F( ) {}\n" {
		t.Errorf("a non-Go file was changed to %q (%v)", got, err)
	}
}
