// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admission.sql

package ledgerdb

import (
	"context"
)

const listAdmissionRows = `-- name: ListAdmissionRows :many
SELECT id, mode, generation, provenance, reason, actor, changed_at FROM admission
`

// Every row of the admission table, for the pristine check a restore depends on.
//
// ALL OF THEM, not one: proving a ledger is untouched means proving there is
// exactly the single row its migration inserted, and a query that selected
// `WHERE id = 1` could not see a second one.
func (q *Queries) ListAdmissionRows(ctx context.Context) ([]Admission, error) {
	rows, err := q.db.QueryContext(ctx, listAdmissionRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admission
	for rows.Next() {
		var i Admission
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.Generation,
			&i.Provenance,
			&i.Reason,
			&i.Actor,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAdmission = `-- name: ReadAdmission :one
SELECT mode, generation, provenance, reason, actor, changed_at
  FROM admission WHERE id = 1
`

type ReadAdmissionRow struct {
	Mode       string
	Generation int64
	Provenance string
	Reason     string
	Actor      string
	ChangedAt  string
}

// The deployment's admission state.
//
// The row is inserted by the migration that creates the table, so sql.ErrNoRows
// means something is wrong with the ledger rather than that admission is open.
// ReadAdmission in admission.go is where that distinction is made.
func (q *Queries) ReadAdmission(ctx context.Context) (ReadAdmissionRow, error) {
	row := q.db.QueryRowContext(ctx, readAdmission)
	var i ReadAdmissionRow
	err := row.Scan(
		&i.Mode,
		&i.Generation,
		&i.Provenance,
		&i.Reason,
		&i.Actor,
		&i.ChangedAt,
	)
	return i, err
}

const setAdmission = `-- name: SetAdmission :exec
UPDATE admission
   SET mode = $1, generation = $2, provenance = $3,
       reason = $4, actor = $5, changed_at = $6
 WHERE id = 1 AND generation = $7
`

type SetAdmissionParams struct {
	Mode       string
	Generation int64
	Provenance string
	Reason     string
	Actor      string
	ChangedAt  string
	Expect     int64
}

// One admission transition, refusing if the generation moved.
//
// THE GENERATION IS IN THE WHERE as well as the SET: the caller has already
// compared it inside this transaction, and repeating it here means a write can
// never land on a row it did not read.
func (q *Queries) SetAdmission(ctx context.Context, arg SetAdmissionParams) error {
	_, err := q.db.ExecContext(ctx, setAdmission,
		arg.Mode,
		arg.Generation,
		arg.Provenance,
		arg.Reason,
		arg.Actor,
		arg.ChangedAt,
		arg.Expect,
	)
	return err
}
