// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: barrier.sql

package ledgerdb

import (
	"context"
)

const anyBarrierRunExists = `-- name: AnyBarrierRunExists :one
SELECT EXISTS(SELECT 1 FROM compute_barrier_nodes)
`

// Whether the fleet has any run at all, for the same reason.
func (q *Queries) AnyBarrierRunExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, anyBarrierRunExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const barrierRunExists = `-- name: BarrierRunExists :one
SELECT EXISTS(SELECT 1 FROM compute_barrier_nodes WHERE node = $1)
`

// Whether one host has a run at all.
//
// READ BEFORE THE WRITE, and that is not a micro-optimisation: the invalidation
// runs on EVERY registration, ahead of the revocation check, so a credential an
// operator has taken back can call it as fast as it can open connections. An
// unconditional write transaction would let it reserve SQLite's single writer
// slot over and over and starve every scheduling decision in the process.
func (q *Queries) BarrierRunExists(ctx context.Context, node string) (bool, error) {
	row := q.db.QueryRowContext(ctx, barrierRunExists, node)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const bumpDispatchGeneration = `-- name: BumpDispatchGeneration :one

UPDATE nodes SET dispatch_generation = dispatch_generation + 1
 WHERE name = $1
 RETURNING dispatch_generation
`

// The compute barrier: a durable request that every host in the fleet be ASKED
// what it is running, and the fenced answers.
//
// WHY THE LEDGER CANNOT ANSWER THIS ON ITS OWN. alloc.Quiescence reads leases,
// and the class this exists for is compute whose lease has already gone: a
// listener that loses a running lease keeps an in-memory obligation to destroy
// what it launched, and a launch whose lease was reclaimed can create compute it
// then fails to destroy. Neither is in the ledger and neither survives a restart,
// but both leave an instance carrying billet's own name on the host's provider.
//
// WHAT MAKES AN ANSWER CAUSAL IS TWO FENCES, and every statement here carries
// both. `node_epoch` is the registration in force -- a reconnect moves it, so a
// proof about a previous incarnation stops counting. `dispatch_generation` is
// advanced durably BEFORE a launch enters that host's queue, so an answer that
// crossed a launch matches nothing rather than being believed.
//
// WHAT IS STORED IS A CONTINUOUS RUN, NOT A SNAPSHOT. An error, a non-empty list
// or either fence moving DELETES the row rather than ageing it, and the proof is
// `observed_at - empty_since` -- two observations spanning the grace, never one
// observation plus elapsed wall clock. A host that answered empty once and then
// disconnected must not age into proved.
// Advance one host's launch-dispatch fence and return the new value.
//
// IT COUNTS LAUNCHES, NOT COMMANDS. A destroy, sweep, tend or inventory cannot
// create compute, so charging them would void proofs for no reason.
//
// sql.ErrNoRows means the host has no row -- and a host with no row cannot be
// proved clear either, since every clearance walks the node table, so there is no
// fence to advance and nothing about it that could later be believed.
func (q *Queries) BumpDispatchGeneration(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpDispatchGeneration, name)
	var dispatch_generation int64
	err := row.Scan(&dispatch_generation)
	return dispatch_generation, err
}

const deleteBarrierRun = `-- name: DeleteBarrierRun :exec
DELETE FROM compute_barrier_nodes WHERE node = $1
`

// Discard one host's continuous-empty run.
func (q *Queries) DeleteBarrierRun(ctx context.Context, node string) error {
	_, err := q.db.ExecContext(ctx, deleteBarrierRun, node)
	return err
}

const deleteComputeBarrier = `-- name: DeleteComputeBarrier :exec
DELETE FROM compute_barrier WHERE id = 1
`

// Remove a request that can no longer mean anything.
func (q *Queries) DeleteComputeBarrier(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteComputeBarrier)
	return err
}

const deleteEveryBarrierRun = `-- name: DeleteEveryBarrierRun :exec
DELETE FROM compute_barrier_nodes
`

// Discard what every host had proved.
//
// REACHED FROM THREE PLACES AND EACH ONE MATTERS. A superseded barrier's
// observations go with it, because they were taken under a generation somebody
// has since moved and admission was open in between. A dropped barrier takes its
// own. And an arrival that cannot be ATTRIBUTED to a host -- a loopback
// registration whose body would not decode -- invalidates everything, because "I
// could not tell who arrived" must not read as "nothing changed".
func (q *Queries) DeleteEveryBarrierRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteEveryBarrierRun)
	return err
}

const hostReportsCompute = `-- name: HostReportsCompute :one
SELECT EXISTS(
  SELECT 1 FROM node_inventory i
    JOIN nodes n ON n.name = i.node
   WHERE i.node = $1 AND i.node_epoch = n.epoch AND i.running > 0)
`

// The same question about one host.
//
// ASKED BY provedTx AS WELL AS BY THE FLEET REPORT, so the two cannot disagree
// about one host at one instant. Without it a machine actively reporting compute
// could be decommissioned as PROVEN -- permanently out of the expected set, on a
// run whose samples simply predated the instance becoming visible.
func (q *Queries) HostReportsCompute(ctx context.Context, node string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hostReportsCompute, node)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBarrierRuns = `-- name: ListBarrierRuns :many
SELECT node, node_epoch, dispatch_generation, empty_since, observed_at
  FROM compute_barrier_nodes WHERE barrier_id = $1
`

type ListBarrierRunsRow struct {
	Node               string
	NodeEpoch          int64
	DispatchGeneration int64
	EmptySince         string
	ObservedAt         string
}

// Every run recorded under one barrier.
func (q *Queries) ListBarrierRuns(ctx context.Context, barrierID string) ([]ListBarrierRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBarrierRuns, barrierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarrierRunsRow
	for rows.Next() {
		var i ListBarrierRunsRow
		if err := rows.Scan(
			&i.Node,
			&i.NodeEpoch,
			&i.DispatchGeneration,
			&i.EmptySince,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetClearance = `-- name: ListFleetClearance :many
SELECT name, live, epoch, dispatch_generation, wire_version,
       decommissioned_at, decommission_proven, decommission_actor
  FROM nodes
 ORDER BY name
`

type ListFleetClearanceRow struct {
	Name               string
	Live               int64
	Epoch              int64
	DispatchGeneration int64
	WireVersion        int64
	DecommissionedAt   string
	DecommissionProven int64
	DecommissionActor  string
}

// Every host, with what a clearance needs to judge it.
func (q *Queries) ListFleetClearance(ctx context.Context) ([]ListFleetClearanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetClearance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetClearanceRow
	for rows.Next() {
		var i ListFleetClearanceRow
		if err := rows.Scan(
			&i.Name,
			&i.Live,
			&i.Epoch,
			&i.DispatchGeneration,
			&i.WireVersion,
			&i.DecommissionedAt,
			&i.DecommissionProven,
			&i.DecommissionActor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsReportingCompute = `-- name: ListHostsReportingCompute :many
SELECT i.node
  FROM node_inventory i
  JOIN nodes n ON n.name = i.node
 WHERE i.node_epoch = n.epoch AND i.running > 0
`

// The hosts whose own last word, under the registration in force, was that they
// were running something.
//
// TELEMETRY THAT CAN NEVER CLEAR AND MAY ALWAYS BLOCK. The node lists its
// provider and THEN posts, so this can never be a proof -- but a host SAYING it
// is running something is a fact, and the two coexist precisely when a create the
// provider accepted has not yet been listed: a run completes around it and no
// fence moves.
func (q *Queries) ListHostsReportingCompute(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHostsReportingCompute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var node string
		if err := rows.Scan(&node); err != nil {
			return nil, err
		}
		items = append(items, node)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readBarrierRun = `-- name: ReadBarrierRun :one
SELECT node_epoch, dispatch_generation, empty_since, observed_at
  FROM compute_barrier_nodes WHERE node = $1 AND barrier_id = $2
`

type ReadBarrierRunParams struct {
	Node      string
	BarrierID string
}

type ReadBarrierRunRow struct {
	NodeEpoch          int64
	DispatchGeneration int64
	EmptySince         string
	ObservedAt         string
}

// One host's run under one barrier.
func (q *Queries) ReadBarrierRun(ctx context.Context, arg ReadBarrierRunParams) (ReadBarrierRunRow, error) {
	row := q.db.QueryRowContext(ctx, readBarrierRun, arg.Node, arg.BarrierID)
	var i ReadBarrierRunRow
	err := row.Scan(
		&i.NodeEpoch,
		&i.DispatchGeneration,
		&i.EmptySince,
		&i.ObservedAt,
	)
	return i, err
}

const readComputeBarrier = `-- name: ReadComputeBarrier :one
SELECT barrier_id, admission_generation, requested_at, requested_by
  FROM compute_barrier WHERE id = 1
`

type ReadComputeBarrierRow struct {
	BarrierID           string
	AdmissionGeneration int64
	RequestedAt         string
	RequestedBy         string
}

// The durable barrier request, if there is one.
func (q *Queries) ReadComputeBarrier(ctx context.Context) (ReadComputeBarrierRow, error) {
	row := q.db.QueryRowContext(ctx, readComputeBarrier)
	var i ReadComputeBarrierRow
	err := row.Scan(
		&i.BarrierID,
		&i.AdmissionGeneration,
		&i.RequestedAt,
		&i.RequestedBy,
	)
	return i, err
}

const readNodeBarrierFence = `-- name: ReadNodeBarrierFence :one
SELECT epoch, dispatch_generation, wire_version, live FROM nodes WHERE name = $1
`

type ReadNodeBarrierFenceRow struct {
	Epoch              int64
	DispatchGeneration int64
	WireVersion        int64
	Live               int64
}

// The fence a barrier observation of this host must carry, plus liveness.
//
// LIVENESS IS NOT PART OF THE FENCE and travels here only so one read answers the
// whole question: a host billet cannot reach still holds whatever it holds.
func (q *Queries) ReadNodeBarrierFence(ctx context.Context, name string) (ReadNodeBarrierFenceRow, error) {
	row := q.db.QueryRowContext(ctx, readNodeBarrierFence, name)
	var i ReadNodeBarrierFenceRow
	err := row.Scan(
		&i.Epoch,
		&i.DispatchGeneration,
		&i.WireVersion,
		&i.Live,
	)
	return i, err
}

const readNodeFence = `-- name: ReadNodeFence :one
SELECT epoch, dispatch_generation FROM nodes WHERE name = $1
`

type ReadNodeFenceRow struct {
	Epoch              int64
	DispatchGeneration int64
}

// Just the two fences, for the paths that have already decided about liveness.
func (q *Queries) ReadNodeFence(ctx context.Context, name string) (ReadNodeFenceRow, error) {
	row := q.db.QueryRowContext(ctx, readNodeFence, name)
	var i ReadNodeFenceRow
	err := row.Scan(&i.Epoch, &i.DispatchGeneration)
	return i, err
}

const recordBarrierRun = `-- name: RecordBarrierRun :exec
INSERT INTO compute_barrier_nodes
     (node, barrier_id, node_epoch, dispatch_generation, empty_since, observed_at)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT(node) DO UPDATE SET
     barrier_id          = excluded.barrier_id,
     node_epoch          = excluded.node_epoch,
     dispatch_generation = excluded.dispatch_generation,
     empty_since = CASE
         WHEN compute_barrier_nodes.barrier_id          = excluded.barrier_id
          AND compute_barrier_nodes.node_epoch          = excluded.node_epoch
          AND compute_barrier_nodes.dispatch_generation = excluded.dispatch_generation
         THEN compute_barrier_nodes.empty_since
         ELSE excluded.empty_since
     END,
     observed_at = excluded.observed_at
`

type RecordBarrierRunParams struct {
	Node               string
	BarrierID          string
	NodeEpoch          int64
	DispatchGeneration int64
	Now                string
}

// Extend one host's continuous-empty run, or start a new one.
//
// THE RUN'S START IS PRESERVED, AND ONLY WHERE EVERY PART OF ITS IDENTITY
// MATCHES. Taking excluded.empty_since unconditionally would restart the clock on
// every sample, so a host could never cross the grace no matter how long it
// stayed empty; taking the stored one unconditionally would carry a run across a
// reconnect or a launch. The CASE is what makes it a run rather than either.
func (q *Queries) RecordBarrierRun(ctx context.Context, arg RecordBarrierRunParams) error {
	_, err := q.db.ExecContext(ctx, recordBarrierRun,
		arg.Node,
		arg.BarrierID,
		arg.NodeEpoch,
		arg.DispatchGeneration,
		arg.Now,
	)
	return err
}

const upsertComputeBarrier = `-- name: UpsertComputeBarrier :exec
INSERT INTO compute_barrier
     (id, barrier_id, admission_generation, requested_at, requested_by)
VALUES (1, $1, $2, $3, $4)
ON CONFLICT(id) DO UPDATE SET
     barrier_id           = excluded.barrier_id,
     admission_generation = excluded.admission_generation,
     requested_at         = excluded.requested_at,
     requested_by         = excluded.requested_by
`

type UpsertComputeBarrierParams struct {
	BarrierID           string
	AdmissionGeneration int64
	RequestedAt         string
	RequestedBy         string
}

// Record the one barrier request this deployment may have outstanding.
//
// A SINGLETON BY CONSTRUCTION (id = 1, CHECKed by the schema): two barriers would
// each be collecting observations the other's generation invalidates.
func (q *Queries) UpsertComputeBarrier(ctx context.Context, arg UpsertComputeBarrierParams) error {
	_, err := q.db.ExecContext(ctx, upsertComputeBarrier,
		arg.BarrierID,
		arg.AdmissionGeneration,
		arg.RequestedAt,
		arg.RequestedBy,
	)
	return err
}
