// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cachepolicy.sql

package ledgerdb

import (
	"context"
)

const countCacheBlocks = `-- name: CountCacheBlocks :one
SELECT COUNT(*) FROM cache_interception_blocks
 WHERE owner = $1 AND ((scope_type = 'org' AND repository = '') OR
                           (scope_type = 'repository' AND repository = $2))
`

type CountCacheBlocksParams struct {
	Owner      string
	Repository string
}

// Blocks covering one repository: its organisation's, or its own.
//
// ONE QUERY FOR BOTH SCOPES, because the answer is "is either blocked" and two
// reads could straddle a write that added the org block after the repository
// read said no.
func (q *Queries) CountCacheBlocks(ctx context.Context, arg CountCacheBlocksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCacheBlocks, arg.Owner, arg.Repository)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCacheBlock = `-- name: DeleteCacheBlock :exec
DELETE FROM cache_interception_blocks
 WHERE scope_type = $1 AND owner = $2 AND repository = $3
`

type DeleteCacheBlockParams struct {
	ScopeType  string
	Owner      string
	Repository string
}

// Re-enable interception for one explicit scope by removing its block.
func (q *Queries) DeleteCacheBlock(ctx context.Context, arg DeleteCacheBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteCacheBlock, arg.ScopeType, arg.Owner, arg.Repository)
	return err
}

const upsertCacheBlock = `-- name: UpsertCacheBlock :exec
INSERT INTO cache_interception_blocks (scope_type, owner, repository, disabled_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT(scope_type, owner, repository) DO UPDATE SET disabled_at = excluded.disabled_at
`

type UpsertCacheBlockParams struct {
	ScopeType  string
	Owner      string
	Repository string
	DisabledAt string
}

// Disable interception for one explicit scope, refreshing when it was decided.
func (q *Queries) UpsertCacheBlock(ctx context.Context, arg UpsertCacheBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertCacheBlock,
		arg.ScopeType,
		arg.Owner,
		arg.Repository,
		arg.DisabledAt,
	)
	return err
}
