// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cacheobservation.sql

package ledgerdb

import (
	"context"
)

const recordHistoryCacheObservation = `-- name: RecordHistoryCacheObservation :exec
UPDATE job_history
   SET image_cache      = CASE WHEN image_cache = '' THEN CAST($1 AS TEXT)
                               ELSE image_cache END,
       cache_generation = CASE WHEN image_cache = '' THEN CAST($2 AS TEXT)
                               ELSE cache_generation END,
       actions_cache    = CASE WHEN actions_cache = '' THEN CAST($3 AS TEXT)
                               ELSE actions_cache END
 WHERE lease_id = $4
`

type RecordHistoryCacheObservationParams struct {
	ImageCache      string
	CacheGeneration string
	ActionsCache    string
	LeaseID         string
}

// And onto its history row, the moment it is observed.
//
// WRITTEN NOW, NOT LEFT TO archive, for the reason a disruption is: a lease
// terminalizes whenever its teardown finally succeeds, which can be hours after
// the job ended or never. Unfenced, like RecordHistoryDisruption: the row is
// keyed by the lease and the observation is about the job, not about who holds
// the lease. A lease that never reached Assign has no history row and this
// updates nothing, which is correct: it ran no job.
func (q *Queries) RecordHistoryCacheObservation(ctx context.Context, arg RecordHistoryCacheObservationParams) error {
	_, err := q.db.ExecContext(ctx, recordHistoryCacheObservation,
		arg.ImageCache,
		arg.CacheGeneration,
		arg.ActionsCache,
		arg.LeaseID,
	)
	return err
}

const recordLeaseCacheObservation = `-- name: RecordLeaseCacheObservation :exec

UPDATE leases
   SET image_cache      = CASE WHEN image_cache = '' THEN CAST($1 AS TEXT)
                               ELSE image_cache END,
       cache_generation = CASE WHEN image_cache = '' THEN CAST($2 AS TEXT)
                               ELSE cache_generation END,
       actions_cache    = CASE WHEN actions_cache = '' THEN CAST($3 AS TEXT)
                               ELSE actions_cache END
 WHERE id = $4 AND epoch = $5
`

type RecordLeaseCacheObservationParams struct {
	ImageCache      string
	CacheGeneration string
	ActionsCache    string
	ID              string
	Epoch           int64
}

// Cache observations: what the cache did for one job, as the node saw it.
//
// AN OBSERVATION, NEVER A VERDICT, and from a CLOSED vocabulary the node writes
// from what it saw rather than what the tier intended -- alloc.ImageCache and
// alloc.ActionsCache hold the sets, and every new observation goes through their
// Valid() before it reaches a statement here. The empty string is the zero value
// and means nothing was observed.
//
// THE FIRST OBSERVATION IS KEPT, and the guard is in the statement rather than in
// a branch above it: each column is written only while it is empty, so a repeat
// from a node retrying a lost response changes nothing and a later, different
// observation cannot replace what the guest first saw. The generation moves with
// the image-cache token so a report never shows a generation with nothing to
// attribute it to. TestBothCacheObservationStatementsKeepTheFirst pins the guard
// on both statements.
// Write the observation onto the live lease, fenced on its epoch.
func (q *Queries) RecordLeaseCacheObservation(ctx context.Context, arg RecordLeaseCacheObservationParams) error {
	_, err := q.db.ExecContext(ctx, recordLeaseCacheObservation,
		arg.ImageCache,
		arg.CacheGeneration,
		arg.ActionsCache,
		arg.ID,
		arg.Epoch,
	)
	return err
}
