// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cachepolicy.sql

package ledgerdb

import (
	"context"
)

const countCacheBlocks = `-- name: CountCacheBlocks :one
SELECT COUNT(*) FROM cache_blocks
 WHERE (kind = $1 OR kind = '*') AND owner = $2 AND
       ((scope_type = 'org' AND repository = '') OR
        (scope_type = 'repository' AND repository = $3))
`

type CountCacheBlocksParams struct {
	Kind       string
	Owner      string
	Repository string
}

// Blocks covering one cache of one repository: its organisation's or its own,
// for that cache or for every cache.
//
// ONE QUERY FOR BOTH SCOPES AND BOTH KINDS, because the answer is "is any of
// them blocked" and separate reads could straddle a write that added one after
// another read said no.
func (q *Queries) CountCacheBlocks(ctx context.Context, arg CountCacheBlocksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCacheBlocks, arg.Kind, arg.Owner, arg.Repository)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCacheBlock = `-- name: DeleteCacheBlock :exec
DELETE FROM cache_blocks
 WHERE kind = $1 AND scope_type = $2 AND owner = $3
   AND repository = $4
`

type DeleteCacheBlockParams struct {
	Kind       string
	ScopeType  string
	Owner      string
	Repository string
}

// Re-enable one cache kind for one explicit scope by removing its block.
func (q *Queries) DeleteCacheBlock(ctx context.Context, arg DeleteCacheBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteCacheBlock,
		arg.Kind,
		arg.ScopeType,
		arg.Owner,
		arg.Repository,
	)
	return err
}

const listCacheBlocks = `-- name: ListCacheBlocks :many
SELECT kind, scope_type, owner, repository, disabled_at FROM cache_blocks
 ORDER BY owner, repository, kind
`

// Every block, for `billet cache status`.
func (q *Queries) ListCacheBlocks(ctx context.Context) ([]CacheBlock, error) {
	rows, err := q.db.QueryContext(ctx, listCacheBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheBlock
	for rows.Next() {
		var i CacheBlock
		if err := rows.Scan(
			&i.Kind,
			&i.ScopeType,
			&i.Owner,
			&i.Repository,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCacheBlock = `-- name: UpsertCacheBlock :exec
INSERT INTO cache_blocks (kind, scope_type, owner, repository, disabled_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(kind, scope_type, owner, repository) DO UPDATE SET disabled_at = excluded.disabled_at
`

type UpsertCacheBlockParams struct {
	Kind       string
	ScopeType  string
	Owner      string
	Repository string
	DisabledAt string
}

// Disable one cache kind for one explicit scope, refreshing when it was decided.
func (q *Queries) UpsertCacheBlock(ctx context.Context, arg UpsertCacheBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertCacheBlock,
		arg.Kind,
		arg.ScopeType,
		arg.Owner,
		arg.Repository,
		arg.DisabledAt,
	)
	return err
}
