// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completions.sql

package ledgerdb

import (
	"context"
)

const acknowledgePendingCompletion = `-- name: AcknowledgePendingCompletion :exec
UPDATE pending_completions SET acknowledged = 1
 WHERE tier = $1 AND request_id = $2 AND message_id = $3
`

type AcknowledgePendingCompletionParams struct {
	Tier      string
	RequestID int64
	MessageID int64
}

// Record that GitHub will not redeliver this message.
func (q *Queries) AcknowledgePendingCompletion(ctx context.Context, arg AcknowledgePendingCompletionParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgePendingCompletion, arg.Tier, arg.RequestID, arg.MessageID)
	return err
}

const deleteAcknowledgedCompletion = `-- name: DeleteAcknowledgedCompletion :exec
DELETE FROM pending_completions
 WHERE tier = $1 AND request_id = $2 AND message_id = $3
   AND acknowledged = 1
`

type DeleteAcknowledgedCompletionParams struct {
	Tier      string
	RequestID int64
	MessageID int64
}

// Remove an obligation that is both retired and acknowledged.
//
// Paired with RetirePendingCompletion in one transaction: the row may only go
// once GitHub will not redeliver it AND settlement is durable, and whichever of
// the two happens second is what removes it.
func (q *Queries) DeleteAcknowledgedCompletion(ctx context.Context, arg DeleteAcknowledgedCompletionParams) error {
	_, err := q.db.ExecContext(ctx, deleteAcknowledgedCompletion, arg.Tier, arg.RequestID, arg.MessageID)
	return err
}

const deleteRetiredCompletion = `-- name: DeleteRetiredCompletion :exec
DELETE FROM pending_completions
 WHERE tier = $1 AND request_id = $2 AND message_id = $3
   AND retired = 1
`

type DeleteRetiredCompletionParams struct {
	Tier      string
	RequestID int64
	MessageID int64
}

// The other half of the pair above, from the acknowledgement side.
func (q *Queries) DeleteRetiredCompletion(ctx context.Context, arg DeleteRetiredCompletionParams) error {
	_, err := q.db.ExecContext(ctx, deleteRetiredCompletion, arg.Tier, arg.RequestID, arg.MessageID)
	return err
}

const listPendingCompletions = `-- name: ListPendingCompletions :many
SELECT tier, request_id, run_id, result, lease_id, lease_epoch, lease_node,
       outcome, release_only, message_id, retired, acknowledged
  FROM pending_completions WHERE tier = $1 ORDER BY request_id
`

type ListPendingCompletionsRow struct {
	Tier         string
	RequestID    int64
	RunID        int64
	Result       string
	LeaseID      string
	LeaseEpoch   int64
	LeaseNode    string
	Outcome      string
	ReleaseOnly  int64
	MessageID    int64
	Retired      int64
	Acknowledged int64
}

// One tier's outstanding obligations.
func (q *Queries) ListPendingCompletions(ctx context.Context, tier string) ([]ListPendingCompletionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCompletions, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingCompletionsRow
	for rows.Next() {
		var i ListPendingCompletionsRow
		if err := rows.Scan(
			&i.Tier,
			&i.RequestID,
			&i.RunID,
			&i.Result,
			&i.LeaseID,
			&i.LeaseEpoch,
			&i.LeaseNode,
			&i.Outcome,
			&i.ReleaseOnly,
			&i.MessageID,
			&i.Retired,
			&i.Acknowledged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingCompletionMessage = `-- name: PendingCompletionMessage :one
SELECT message_id, retired FROM pending_completions
 WHERE tier = $1 AND request_id = $2
`

type PendingCompletionMessageParams struct {
	Tier      string
	RequestID int64
}

type PendingCompletionMessageRow struct {
	MessageID int64
	Retired   int64
}

// The message id and retirement of an obligation already on file.
//
// Read INSIDE the same transaction as the upsert below, because the disposition
// it decides (stale, retired, or actionable) describes the row the upsert is
// about to act on.
func (q *Queries) PendingCompletionMessage(ctx context.Context, arg PendingCompletionMessageParams) (PendingCompletionMessageRow, error) {
	row := q.db.QueryRowContext(ctx, pendingCompletionMessage, arg.Tier, arg.RequestID)
	var i PendingCompletionMessageRow
	err := row.Scan(&i.MessageID, &i.Retired)
	return i, err
}

const retirePendingCompletion = `-- name: RetirePendingCompletion :exec
UPDATE pending_completions SET retired = 1
 WHERE tier = $1 AND request_id = $2 AND message_id = $3
`

type RetirePendingCompletionParams struct {
	Tier      string
	RequestID int64
	MessageID int64
}

// Make replay a no-op BEFORE deletion is attempted.
//
// Scoped to the message id: a redelivery that arrives as a later message is a
// new obligation, not one this settlement covers.
func (q *Queries) RetirePendingCompletion(ctx context.Context, arg RetirePendingCompletionParams) error {
	_, err := q.db.ExecContext(ctx, retirePendingCompletion, arg.Tier, arg.RequestID, arg.MessageID)
	return err
}

const upsertPendingCompletion = `-- name: UpsertPendingCompletion :exec
INSERT INTO pending_completions
	(tier, request_id, run_id, result, lease_id, lease_epoch, lease_node, outcome,
	 release_only, message_id, retired, acknowledged)
	VALUES ($1, $2, $3, $4, $5, $6, $7,
	        $8, $9, $10, $11, $12)
	ON CONFLICT(tier, request_id) DO UPDATE SET
		run_id=excluded.run_id,
		result=excluded.result,
		lease_id=CASE WHEN excluded.message_id = pending_completions.message_id
			AND (pending_completions.retired = 1 OR
			     pending_completions.release_only > excluded.release_only)
			THEN pending_completions.lease_id ELSE excluded.lease_id END,
		lease_epoch=CASE WHEN excluded.message_id = pending_completions.message_id
			AND (pending_completions.retired = 1 OR
			     pending_completions.release_only > excluded.release_only)
			THEN pending_completions.lease_epoch ELSE excluded.lease_epoch END,
		lease_node=CASE WHEN excluded.message_id = pending_completions.message_id
			AND (pending_completions.retired = 1 OR
			     pending_completions.release_only > excluded.release_only)
			THEN pending_completions.lease_node ELSE excluded.lease_node END,
		outcome=CASE WHEN excluded.message_id = pending_completions.message_id
			AND (pending_completions.retired = 1 OR
			     pending_completions.release_only > excluded.release_only)
			THEN pending_completions.outcome ELSE excluded.outcome END,
		release_only=CASE
			WHEN excluded.message_id = pending_completions.message_id
			THEN CASE WHEN pending_completions.release_only > excluded.release_only
			          THEN pending_completions.release_only ELSE excluded.release_only END
			ELSE excluded.release_only END,
		message_id=excluded.message_id,
		retired=CASE
			WHEN excluded.message_id = pending_completions.message_id
			THEN CASE WHEN pending_completions.retired > excluded.retired
			          THEN pending_completions.retired ELSE excluded.retired END
			ELSE excluded.retired END,
		acknowledged=CASE
			WHEN excluded.message_id = pending_completions.message_id
			THEN CASE WHEN pending_completions.acknowledged > excluded.acknowledged
			          THEN pending_completions.acknowledged ELSE excluded.acknowledged END
			ELSE excluded.acknowledged END
	WHERE excluded.message_id >= pending_completions.message_id
`

type UpsertPendingCompletionParams struct {
	Tier         string
	RequestID    int64
	RunID        int64
	Result       string
	LeaseID      string
	LeaseEpoch   int64
	LeaseNode    string
	Outcome      string
	ReleaseOnly  int64
	MessageID    int64
	Retired      int64
	Acknowledged int64
}

// Durably record a result-delivery obligation.
//
// THE CASE ARMS ARE THE REDELIVERY RULE, and they are not decoration. A
// redelivery of the SAME message must not undo settlement that has already
// happened: once a row is retired, or once it has been narrowed to a release
// only, the lease fields and outcome on file win over what the delivery carries.
// A LATER message (a higher message_id) replaces them outright, and the trailing
// WHERE drops an EARLIER one entirely.
//
// release_only, retired and acknowledged are max()'d for the same message so a
// redelivery can only ever move them forward.
func (q *Queries) UpsertPendingCompletion(ctx context.Context, arg UpsertPendingCompletionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingCompletion,
		arg.Tier,
		arg.RequestID,
		arg.RunID,
		arg.Result,
		arg.LeaseID,
		arg.LeaseEpoch,
		arg.LeaseNode,
		arg.Outcome,
		arg.ReleaseOnly,
		arg.MessageID,
		arg.Retired,
		arg.Acknowledged,
	)
	return err
}
