// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentialsweeps.sql

package ledgerdb

import (
	"context"
)

const listCredentialSweeps = `-- name: ListCredentialSweeps :many
SELECT region, path, swept_at, removed, removed_total, kept, unaccounted, foreign_names,
       error
  FROM credential_sweeps
 ORDER BY region, path
`

// Every path the sweep has ever recorded a pass over.
func (q *Queries) ListCredentialSweeps(ctx context.Context) ([]CredentialSweep, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialSweeps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialSweep
	for rows.Next() {
		var i CredentialSweep
		if err := rows.Scan(
			&i.Region,
			&i.Path,
			&i.SweptAt,
			&i.Removed,
			&i.RemovedTotal,
			&i.Kept,
			&i.Unaccounted,
			&i.ForeignNames,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCredentialSweep = `-- name: RecordCredentialSweep :exec

INSERT INTO credential_sweeps
   (region, path, swept_at, removed, removed_total, kept, unaccounted, foreign_names, error)
VALUES ($1, $2, $3, $4, $4, $5, $6, $7,
        $8)
ON CONFLICT (region, path) DO UPDATE SET
   swept_at      = excluded.swept_at,
   removed       = excluded.removed,
   removed_total = credential_sweeps.removed_total + excluded.removed,
   kept          = excluded.kept,
   unaccounted   = excluded.unaccounted,
   foreign_names = excluded.foreign_names,
   error         = excluded.error
`

type RecordCredentialSweepParams struct {
	Region       string
	Path         string
	SweptAt      string
	Removed      int64
	Kept         int64
	Unaccounted  int64
	ForeignNames int64
	Error        string
}

// What the control plane's sweep of staged CodeBuild registrations did, one row
// per region and Parameter Store path.
//
// A RECORD, NOT A DECISION. Nothing reads this to decide whether a parameter may
// be deleted -- that is answered per lease by ReadLeaseSettlement. It exists so
// `billet status`, which runs in another process, can say what the sweep removed,
// what it is still waiting on, and whether its last pass failed.
// Record one pass over one path.
//
// removed IS THE LAST PASS AND removed_total ACCUMULATES, so a status line can
// show both "3 removed in total" and whether the most recent pass did anything.
// Every other column describes the last pass only: kept and unaccounted are
// counts of what is there now, and error is empty on a pass that completed.
func (q *Queries) RecordCredentialSweep(ctx context.Context, arg RecordCredentialSweepParams) error {
	_, err := q.db.ExecContext(ctx, recordCredentialSweep,
		arg.Region,
		arg.Path,
		arg.SweptAt,
		arg.Removed,
		arg.Kept,
		arg.Unaccounted,
		arg.ForeignNames,
		arg.Error,
	)
	return err
}
