// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_binding.sql

package ledgerdb

import (
	"context"
)

const bindDeployment = `-- name: BindDeployment :exec
INSERT INTO deployment_binding (id, deployment_id, bound_at)
VALUES (1, $1, $2)
`

type BindDeploymentParams struct {
	DeploymentID string
	BoundAt      string
}

// Record the deployment these rows belong to, for the first and only time.
//
// A PLAIN INSERT RATHER THAN AN UPSERT, and the absence of a DO UPDATE clause is
// the guarantee. The caller has already read the row inside this same write
// transaction and found none, and every writer serializes (SQLite at BEGIN
// IMMEDIATE, PostgreSQL on the advisory lock beginWrite takes), so nothing can
// bind between the read and this insert. If one somehow did, the primary key
// refuses rather than quietly relabelling a deployment.
func (q *Queries) BindDeployment(ctx context.Context, arg BindDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, bindDeployment, arg.DeploymentID, arg.BoundAt)
	return err
}

const readDeploymentBinding = `-- name: ReadDeploymentBinding :one

SELECT deployment_id, bound_at FROM deployment_binding WHERE id = 1
`

type ReadDeploymentBindingRow struct {
	DeploymentID string
	BoundAt      string
}

// Which deployment these rows belong to.
//
// THE PAIRING USED TO NEED NOTHING TO ENFORCE IT. While the ledger was a file in
// the identity directory, one directory meant one identity and one ledger, and
// there was no way to point a second identity at the same rows. A PostgreSQL
// ledger is reachable from anywhere and recorded nothing about whose it was, so
// two hosts could share one capacity record under two identities: each control
// plane admitting nodes against its own authority, both charging capacity into
// one ledger, and nothing anywhere naming the disagreement.
//
// WRITTEN ONCE AND READ TO REFUSE, which is the same discipline as the
// controller claim one file over. There is no statement here that replaces a
// binding, deliberately: the operation that would need one is relabelling a
// deployment, and billet refuses that everywhere else it can arise.
//
// (The prose in this file is ASCII, like every query file: sqlc rewrites named
// parameters on BYTE offsets, so one multi-byte character shifts every statement
// after it and the parse error names neither the file nor the character.)
// Which deployment this ledger says it belongs to.
//
// sql.ErrNoRows IS AN ORDINARY STATE AND NOT A REFUSAL. A ledger migrated before
// this table existed carries no binding, and neither does one whose controller
// has not claimed yet, so an absent row means "not yet bound" and never "bound
// to nobody". Collapsing the two would refuse every deployment upgrading through
// the release that adds this.
func (q *Queries) ReadDeploymentBinding(ctx context.Context) (ReadDeploymentBindingRow, error) {
	row := q.db.QueryRowContext(ctx, readDeploymentBinding)
	var i ReadDeploymentBindingRow
	err := row.Scan(&i.DeploymentID, &i.BoundAt)
	return i, err
}
