// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disruption.sql

package ledgerdb

import (
	"context"
)

const disruptableLease = `-- name: DisruptableLease :many

SELECT id FROM leases
 WHERE id = $1
   AND disruption = ''
   AND phase IN ('launching','online','busy','custody','teardown','quarantine')
   AND NOT EXISTS (SELECT 1 FROM job_history h
                    WHERE h.lease_id = leases.id AND h.result != '')
   AND NOT EXISTS (SELECT 1 FROM pending_completions p
                    WHERE p.lease_id = leases.id AND p.result != '')
`

// Disruption: what billet's OWN infrastructure did to a lease while the job on
// it may still have been running.
//
// AN OBSERVATION, NEVER A VERDICT. Nothing here says a job failed because of a
// disruption; what makes one interesting is reading it beside GitHub's own result
// for the same job, which is why the two are recorded separately and neither is
// stored as an answer.
//
// THE GUARD IS WRITTEN TWICE, and it has to be: SQL has no way to compose a
// predicate the way the Go constant it replaced did.
// TestBothDisruptionStatementsPinTheirWholeStatement pins each statement's
// COMPLETE text -- the locator as well as the guard -- because a guard that
// drifts on one path is the path that attributes somebody's ordinary test failure
// to billet, and a locator that widens is every lease in the deployment.
//
// WHAT THE GUARD SAYS, clause by clause:
//
//	an empty disruption        The FIRST observation is the one kept. A later
//	                           disruption is a consequence of the earlier one at
//	                           least as often as it is a separate event, and only
//	                           the earliest can still have been causal.
//
//	phase IN (...)             Phases in which a job COULD still have been
//	                           running. Could, not was: `launching` admits a
//	                           lease whose guest never started. `capacity` and
//	                           `assigned` are absent because nothing was started
//	                           under them, and attributing a build failure to one
//	                           would attribute it to a machine that never ran the
//	                           build. `quarantine` IS here, because quarantine
//	                           exists precisely while compute is unconfirmed.
//
//	NOT EXISTS job_history     A disruption landing after GitHub has reported the
//	NOT EXISTS pending_...     job cannot have caused it. BOTH records are asked
//	                           because pending_completions is written FIRST, when
//	                           the listener makes the delivery durable, and
//	                           job_history.result follows in a SECOND
//	                           transaction: reading only the second leaves a
//	                           committed interval in which a concurrent NodeGone
//	                           or reclaim sees no result and attributes a job that
//	                           had already finished. It also survives a crash
//	                           between the two writes, since the pending row does
//	                           and the column does not.
//
// Whether one lease may still have a disruption recorded against it.
func (q *Queries) DisruptableLease(ctx context.Context, id string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, disruptableLease, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disruptableLeasesOnNode = `-- name: DisruptableLeasesOnNode :many
SELECT id FROM leases
 WHERE COALESCE(node, target_node) = CAST($1 AS TEXT)
   AND disruption = ''
   AND phase IN ('launching','online','busy','custody','teardown','quarantine')
   AND NOT EXISTS (SELECT 1 FROM job_history h
                    WHERE h.lease_id = leases.id AND h.result != '')
   AND NOT EXISTS (SELECT 1 FROM pending_completions p
                    WHERE p.lease_id = leases.id AND p.result != '')
`

// Which of one host's leases may still have a disruption recorded against them.
//
// COALESCE(node, target_node), the way the rest of this package attributes a
// lease: a reservation aimed at a machine that is being given up on is as
// disrupted as one bound to it.
func (q *Queries) DisruptableLeasesOnNode(ctx context.Context, node string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, disruptableLeasesOnNode, node)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordHistoryDisruption = `-- name: RecordHistoryDisruption :exec
UPDATE job_history SET disruption = $1, disrupted_at = $2
 WHERE lease_id = $3
`

type RecordHistoryDisruptionParams struct {
	Disruption  string
	DisruptedAt string
	LeaseID     string
}

// And onto its history row.
//
// WRITTEN NOW, NOT LEFT TO archive. A lease terminalizes whenever its teardown
// finally succeeds, which can be hours after the job ended or never -- and a job
// whose teardown is wedged on a host that vanished is exactly the one an operator
// is looking for. A lease that never reached Assign has no history row and this
// updates nothing, which is correct: it ran no job.
func (q *Queries) RecordHistoryDisruption(ctx context.Context, arg RecordHistoryDisruptionParams) error {
	_, err := q.db.ExecContext(ctx, recordHistoryDisruption, arg.Disruption, arg.DisruptedAt, arg.LeaseID)
	return err
}

const recordLeaseDisruption = `-- name: RecordLeaseDisruption :exec
UPDATE leases SET disruption = $1, disrupted_at = $2 WHERE id = $3
`

type RecordLeaseDisruptionParams struct {
	Disruption  string
	DisruptedAt string
	ID          string
}

// Write the observation onto the live lease.
func (q *Queries) RecordLeaseDisruption(ctx context.Context, arg RecordLeaseDisruptionParams) error {
	_, err := q.db.ExecContext(ctx, recordLeaseDisruption, arg.Disruption, arg.DisruptedAt, arg.ID)
	return err
}
