// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package ledgerdb

import (
	"context"
)

const decideEnrollment = `-- name: DecideEnrollment :exec
UPDATE node_enrollments
   SET state = $1, cert_pem = $2, decided_at = $3
 WHERE name = $4
`

type DecideEnrollmentParams struct {
	State     string
	CertPem   string
	DecidedAt string
	Name      string
}

// Record an operator's approval or denial.
func (q *Queries) DecideEnrollment(ctx context.Context, arg DecideEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, decideEnrollment,
		arg.State,
		arg.CertPem,
		arg.DecidedAt,
		arg.Name,
	)
	return err
}

const insertEnrollment = `-- name: InsertEnrollment :exec
INSERT INTO node_enrollments (name, fingerprint, csr_pem, state, requested_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEnrollmentParams struct {
	Name        string
	Fingerprint string
	CsrPem      string
	State       string
	RequestedAt string
}

// Record a request for a name nothing holds.
func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, insertEnrollment,
		arg.Name,
		arg.Fingerprint,
		arg.CsrPem,
		arg.State,
		arg.RequestedAt,
	)
	return err
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT name, fingerprint, csr_pem, cert_pem, state, requested_at, decided_at, source
  FROM node_enrollments ORDER BY requested_at
`

// Everything that has asked to join.
func (q *Queries) ListEnrollments(ctx context.Context) ([]NodeEnrollment, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeEnrollment
	for rows.Next() {
		var i NodeEnrollment
		if err := rows.Scan(
			&i.Name,
			&i.Fingerprint,
			&i.CsrPem,
			&i.CertPem,
			&i.State,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsInState = `-- name: ListEnrollmentsInState :many
SELECT name, fingerprint, csr_pem, cert_pem, state, requested_at, decided_at, source
  FROM node_enrollments WHERE state = $1 ORDER BY requested_at
`

// Everything in one state.
//
// A SECOND STATEMENT RATHER THAN one query whose state filter is skipped when
// the parameter is empty, so each has one plan and the branch is visible in the
// Go that chooses it. An unfiltered
// read of this table is the operator's whole pending list; a filtered one is a
// lookup, and folding them into one query hides which is running.
func (q *Queries) ListEnrollmentsInState(ctx context.Context, state string) ([]NodeEnrollment, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentsInState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeEnrollment
	for rows.Next() {
		var i NodeEnrollment
		if err := rows.Scan(
			&i.Name,
			&i.Fingerprint,
			&i.CsrPem,
			&i.CertPem,
			&i.State,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEnrollment = `-- name: ReadEnrollment :one

SELECT name, fingerprint, csr_pem, cert_pem, state, requested_at, decided_at, source
  FROM node_enrollments WHERE name = $1
`

// Node enrollment: what has asked to join, and what an operator decided.
//
// THE PROJECTIONS ARE IN TABLE DECLARATION ORDER on purpose. sqlc returns the
// model struct for a query that selects exactly the table's columns in exactly
// its order, and a Row type of its own for anything else -- so writing the three
// full reads the same way gives all three one shared type and the adapter one
// mapping function instead of three that must be kept identical.
// One request, by the name it claims.
func (q *Queries) ReadEnrollment(ctx context.Context, name string) (NodeEnrollment, error) {
	row := q.db.QueryRowContext(ctx, readEnrollment, name)
	var i NodeEnrollment
	err := row.Scan(
		&i.Name,
		&i.Fingerprint,
		&i.CsrPem,
		&i.CertPem,
		&i.State,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.Source,
	)
	return i, err
}

const readEnrollmentFingerprint = `-- name: ReadEnrollmentFingerprint :one
SELECT fingerprint FROM node_enrollments WHERE name = $1
`

// Just the key a name is currently admitted as.
//
// SEPARATE FROM ReadEnrollment because the caller is about to overwrite the row
// and needs only what it is displacing; reading the CSR and the certificate to
// compare one column is the whole credential in memory for nothing.
func (q *Queries) ReadEnrollmentFingerprint(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, readEnrollmentFingerprint, name)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const replaceDeniedEnrollment = `-- name: ReplaceDeniedEnrollment :exec
UPDATE node_enrollments
   SET fingerprint = $1, csr_pem = $2, cert_pem = '', state = $3,
       source = 'enrolled', requested_at = $4, decided_at = ''
 WHERE name = $5
`

type ReplaceDeniedEnrollmentParams struct {
	Fingerprint string
	CsrPem      string
	State       string
	RequestedAt string
	Name        string
}

// Let a different key take a name a denial is holding.
//
// ONLY FOR A DENIED ROW, which the caller checks: pending and approved still
// hold the name, because an operator who compared a fingerprint yesterday must
// not be approving a different machine today under a name they already trust. A
// denial holds nothing, because the enrolling process keeps its private key in
// memory while it waits for a human -- so a reboot loses the key and, without
// this, the machine that comes back is refused forever.
func (q *Queries) ReplaceDeniedEnrollment(ctx context.Context, arg ReplaceDeniedEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, replaceDeniedEnrollment,
		arg.Fingerprint,
		arg.CsrPem,
		arg.State,
		arg.RequestedAt,
		arg.Name,
	)
	return err
}

const upsertIssuedEnrollment = `-- name: UpsertIssuedEnrollment :exec
INSERT INTO node_enrollments
     (name, fingerprint, csr_pem, cert_pem, state, source, requested_at, decided_at)
VALUES ($1, $2, '', $3, $4, 'issued', $5, $6)
ON CONFLICT (name) DO UPDATE SET
  fingerprint = excluded.fingerprint,
  cert_pem    = excluded.cert_pem,
  state       = excluded.state,
  source      = excluded.source,
  decided_at  = excluded.decided_at
`

type UpsertIssuedEnrollmentParams struct {
	Name        string
	Fingerprint string
	CertPem     string
	State       string
	RequestedAt string
	DecidedAt   string
}

// Record a certificate handed out directly by `billet ca issue`.
//
// IT OVERWRITES, unlike the wire, and that is deliberate: issuing is a
// deliberate operator act and refusing would leave a name unusable after a
// machine was rebuilt. csr_pem is left alone by the update because this path
// never had one; requested_at likewise keeps the first admission's timestamp.
func (q *Queries) UpsertIssuedEnrollment(ctx context.Context, arg UpsertIssuedEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertIssuedEnrollment,
		arg.Name,
		arg.Fingerprint,
		arg.CertPem,
		arg.State,
		arg.RequestedAt,
		arg.DecidedAt,
	)
	return err
}
