// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forcedestroy.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const completeForceDestroy = `-- name: CompleteForceDestroy :exec
UPDATE force_destroy SET state = $1, completed_at = $2
 WHERE generation = $3 AND state = $4
`

type CompleteForceDestroyParams struct {
	State       string
	CompletedAt string
	Generation  int64
	WasState    string
}

// Close out a request once nothing is pending.
//
// Guarded on the state it is leaving, so a second listener arriving at the same
// conclusion cannot rewrite completed_at.
func (q *Queries) CompleteForceDestroy(ctx context.Context, arg CompleteForceDestroyParams) error {
	_, err := q.db.ExecContext(ctx, completeForceDestroy,
		arg.State,
		arg.CompletedAt,
		arg.Generation,
		arg.WasState,
	)
	return err
}

const countForceDestroyInState = `-- name: CountForceDestroyInState :one
SELECT COUNT(*) FROM force_destroy WHERE state = $1
`

// How many force-destroy requests sit in one state.
//
// Asked inside the write transaction that would create the next one: two
// concurrent forces would each enumerate a target set the other was midway
// through destroying.
func (q *Queries) CountForceDestroyInState(ctx context.Context, state string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countForceDestroyInState, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countForceTargetsInState = `-- name: CountForceTargetsInState :one
SELECT COUNT(*) FROM force_destroy_target
 WHERE generation = $1 AND state = $2
`

type CountForceTargetsInStateParams struct {
	Generation int64
	State      string
}

// How many of one request's targets are still in a given state.
//
// Read in the SAME transaction as the settlement above, because completion is
// decided from it: two listeners settling their last target concurrently would
// otherwise both see work outstanding and leave a request nothing will finish.
func (q *Queries) CountForceTargetsInState(ctx context.Context, arg CountForceTargetsInStateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countForceTargetsInState, arg.Generation, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const forceDestroyInState = `-- name: ForceDestroyInState :one
SELECT generation, admission_generation, state, reason, actor, requested_at,
       completed_at
  FROM force_destroy WHERE state = $1
`

// The one request sitting in a given state, if any.
func (q *Queries) ForceDestroyInState(ctx context.Context, state string) (ForceDestroy, error) {
	row := q.db.QueryRowContext(ctx, forceDestroyInState, state)
	var i ForceDestroy
	err := row.Scan(
		&i.Generation,
		&i.AdmissionGeneration,
		&i.State,
		&i.Reason,
		&i.Actor,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const forceTargets = `-- name: ForceTargets :many
SELECT lease_id, tier, node, run_id, scheduler_request, phase, state, detail
  FROM force_destroy_target WHERE generation = $1
 ORDER BY tier, lease_id
`

type ForceTargetsRow struct {
	LeaseID          string
	Tier             string
	Node             string
	RunID            string
	SchedulerRequest int64
	Phase            string
	State            string
	Detail           string
}

// Every lease one request covers, whatever became of it.
func (q *Queries) ForceTargets(ctx context.Context, generation int64) ([]ForceTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, forceTargets, generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForceTargetsRow
	for rows.Next() {
		var i ForceTargetsRow
		if err := rows.Scan(
			&i.LeaseID,
			&i.Tier,
			&i.Node,
			&i.RunID,
			&i.SchedulerRequest,
			&i.Phase,
			&i.State,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const highestForceDestroyGeneration = `-- name: HighestForceDestroyGeneration :one
SELECT CAST(COALESCE(MAX(generation), 0) AS BIGINT) AS generation FROM force_destroy
`

// The highest generation on file, or 0 when there has never been a force.
//
// CAST because sqlc types a bare MAX (and a bare COALESCE) as interface{};
// measured. COALESCE first, because CAST(NULL AS BIGINT) is still NULL. The 0
// reproduces exactly what a NULL scanned into sql.NullInt64 used to yield, so
// the caller's +1 still makes the first request generation 1.
func (q *Queries) HighestForceDestroyGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, highestForceDestroyGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const insertForceDestroy = `-- name: InsertForceDestroy :exec
INSERT INTO force_destroy
    (generation, admission_generation, state, reason, actor, requested_at, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, '')
`

type InsertForceDestroyParams struct {
	Generation          int64
	AdmissionGeneration int64
	State               string
	Reason              string
	Actor               string
	RequestedAt         string
}

// Record one operator decision to destroy running compute.
//
// completed_at is empty rather than null: this row is read back into a struct
// whose fields are strings, and a nullable column would make "not finished" and
// "billet could not read it" the same value.
func (q *Queries) InsertForceDestroy(ctx context.Context, arg InsertForceDestroyParams) error {
	_, err := q.db.ExecContext(ctx, insertForceDestroy,
		arg.Generation,
		arg.AdmissionGeneration,
		arg.State,
		arg.Reason,
		arg.Actor,
		arg.RequestedAt,
	)
	return err
}

const insertForceDestroyTarget = `-- name: InsertForceDestroyTarget :exec
INSERT INTO force_destroy_target
    (generation, lease_id, tier, node, run_id, scheduler_request, phase, state, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, '')
`

type InsertForceDestroyTargetParams struct {
	Generation       int64
	LeaseID          string
	Tier             string
	Node             string
	RunID            string
	SchedulerRequest int64
	Phase            string
	State            string
}

// Record one lease the operator authorised destroying.
//
// EVERY FIELD IS STORED so the diagnostic survives the command: a listener
// acting on this a poll later, or a second control plane after a restart, has no
// other record of what the person actually approved.
func (q *Queries) InsertForceDestroyTarget(ctx context.Context, arg InsertForceDestroyTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertForceDestroyTarget,
		arg.Generation,
		arg.LeaseID,
		arg.Tier,
		arg.Node,
		arg.RunID,
		arg.SchedulerRequest,
		arg.Phase,
		arg.State,
	)
	return err
}

const latestForceDestroy = `-- name: LatestForceDestroy :one
SELECT generation, admission_generation, state, reason, actor, requested_at,
       completed_at
  FROM force_destroy ORDER BY generation DESC LIMIT 1
`

// The most recent request, open or finished, for the report an operator reads
// after the fact.
func (q *Queries) LatestForceDestroy(ctx context.Context) (ForceDestroy, error) {
	row := q.db.QueryRowContext(ctx, latestForceDestroy)
	var i ForceDestroy
	err := row.Scan(
		&i.Generation,
		&i.AdmissionGeneration,
		&i.State,
		&i.Reason,
		&i.Actor,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const pendingForceTargets = `-- name: PendingForceTargets :many
SELECT lease_id, tier, node, run_id, scheduler_request, phase, state, detail
  FROM force_destroy_target
 WHERE generation = $1 AND tier = $2 AND state = $3
 ORDER BY lease_id
`

type PendingForceTargetsParams struct {
	Generation int64
	Tier       string
	State      string
}

type PendingForceTargetsRow struct {
	LeaseID          string
	Tier             string
	Node             string
	RunID            string
	SchedulerRequest int64
	Phase            string
	State            string
	Detail           string
}

// The leases one tier still owes a destroy for.
//
// SCOPED TO A TIER because a listener may only act on its own escrow: destroying
// another tier's compute would be tearing down a lease it never held and cannot
// release.
func (q *Queries) PendingForceTargets(ctx context.Context, arg PendingForceTargetsParams) ([]PendingForceTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingForceTargets, arg.Generation, arg.Tier, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingForceTargetsRow
	for rows.Next() {
		var i PendingForceTargetsRow
		if err := rows.Scan(
			&i.LeaseID,
			&i.Tier,
			&i.Node,
			&i.RunID,
			&i.SchedulerRequest,
			&i.Phase,
			&i.State,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleForceTarget = `-- name: SettleForceTarget :execresult
UPDATE force_destroy_target SET state = $1, detail = $2
 WHERE generation = $3 AND lease_id = $4 AND state = $5
`

type SettleForceTargetParams struct {
	State      string
	Detail     string
	Generation int64
	LeaseID    string
	WasState   string
}

// Record what became of one lease, and only while it is still pending.
//
// :execresult because ALREADY SETTLED IS NOT AN ERROR. A listener that restarts
// re-observes the request and may act on a target another incarnation already
// finished, so the caller reads RowsAffected to tell "I settled it" from
// "somebody already had".
func (q *Queries) SettleForceTarget(ctx context.Context, arg SettleForceTargetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, settleForceTarget,
		arg.State,
		arg.Detail,
		arg.Generation,
		arg.LeaseID,
		arg.WasState,
	)
}
