// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobguest.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const readJobGuestReport = `-- name: ReadJobGuestReport :one
SELECT lease_id, node, recorded_at, agent_version, agent_schema, codec, data,
       accepted, refused, dropped_bytes, hello, final_seen, node_restarted,
       first_received_at, last_received_at
  FROM job_guest_reports WHERE lease_id = $1
`

// One lease's guest report. sql.ErrNoRows means none was kept, which a reader
// says rather than printing an empty report.
func (q *Queries) ReadJobGuestReport(ctx context.Context, leaseID string) (JobGuestReport, error) {
	row := q.db.QueryRowContext(ctx, readJobGuestReport, leaseID)
	var i JobGuestReport
	err := row.Scan(
		&i.LeaseID,
		&i.Node,
		&i.RecordedAt,
		&i.AgentVersion,
		&i.AgentSchema,
		&i.Codec,
		&i.Data,
		&i.Accepted,
		&i.Refused,
		&i.DroppedBytes,
		&i.Hello,
		&i.FinalSeen,
		&i.NodeRestarted,
		&i.FirstReceivedAt,
		&i.LastReceivedAt,
	)
	return i, err
}

const recordJobGuestReport = `-- name: RecordJobGuestReport :execrows

INSERT INTO job_guest_reports
     (lease_id, node, recorded_at, agent_version, agent_schema, codec, data,
      accepted, refused, dropped_bytes, hello, final_seen, node_restarted,
      first_received_at, last_received_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, $12,
        $13, $14, $15)
ON CONFLICT (lease_id) DO NOTHING
`

type RecordJobGuestReportParams struct {
	LeaseID         string
	Node            string
	RecordedAt      string
	AgentVersion    string
	AgentSchema     int64
	Codec           int64
	Data            string
	Accepted        int64
	Refused         int64
	DroppedBytes    int64
	Hello           int64
	FinalSeen       int64
	NodeRestarted   int64
	FirstReceivedAt sql.NullString
	LastReceivedAt  sql.NullString
}

// Guest reports: what the agent inside a job's guest told the node, the
// guest's own unverified view (migration 60).
// Keep the first guest report for a lease.
//
// DO NOTHING ON CONFLICT, for RecordJobUsage's reason: a retry after a lost
// answer carries the same report, and a second is not allowed to replace the
// first. The epoch fence is the caller's, in the same transaction. The arrival
// times are NULL where no batch arrived.
func (q *Queries) RecordJobGuestReport(ctx context.Context, arg RecordJobGuestReportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordJobGuestReport,
		arg.LeaseID,
		arg.Node,
		arg.RecordedAt,
		arg.AgentVersion,
		arg.AgentSchema,
		arg.Codec,
		arg.Data,
		arg.Accepted,
		arg.Refused,
		arg.DroppedBytes,
		arg.Hello,
		arg.FinalSeen,
		arg.NodeRestarted,
		arg.FirstReceivedAt,
		arg.LastReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
