// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobidentity.sql

package ledgerdb

import (
	"context"
)

const insertJobIdentity = `-- name: InsertJobIdentity :exec

INSERT INTO job_identities (job_id, internal_id)
SELECT $1, COALESCE(MIN(internal_id), 0) - 1
FROM (SELECT internal_id FROM job_identities
      UNION ALL SELECT internal_id FROM pool_slot_identities)
WHERE true
ON CONFLICT(job_id) DO NOTHING
`

// Durable negative scheduler identities.
//
// ZERO IS NEVER A SCHEDULER IDENTITY. GitHub's direct JobAssigned path carries
// runnerRequestId 0, and its desired-count signal names a quantity rather than a
// job at all -- so billet mints its own id for both. Negative, so it can never
// collide with one of GitHub's own positive request ids, and allocated under the
// immediate writer transaction so a redelivery or a restart recovers the SAME
// number rather than minting a second identity for one job.
//
// HASHING THE JOB ID WAS THE ALTERNATIVE AND IT IS WORSE: it would make hash
// collisions a correctness property of the scheduler.
//
// THE MINIMUM IS TAKEN ACROSS BOTH TABLES, which is what keeps the two families
// of identity in one number space. Reading only its own table would let a job and
// a pool slot be handed the same id.
// Mint the identity for one direct-assignment job, if it has none.
//
// DO NOTHING rather than DO UPDATE: a job that already has an identity must keep
// it, because that number is what an in-flight message is keyed on.
func (q *Queries) InsertJobIdentity(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, insertJobIdentity, jobID)
	return err
}

const insertPoolSlotIdentity = `-- name: InsertPoolSlotIdentity :exec
INSERT INTO pool_slot_identities (lease_id, internal_id)
SELECT $1, COALESCE(MIN(internal_id), 0) - 1
FROM (SELECT internal_id FROM job_identities
      UNION ALL SELECT internal_id FROM pool_slot_identities)
WHERE true
ON CONFLICT(lease_id) DO NOTHING
`

// Mint the identity for one escrowed lease becoming a physical pool member.
//
// KEYED ON THE LEASE, because GitHub's desired-count signal names no job: the
// lease is the only stable identity available on redelivery and after a restart.
func (q *Queries) InsertPoolSlotIdentity(ctx context.Context, leaseID string) error {
	_, err := q.db.ExecContext(ctx, insertPoolSlotIdentity, leaseID)
	return err
}

const readJobIdentity = `-- name: ReadJobIdentity :one
SELECT internal_id FROM job_identities WHERE job_id = $1
`

// The identity one job holds.
//
// READ AFTER THE INSERT RATHER THAN RETURNED BY IT, because the insert may have
// done nothing: the identity that matters is whatever the row holds now, which
// is not necessarily the number this call would have minted.
func (q *Queries) ReadJobIdentity(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, readJobIdentity, jobID)
	var internal_id int64
	err := row.Scan(&internal_id)
	return internal_id, err
}

const readPoolSlotIdentity = `-- name: ReadPoolSlotIdentity :one
SELECT internal_id FROM pool_slot_identities WHERE lease_id = $1
`

// The identity one lease's pool slot holds.
func (q *Queries) ReadPoolSlotIdentity(ctx context.Context, leaseID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, readPoolSlotIdentity, leaseID)
	var internal_id int64
	err := row.Scan(&internal_id)
	return internal_id, err
}
