// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobusage.sql

package ledgerdb

import (
	"context"
)

const readJobSeries = `-- name: ReadJobSeries :one
SELECT codec, series FROM job_series WHERE lease_id = $1
`

type ReadJobSeriesRow struct {
	Codec  int64
	Series string
}

// One lease's series blob and the codec that wrote it.
func (q *Queries) ReadJobSeries(ctx context.Context, leaseID string) (ReadJobSeriesRow, error) {
	row := q.db.QueryRowContext(ctx, readJobSeries, leaseID)
	var i ReadJobSeriesRow
	err := row.Scan(&i.Codec, &i.Series)
	return i, err
}

const readJobUsage = `-- name: ReadJobUsage :one
SELECT lease_id, node, recorded_at, source, unmeasured, samples, interval_ms,
       window_ms, cpu_user_us, cpu_system_us, guest_cpu_us, vmm_cpu_us,
       memory_peak_bytes, oom_kills, disk_read_bytes, disk_write_bytes,
       net_rx_bytes, net_tx_bytes, net_rx_packets, net_tx_packets,
       cpu_some_us, cpu_full_us, memory_some_us, memory_full_us, io_some_us,
       io_full_us, energy_active_uj, energy_idle_uj, energy_source
  FROM job_usage WHERE lease_id = $1
`

// One lease's usage summary. sql.ErrNoRows means nothing was measured, which a
// reader says rather than printing zeros.
func (q *Queries) ReadJobUsage(ctx context.Context, leaseID string) (JobUsage, error) {
	row := q.db.QueryRowContext(ctx, readJobUsage, leaseID)
	var i JobUsage
	err := row.Scan(
		&i.LeaseID,
		&i.Node,
		&i.RecordedAt,
		&i.Source,
		&i.Unmeasured,
		&i.Samples,
		&i.IntervalMs,
		&i.WindowMs,
		&i.CpuUserUs,
		&i.CpuSystemUs,
		&i.GuestCpuUs,
		&i.VmmCpuUs,
		&i.MemoryPeakBytes,
		&i.OomKills,
		&i.DiskReadBytes,
		&i.DiskWriteBytes,
		&i.NetRxBytes,
		&i.NetTxBytes,
		&i.NetRxPackets,
		&i.NetTxPackets,
		&i.CpuSomeUs,
		&i.CpuFullUs,
		&i.MemorySomeUs,
		&i.MemoryFullUs,
		&i.IoSomeUs,
		&i.IoFullUs,
		&i.EnergyActiveUj,
		&i.EnergyIdleUj,
		&i.EnergySource,
	)
	return i, err
}

const recordJobSeries = `-- name: RecordJobSeries :exec
INSERT INTO job_series (lease_id, codec, series)
VALUES ($1, $2, $3)
ON CONFLICT (lease_id) DO NOTHING
`

type RecordJobSeriesParams struct {
	LeaseID string
	Codec   int64
	Series  string
}

// Keep the first series for a lease, for the reason RecordJobUsage keeps the
// first summary.
func (q *Queries) RecordJobSeries(ctx context.Context, arg RecordJobSeriesParams) error {
	_, err := q.db.ExecContext(ctx, recordJobSeries, arg.LeaseID, arg.Codec, arg.Series)
	return err
}

const recordJobUsage = `-- name: RecordJobUsage :exec

INSERT INTO job_usage
     (lease_id, node, recorded_at, source, unmeasured, samples, interval_ms,
      window_ms, cpu_user_us, cpu_system_us, guest_cpu_us, vmm_cpu_us,
      memory_peak_bytes, oom_kills, disk_read_bytes, disk_write_bytes,
      net_rx_bytes, net_tx_bytes, net_rx_packets, net_tx_packets,
      cpu_some_us, cpu_full_us, memory_some_us, memory_full_us, io_some_us,
      io_full_us, energy_active_uj, energy_idle_uj, energy_source)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12, $13, $14, $15,
        $16, $17, $18, $19,
        $20, $21, $22, $23,
        $24, $25, $26, $27,
        $28, $29)
ON CONFLICT (lease_id) DO NOTHING
`

type RecordJobUsageParams struct {
	LeaseID         string
	Node            string
	RecordedAt      string
	Source          string
	Unmeasured      string
	Samples         int64
	IntervalMs      int64
	WindowMs        int64
	CpuUserUs       int64
	CpuSystemUs     int64
	GuestCpuUs      int64
	VmmCpuUs        int64
	MemoryPeakBytes int64
	OomKills        int64
	DiskReadBytes   int64
	DiskWriteBytes  int64
	NetRxBytes      int64
	NetTxBytes      int64
	NetRxPackets    int64
	NetTxPackets    int64
	CpuSomeUs       int64
	CpuFullUs       int64
	MemorySomeUs    int64
	MemoryFullUs    int64
	IoSomeUs        int64
	IoFullUs        int64
	EnergyActiveUj  int64
	EnergyIdleUj    int64
	EnergySource    string
}

// Job usage: what a job did to the host, measured by the host (migration 57).
// Keep the first usage report for a lease.
//
// DO NOTHING ON CONFLICT, because a node reports once and a retry after a lost
// answer carries the same summary; a second report is not allowed to replace
// the first. The epoch fence is the caller's, in the same transaction.
func (q *Queries) RecordJobUsage(ctx context.Context, arg RecordJobUsageParams) error {
	_, err := q.db.ExecContext(ctx, recordJobUsage,
		arg.LeaseID,
		arg.Node,
		arg.RecordedAt,
		arg.Source,
		arg.Unmeasured,
		arg.Samples,
		arg.IntervalMs,
		arg.WindowMs,
		arg.CpuUserUs,
		arg.CpuSystemUs,
		arg.GuestCpuUs,
		arg.VmmCpuUs,
		arg.MemoryPeakBytes,
		arg.OomKills,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.NetRxBytes,
		arg.NetTxBytes,
		arg.NetRxPackets,
		arg.NetTxPackets,
		arg.CpuSomeUs,
		arg.CpuFullUs,
		arg.MemorySomeUs,
		arg.MemoryFullUs,
		arg.IoSomeUs,
		arg.IoFullUs,
		arg.EnergyActiveUj,
		arg.EnergyIdleUj,
		arg.EnergySource,
	)
	return err
}
