// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobusage.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const readJobDestinations = `-- name: ReadJobDestinations :many
SELECT ordinal, addr, sent_bytes, received_bytes, connections
  FROM job_destinations WHERE lease_id = $1
 ORDER BY ordinal
`

type ReadJobDestinationsRow struct {
	Ordinal       int64
	Addr          string
	SentBytes     int64
	ReceivedBytes int64
	Connections   int64
}

// One lease's destinations in the order the node gave them, the total beyond
// them last.
func (q *Queries) ReadJobDestinations(ctx context.Context, leaseID string) ([]ReadJobDestinationsRow, error) {
	rows, err := q.db.QueryContext(ctx, readJobDestinations, leaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadJobDestinationsRow
	for rows.Next() {
		var i ReadJobDestinationsRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.Addr,
			&i.SentBytes,
			&i.ReceivedBytes,
			&i.Connections,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readJobSeries = `-- name: ReadJobSeries :one
SELECT codec, series FROM job_series WHERE lease_id = $1
`

type ReadJobSeriesRow struct {
	Codec  int64
	Series string
}

// One lease's series blob and the codec that wrote it.
func (q *Queries) ReadJobSeries(ctx context.Context, leaseID string) (ReadJobSeriesRow, error) {
	row := q.db.QueryRowContext(ctx, readJobSeries, leaseID)
	var i ReadJobSeriesRow
	err := row.Scan(&i.Codec, &i.Series)
	return i, err
}

const readJobUsage = `-- name: ReadJobUsage :one
SELECT lease_id, node, recorded_at, source, unmeasured, samples, interval_ms,
       window_ms, cpu_user_us, cpu_system_us, guest_cpu_us, vmm_cpu_us,
       memory_peak_bytes, oom_kills, disk_read_bytes, disk_write_bytes,
       net_rx_bytes, net_tx_bytes, net_rx_packets, net_tx_packets,
       cpu_some_us, cpu_full_us, memory_some_us, memory_full_us, io_some_us,
       io_full_us, energy_active_uj, energy_idle_uj, energy_source, cycles,
       instructions, cache_references, cache_misses, branch_misses,
       frontend_stall_cycles, destinations_incomplete, tap_sent_bytes,
       tap_received_bytes
  FROM job_usage WHERE lease_id = $1
`

// One lease's usage summary. sql.ErrNoRows means nothing was measured, which a
// reader says rather than printing zeros.
func (q *Queries) ReadJobUsage(ctx context.Context, leaseID string) (JobUsage, error) {
	row := q.db.QueryRowContext(ctx, readJobUsage, leaseID)
	var i JobUsage
	err := row.Scan(
		&i.LeaseID,
		&i.Node,
		&i.RecordedAt,
		&i.Source,
		&i.Unmeasured,
		&i.Samples,
		&i.IntervalMs,
		&i.WindowMs,
		&i.CpuUserUs,
		&i.CpuSystemUs,
		&i.GuestCpuUs,
		&i.VmmCpuUs,
		&i.MemoryPeakBytes,
		&i.OomKills,
		&i.DiskReadBytes,
		&i.DiskWriteBytes,
		&i.NetRxBytes,
		&i.NetTxBytes,
		&i.NetRxPackets,
		&i.NetTxPackets,
		&i.CpuSomeUs,
		&i.CpuFullUs,
		&i.MemorySomeUs,
		&i.MemoryFullUs,
		&i.IoSomeUs,
		&i.IoFullUs,
		&i.EnergyActiveUj,
		&i.EnergyIdleUj,
		&i.EnergySource,
		&i.Cycles,
		&i.Instructions,
		&i.CacheReferences,
		&i.CacheMisses,
		&i.BranchMisses,
		&i.FrontendStallCycles,
		&i.DestinationsIncomplete,
		&i.TapSentBytes,
		&i.TapReceivedBytes,
	)
	return i, err
}

const recordJobDestinations = `-- name: RecordJobDestinations :exec
WITH RECURSIVE slot (n, rec, rest) AS (
    SELECT 0, substr(CAST($2 AS TEXT), 1, 99),
           substr(CAST($2 AS TEXT), 100)
     WHERE 0 < CAST($3 AS BIGINT)
    UNION ALL
    SELECT n + 1, substr(rest, 1, 99), substr(rest, 100)
      FROM slot WHERE n + 1 < CAST($3 AS BIGINT)
)
INSERT INTO job_destinations
     (lease_id, ordinal, addr, sent_bytes, received_bytes, connections)
SELECT CAST($1 AS TEXT),
       CAST(substr(rec, 1, 3) AS BIGINT),
       rtrim(substr(rec, 4, 39)),
       CAST(substr(rec, 43, 19) AS BIGINT),
       CAST(substr(rec, 62, 19) AS BIGINT),
       CAST(substr(rec, 81, 19) AS BIGINT)
  FROM slot
`

type RecordJobDestinationsParams struct {
	LeaseID  string
	Packed   string
	RowCount int64
}

// Every one of a job's destination rows, the named ones and the total beyond
// them (migration 59), written only by the usage report that won
// RecordJobUsage, in its transaction, so a lease's rows are one report's.
//
// ONE STATEMENT FOR UP TO 257 ROWS, because a write transaction holds the
// ledger's only writer slot (SQLite) or its write lock (PostgreSQL) for every
// round trip it makes, and one INSERT a row made 257 of them: measured
// 2026-10-09 against a PostgreSQL on loopback, 18 ms a report one row at a time
// and 14 ms in one statement, a gap that grows by 256 round trips on a real
// network. A portable statement cannot take a list, so the caller packs the
// rows into one string of fixed-width records (internal/alloc
// packDestinations: a 3-digit ordinal, the address space-padded to 39
// characters, then the sent, received and connection counts as 19 zero-padded
// digits each, 99 characters a row) and the recursive slot list below cuts one
// record off the front at each step.
//
// EACH STEP CARRIES THE REST rather than indexing into the whole string,
// because both engines find a character offset in TEXT by scanning from its
// start: indexed, the same report took 57 ms on PostgreSQL.
func (q *Queries) RecordJobDestinations(ctx context.Context, arg RecordJobDestinationsParams) error {
	_, err := q.db.ExecContext(ctx, recordJobDestinations, arg.LeaseID, arg.Packed, arg.RowCount)
	return err
}

const recordJobSeries = `-- name: RecordJobSeries :exec
INSERT INTO job_series (lease_id, codec, series)
VALUES ($1, $2, $3)
ON CONFLICT (lease_id) DO NOTHING
`

type RecordJobSeriesParams struct {
	LeaseID string
	Codec   int64
	Series  string
}

// Keep the first series for a lease, for the reason RecordJobUsage keeps the
// first summary.
func (q *Queries) RecordJobSeries(ctx context.Context, arg RecordJobSeriesParams) error {
	_, err := q.db.ExecContext(ctx, recordJobSeries, arg.LeaseID, arg.Codec, arg.Series)
	return err
}

const recordJobUsage = `-- name: RecordJobUsage :execrows

INSERT INTO job_usage
     (lease_id, node, recorded_at, source, unmeasured, samples, interval_ms,
      window_ms, cpu_user_us, cpu_system_us, guest_cpu_us, vmm_cpu_us,
      memory_peak_bytes, oom_kills, disk_read_bytes, disk_write_bytes,
      net_rx_bytes, net_tx_bytes, net_rx_packets, net_tx_packets,
      cpu_some_us, cpu_full_us, memory_some_us, memory_full_us, io_some_us,
      io_full_us, energy_active_uj, energy_idle_uj, energy_source,
      cycles, instructions, cache_references, cache_misses, branch_misses,
      frontend_stall_cycles, destinations_incomplete, tap_sent_bytes,
      tap_received_bytes)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12, $13, $14, $15,
        $16, $17, $18, $19,
        $20, $21, $22, $23,
        $24, $25, $26, $27,
        $28, $29, $30, $31,
        $32, $33, $34,
        $35, $36, $37,
        $38)
ON CONFLICT (lease_id) DO NOTHING
`

type RecordJobUsageParams struct {
	LeaseID                string
	Node                   string
	RecordedAt             string
	Source                 string
	Unmeasured             string
	Samples                int64
	IntervalMs             int64
	WindowMs               int64
	CpuUserUs              int64
	CpuSystemUs            int64
	GuestCpuUs             int64
	VmmCpuUs               int64
	MemoryPeakBytes        int64
	OomKills               int64
	DiskReadBytes          int64
	DiskWriteBytes         int64
	NetRxBytes             int64
	NetTxBytes             int64
	NetRxPackets           int64
	NetTxPackets           int64
	CpuSomeUs              int64
	CpuFullUs              int64
	MemorySomeUs           int64
	MemoryFullUs           int64
	IoSomeUs               int64
	IoFullUs               int64
	EnergyActiveUj         int64
	EnergyIdleUj           int64
	EnergySource           string
	Cycles                 sql.NullInt64
	Instructions           sql.NullInt64
	CacheReferences        sql.NullInt64
	CacheMisses            sql.NullInt64
	BranchMisses           sql.NullInt64
	FrontendStallCycles    sql.NullInt64
	DestinationsIncomplete sql.NullInt64
	TapSentBytes           sql.NullInt64
	TapReceivedBytes       sql.NullInt64
}

// Job usage: what a job did to the host, measured by the host (migration 57).
// Keep the first usage report for a lease.
//
// DO NOTHING ON CONFLICT, because a node reports once and a retry after a lost
// answer carries the same summary; a second report is not allowed to replace
// the first. The epoch fence is the caller's, in the same transaction.
//
// THE ROW COUNT SAYS WHETHER THIS REPORT WON, and only the report that won may
// write the series: otherwise a first report without a series and a second
// with one would be stored as a pair neither request sent.
//
// A hardware counter is NULL where it was not counted (migration 58), and
// destinations_incomplete is NULL where the flows were not totalled, the tap's
// totals NULL where the tap was not read (migration 59).
func (q *Queries) RecordJobUsage(ctx context.Context, arg RecordJobUsageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordJobUsage,
		arg.LeaseID,
		arg.Node,
		arg.RecordedAt,
		arg.Source,
		arg.Unmeasured,
		arg.Samples,
		arg.IntervalMs,
		arg.WindowMs,
		arg.CpuUserUs,
		arg.CpuSystemUs,
		arg.GuestCpuUs,
		arg.VmmCpuUs,
		arg.MemoryPeakBytes,
		arg.OomKills,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.NetRxBytes,
		arg.NetTxBytes,
		arg.NetRxPackets,
		arg.NetTxPackets,
		arg.CpuSomeUs,
		arg.CpuFullUs,
		arg.MemorySomeUs,
		arg.MemoryFullUs,
		arg.IoSomeUs,
		arg.IoFullUs,
		arg.EnergyActiveUj,
		arg.EnergyIdleUj,
		arg.EnergySource,
		arg.Cycles,
		arg.Instructions,
		arg.CacheReferences,
		arg.CacheMisses,
		arg.BranchMisses,
		arg.FrontendStallCycles,
		arg.DestinationsIncomplete,
		arg.TapSentBytes,
		arg.TapReceivedBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
