// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jointokens.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const insertJoinToken = `-- name: InsertJoinToken :exec

INSERT INTO join_tokens (token_sha256, note, uses_remaining, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertJoinTokenParams struct {
	TokenSha256   string
	Note          string
	UsesRemaining int64
	CreatedAt     string
	ExpiresAt     string
}

// Join tokens: the short-lived credential that lets a machine ASK to enroll.
//
// The token is never stored. What the table holds is its sha256, which is why
// every statement here takes a hash rather than a secret.
// Mint one join token.
func (q *Queries) InsertJoinToken(ctx context.Context, arg InsertJoinTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertJoinToken,
		arg.TokenSha256,
		arg.Note,
		arg.UsesRemaining,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listJoinTokenHashes = `-- name: ListJoinTokenHashes :many
SELECT token_sha256 FROM join_tokens
`

// Every key the table holds, for the test that says the secret is not among
// them.
func (q *Queries) ListJoinTokenHashes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listJoinTokenHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token_sha256 string
		if err := rows.Scan(&token_sha256); err != nil {
			return nil, err
		}
		items = append(items, token_sha256)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinTokens = `-- name: ListJoinTokens :many
SELECT note, uses_remaining, created_at, expires_at FROM join_tokens
 ORDER BY created_at DESC
`

type ListJoinTokensRow struct {
	Note          string
	UsesRemaining int64
	CreatedAt     string
	ExpiresAt     string
}

// What is outstanding, without the secrets.
func (q *Queries) ListJoinTokens(ctx context.Context) ([]ListJoinTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listJoinTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinTokensRow
	for rows.Next() {
		var i ListJoinTokensRow
		if err := rows.Scan(
			&i.Note,
			&i.UsesRemaining,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveJoinTokenExists = `-- name: LiveJoinTokenExists :one
SELECT EXISTS(SELECT 1 FROM join_tokens
               WHERE token_sha256 = $1 AND uses_remaining > 0
                 AND expires_at > $2)
`

type LiveJoinTokenExistsParams struct {
	TokenSha256 string
	Now         string
}

// Whether a token with this hash could possibly be spent right now.
//
// IT AUTHORISES NOTHING. Someone else may spend the last use a microsecond
// later, and the enrollment transaction is what actually decides; this exists
// only to keep a caller with no usable token off the single writer connection.
func (q *Queries) LiveJoinTokenExists(ctx context.Context, arg LiveJoinTokenExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, liveJoinTokenExists, arg.TokenSha256, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const spendJoinToken = `-- name: SpendJoinToken :execresult
UPDATE join_tokens SET uses_remaining = uses_remaining - 1
 WHERE token_sha256 = $1 AND uses_remaining > 0 AND expires_at > $2
`

type SpendJoinTokenParams struct {
	TokenSha256 string
	Now         string
}

// Check a token and consume one use, in one statement.
//
// CHECK AND DECREMENT TOGETHER, so two machines racing on a single-use token
// cannot both be admitted: this matches only while a use remains and the token
// is unexpired, and whichever commits second changes no rows. The caller reads
// RowsAffected, which is why this is :execresult and not :exec -- an :exec
// returns nothing to distinguish "spent" from "there was nothing to spend".
func (q *Queries) SpendJoinToken(ctx context.Context, arg SpendJoinTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, spendJoinToken, arg.TokenSha256, arg.Now)
}
