// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const assignLease = `-- name: AssignLease :exec
UPDATE leases
   SET phase = $1, run_id = $2, request_id = $3,
       heartbeat_at = $4, expires_at = $5
 WHERE id = $6 AND epoch = $7
`

type AssignLeaseParams struct {
	Phase       string
	RunID       sql.NullInt64
	RequestID   sql.NullInt64
	HeartbeatAt string
	ExpiresAt   string
	ID          string
	Epoch       int64
}

// Bind an escrowed lease to a GitHub job and refresh its TTL.
func (q *Queries) AssignLease(ctx context.Context, arg AssignLeaseParams) error {
	_, err := q.db.ExecContext(ctx, assignLease,
		arg.Phase,
		arg.RunID,
		arg.RequestID,
		arg.HeartbeatAt,
		arg.ExpiresAt,
		arg.ID,
		arg.Epoch,
	)
	return err
}

const backfillLeaseFailureReason = `-- name: BackfillLeaseFailureReason :exec
UPDATE leases SET failure_reason = $1
 WHERE id = $2 AND phase = 'failed' AND failure_reason = ''
`

type BackfillLeaseFailureReasonParams struct {
	FailureReason string
	ID            string
}

// The lease-row half of BackfillFailureReason: a failed row with no reason.
func (q *Queries) BackfillLeaseFailureReason(ctx context.Context, arg BackfillLeaseFailureReasonParams) error {
	_, err := q.db.ExecContext(ctx, backfillLeaseFailureReason, arg.FailureReason, arg.ID)
	return err
}

const bindLease = `-- name: BindLease :exec
UPDATE leases SET node = $1, chosen_provider = $2,
       holder_incarnation = $3
 WHERE id = $4 AND epoch = $5
`

type BindLeaseParams struct {
	Node              sql.NullString
	ChosenProvider    string
	HolderIncarnation string
	ID                string
	Epoch             int64
}

// Record which host the work actually went to, and the backend it runs on.
//
// THE PROVIDER IS THE HOST'S REGISTERED ONE, read in this transaction rather than
// taken from a catalogue: the registration is what the machine itself reported.
//
// holder_incarnation IS THAT HOST'S INCARNATION, read in the same transaction:
// the process that is launching this compute. A report compares it with the
// node's current incarnation to say whether the process that was given the
// work is still the one the deployment talks to. It decides nothing.
func (q *Queries) BindLease(ctx context.Context, arg BindLeaseParams) error {
	_, err := q.db.ExecContext(ctx, bindLease,
		arg.Node,
		arg.ChosenProvider,
		arg.HolderIncarnation,
		arg.ID,
		arg.Epoch,
	)
	return err
}

const countActiveRunnerLeases = `-- name: CountActiveRunnerLeases :one
SELECT CAST(COUNT(*) AS BIGINT) FROM leases
 WHERE tier = $1 AND phase NOT IN ('capacity','done','failed') AND deregistered = 0
`

// How many runners GitHub could still route a job to, in one tier.
//
// KEYED ON deregistered RATHER THAN ON PHASE, because the question is whether the
// GitHub registration is gone rather than what billet's compute lifecycle is
// doing: a teardown still retrying its destroy is deregistered and must stop
// counting, while a teardown whose runner was never deregistered must keep
// counting or a replacement is launched against a runner GitHub can still
// schedule.
func (q *Queries) CountActiveRunnerLeases(ctx context.Context, tier string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRunnerLeases, tier)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOpenInTier = `-- name: CountOpenInTier :one
SELECT CAST(COUNT(*) AS BIGINT) FROM leases
 WHERE tier = $1 AND phase NOT IN ('done','failed')
`

// Everything one tier holds, live host or not.
func (q *Queries) CountOpenInTier(ctx context.Context, tier string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenInTier, tier)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOpenPerTier = `-- name: CountOpenPerTier :many
SELECT l.tier, CAST(COUNT(*) AS BIGINT) AS open_leases
  FROM leases l
  LEFT JOIN nodes n ON n.name = COALESCE(l.node, l.target_node)
 WHERE l.phase NOT IN ('done','failed')
   AND (COALESCE(l.node, l.target_node, '') = ''
        OR (n.live = 1 AND n.drained = 0))
 GROUP BY l.tier
`

type CountOpenPerTierRow struct {
	Tier       string
	OpenLeases int64
}

// How much each tier already holds, for the floor arithmetic.
//
// A LEASE ON A HOST THAT IS GONE COUNTS FOR NOTHING, which is what the LEFT JOIN
// and the liveness test express: a floor is about capacity a tier can actually
// use. An UNPLACED lease still counts, because escrow has promised it.
//
// THAT UNPLACED CLAUSE IS UNREACHABLE THROUGH TODAY'S API, and that is said here
// rather than left for somebody to discover: every reservation names a machine
// now -- Reserve refuses when placement finds no host, so insertLease always has
// a target -- and only a row written before that was true has an empty one.
// Measured: deleting the clause fails no test in internal/alloc. It stays because
// such rows exist in deployments upgraded from before, and dropping them from a
// tier's committed count understates what that tier already holds.
func (q *Queries) CountOpenPerTier(ctx context.Context) ([]CountOpenPerTierRow, error) {
	rows, err := q.db.QueryContext(ctx, countOpenPerTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenPerTierRow
	for rows.Next() {
		var i CountOpenPerTierRow
		if err := rows.Scan(&i.Tier, &i.OpenLeases); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heartbeatLease = `-- name: HeartbeatLease :exec
UPDATE leases SET heartbeat_at = $1, expires_at = $2
 WHERE id = $3 AND epoch = $4
`

type HeartbeatLeaseParams struct {
	HeartbeatAt string
	ExpiresAt   string
	ID          string
	Epoch       int64
}

// Push a lease's expiry out.
func (q *Queries) HeartbeatLease(ctx context.Context, arg HeartbeatLeaseParams) error {
	_, err := q.db.ExecContext(ctx, heartbeatLease,
		arg.HeartbeatAt,
		arg.ExpiresAt,
		arg.ID,
		arg.Epoch,
	)
	return err
}

const holdLease = `-- name: HoldLease :exec
UPDATE leases
   SET phase = $1, held_at = $2, heartbeat_at = $3,
       expires_at = $4, holder_incarnation = $5
 WHERE id = $6 AND epoch = $7
`

type HoldLeaseParams struct {
	Phase             string
	HeldAt            string
	HeartbeatAt       string
	ExpiresAt         string
	HolderIncarnation string
	ID                string
	Epoch             int64
}

// Move a lease into a phase that holds compute, and keep its TTL alive.
//
// held_at IS WHEN THE OBLIGATION STARTED, which is what an operator report ages
// from. The TTL still moves because a held lease is still being tended.
//
// holder_incarnation IS REWRITTEN ON THE WAY INTO CUSTODY OR TEARDOWN, because
// the process taking the obligation may not be the one that launched the
// compute -- a restart adopts what it finds -- and the caller passes the value
// it read for every other phase so the column is never blanked.
func (q *Queries) HoldLease(ctx context.Context, arg HoldLeaseParams) error {
	_, err := q.db.ExecContext(ctx, holdLease,
		arg.Phase,
		arg.HeldAt,
		arg.HeartbeatAt,
		arg.ExpiresAt,
		arg.HolderIncarnation,
		arg.ID,
		arg.Epoch,
	)
	return err
}

const insertLease = `-- name: InsertLease :exec
INSERT INTO leases
   (id, tier, node, target_node, macos_slot, guest_os, providers, phase, vcpu, memory,
    requested_vcpu, requested_memory, instance_type, site, price_micros_per_hour,
    epoch, created_at, heartbeat_at, expires_at)
VALUES ($1, $2, NULL, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13,
        $14, 0, $15, $16, $17)
`

type InsertLeaseParams struct {
	ID                 string
	Tier               string
	TargetNode         sql.NullString
	MacosSlot          int64
	GuestOs            string
	Providers          string
	Phase              string
	Vcpu               int64
	Memory             int64
	RequestedVcpu      int64
	RequestedMemory    int64
	InstanceType       string
	Site               string
	PriceMicrosPerHour int64
	CreatedAt          string
	HeartbeatAt        string
	ExpiresAt          string
}

// Escrow one slot.
//
// node IS NULL AND target_node IS NOT. The two answer different questions: the
// target is where billet DECIDED the work goes, the node is where it actually
// went. Capacity is charged on COALESCE(node, target_node) precisely so a
// reservation aimed at a machine spends that machine's room immediately --
// counting only bound leases let a tier escrow against the same host repeatedly
// in the window before its first launch, which is the deployment-level overcommit
// moved down to the machine.
//
// THE REQUESTED AND CHARGED VECTORS ARE BOTH RECORDED. A remote lease is charged
// for the SHAPE placement bought rather than the smaller tier request, and a
// fallback resizes the charge; the immutable request is what a later shape is
// checked against.
//
// THE PRICE IS THE SHAPE'S PRICE AT THE MOMENT IT IS CHARGED, in millionths of
// a dollar, and the site is the placed host's registered site. Both are written
// here rather than read back later because a node may re-register with a new
// catalogue while this lease is open, and the history a terminalization copies
// has to say what the deployment bought, not what it would pay today. Zero is a
// host-backed lease, which buys nothing.
func (q *Queries) InsertLease(ctx context.Context, arg InsertLeaseParams) error {
	_, err := q.db.ExecContext(ctx, insertLease,
		arg.ID,
		arg.Tier,
		arg.TargetNode,
		arg.MacosSlot,
		arg.GuestOs,
		arg.Providers,
		arg.Phase,
		arg.Vcpu,
		arg.Memory,
		arg.RequestedVcpu,
		arg.RequestedMemory,
		arg.InstanceType,
		arg.Site,
		arg.PriceMicrosPerHour,
		arg.CreatedAt,
		arg.HeartbeatAt,
		arg.ExpiresAt,
	)
	return err
}

const listExpiredLeases = `-- name: ListExpiredLeases :many
SELECT id, tier, node, target_node, macos_slot, chosen_provider, phase, vcpu, memory,
       requested_vcpu, requested_memory, instance_type, site, price_micros_per_hour,
       image_cache, cache_generation, actions_cache, held_at, force_release,
       holder_incarnation, failure_reason, disruption, disrupted_at, epoch, run_id,
       request_id
  FROM leases
 WHERE phase NOT IN ('done','failed','quarantine') AND expires_at <= $1
 ORDER BY expires_at
 LIMIT CAST($2 AS BIGINT)
`

type ListExpiredLeasesParams struct {
	Cutoff  string
	MaxRows int64
}

type ListExpiredLeasesRow struct {
	ID                 string
	Tier               string
	Node               sql.NullString
	TargetNode         sql.NullString
	MacosSlot          int64
	ChosenProvider     string
	Phase              string
	Vcpu               int64
	Memory             int64
	RequestedVcpu      int64
	RequestedMemory    int64
	InstanceType       string
	Site               string
	PriceMicrosPerHour int64
	ImageCache         string
	CacheGeneration    string
	ActionsCache       string
	HeldAt             string
	ForceRelease       int64
	HolderIncarnation  string
	FailureReason      string
	Disruption         string
	DisruptedAt        string
	Epoch              int64
	RunID              sql.NullInt64
	RequestID          sql.NullInt64
}

// The leases whose holders stopped heartbeating.
//
// QUARANTINE IS EXCLUDED because it is already past this line: its compute is
// unconfirmed and its capacity stays charged until something proves otherwise, so
// reaping it again would be the reaper deciding a question only evidence settles.
//
// EVERYTHING THE ARCHIVE COPIES IS SELECTED, chosen_provider included. The
// reaper terminalizes an expired escrow outright and archives it from this row,
// and a projection that left the provider out archived every reaped lease as
// having run on nothing.
func (q *Queries) ListExpiredLeases(ctx context.Context, arg ListExpiredLeasesParams) ([]ListExpiredLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredLeases, arg.Cutoff, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredLeasesRow
	for rows.Next() {
		var i ListExpiredLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Tier,
			&i.Node,
			&i.TargetNode,
			&i.MacosSlot,
			&i.ChosenProvider,
			&i.Phase,
			&i.Vcpu,
			&i.Memory,
			&i.RequestedVcpu,
			&i.RequestedMemory,
			&i.InstanceType,
			&i.Site,
			&i.PriceMicrosPerHour,
			&i.ImageCache,
			&i.CacheGeneration,
			&i.ActionsCache,
			&i.HeldAt,
			&i.ForceRelease,
			&i.HolderIncarnation,
			&i.FailureReason,
			&i.Disruption,
			&i.DisruptedAt,
			&i.Epoch,
			&i.RunID,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaseIDsOnNode = `-- name: ListLeaseIDsOnNode :many
SELECT id FROM leases
 WHERE node = $1
   AND phase IN ($2, $3, $4, $5, $6)
`

type ListLeaseIDsOnNodeParams struct {
	Node      sql.NullString
	Launching string
	Online    string
	Busy      string
	Custody   string
	Teardown  string
}

// The leases one host is running compute for.
func (q *Queries) ListLeaseIDsOnNode(ctx context.Context, arg ListLeaseIDsOnNodeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLeaseIDsOnNode,
		arg.Node,
		arg.Launching,
		arg.Online,
		arg.Busy,
		arg.Custody,
		arg.Teardown,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceableRunnerLeaseIDs = `-- name: ListServiceableRunnerLeaseIDs :many
SELECT leases.id FROM leases
 WHERE leases.tier = $1
   AND leases.phase IN ('launching','online','busy','custody')
   AND NOT EXISTS (SELECT 1 FROM pool_runners
                    WHERE pool_runners.lease_id = leases.id
                      AND pool_runners.status IN ('retiring','retired'))
 ORDER BY leases.id
`

// The leases in one tier whose compute a restart should re-adopt.
//
// RETIRING AND RETIRED POOL MEMBERS ARE EXCLUDED: their registration is being
// removed or is gone, so re-adopting them would hold capacity for a runner
// nothing can route to.
func (q *Queries) ListServiceableRunnerLeaseIDs(ctx context.Context, tier string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listServiceableRunnerLeaseIDs, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLeaseDeregistered = `-- name: MarkLeaseDeregistered :exec
UPDATE leases SET deregistered = 1 WHERE id = $1
`

// Record that GitHub's runner registration for this lease has been removed.
//
// DELIBERATELY UNFENCED. Deregistration is a monotonic fact about GitHub, not
// about who holds the lease: once RemoveRunner has succeeded the runner is gone
// whatever the epoch. A quarantined lease has only terminal successors and a reap
// never relaunches on the same row -- new capacity is always a fresh id -- so no
// live runner can occupy a row this flag has set. Fencing it would let a reap
// landing between RemoveRunner and this mark strand a gone runner as counted
// forever.
func (q *Queries) MarkLeaseDeregistered(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markLeaseDeregistered, id)
	return err
}

const markLeaseFailure = `-- name: MarkLeaseFailure :exec
UPDATE leases SET failure_reason = $1 WHERE id = $2 AND epoch = $3
`

type MarkLeaseFailureParams struct {
	FailureReason string
	ID            string
	Epoch         int64
}

// Record why a still-open lease is destined to fail.
//
// SEPARATE FROM RELEASING IT, because the fact often arrives before the compute
// is gone and capacity must stay charged throughout that interval.
func (q *Queries) MarkLeaseFailure(ctx context.Context, arg MarkLeaseFailureParams) error {
	_, err := q.db.ExecContext(ctx, markLeaseFailure, arg.FailureReason, arg.ID, arg.Epoch)
	return err
}

const readLease = `-- name: ReadLease :one
SELECT id, tier, node, target_node, macos_slot, guest_os, providers, chosen_provider,
       phase, vcpu, memory, requested_vcpu, requested_memory, instance_type, site,
       price_micros_per_hour, image_cache, cache_generation, actions_cache,
       held_at, force_release, holder_incarnation, failure_reason, disruption,
       disrupted_at, epoch, run_id, request_id
  FROM leases WHERE id = $1
`

type ReadLeaseRow struct {
	ID                 string
	Tier               string
	Node               sql.NullString
	TargetNode         sql.NullString
	MacosSlot          int64
	GuestOs            string
	Providers          string
	ChosenProvider     string
	Phase              string
	Vcpu               int64
	Memory             int64
	RequestedVcpu      int64
	RequestedMemory    int64
	InstanceType       string
	Site               string
	PriceMicrosPerHour int64
	ImageCache         string
	CacheGeneration    string
	ActionsCache       string
	HeldAt             string
	ForceRelease       int64
	HolderIncarnation  string
	FailureReason      string
	Disruption         string
	DisruptedAt        string
	Epoch              int64
	RunID              sql.NullInt64
	RequestID          sql.NullInt64
}

// One lease, whatever phase it is in.
func (q *Queries) ReadLease(ctx context.Context, id string) (ReadLeaseRow, error) {
	row := q.db.QueryRowContext(ctx, readLease, id)
	var i ReadLeaseRow
	err := row.Scan(
		&i.ID,
		&i.Tier,
		&i.Node,
		&i.TargetNode,
		&i.MacosSlot,
		&i.GuestOs,
		&i.Providers,
		&i.ChosenProvider,
		&i.Phase,
		&i.Vcpu,
		&i.Memory,
		&i.RequestedVcpu,
		&i.RequestedMemory,
		&i.InstanceType,
		&i.Site,
		&i.PriceMicrosPerHour,
		&i.ImageCache,
		&i.CacheGeneration,
		&i.ActionsCache,
		&i.HeldAt,
		&i.ForceRelease,
		&i.HolderIncarnation,
		&i.FailureReason,
		&i.Disruption,
		&i.DisruptedAt,
		&i.Epoch,
		&i.RunID,
		&i.RequestID,
	)
	return i, err
}

const readLeaseClosure = `-- name: ReadLeaseClosure :one
SELECT l.phase, CAST(COALESCE(h.finished_at, '') AS TEXT) AS finished_at
  FROM leases l
  LEFT JOIN job_history h ON h.lease_id = l.id
 WHERE l.id = $1
`

type ReadLeaseClosureRow struct {
	Phase      string
	FinishedAt string
}

// Whether one lease has finished, and when the ledger closed it.
//
// THE ONE QUESTION THAT MAY AUTHORISE DELETING A STAGED REGISTRATION. A CodeBuild
// runner's JIT configuration outlives its build in Parameter Store, and from the
// provider alone "no build for this lease" and "the build has not appeared yet"
// are the same observation. What separates them is this row: a terminal phase,
// closed longer ago than any build could still be running. sql.ErrNoRows is a
// lease the ledger has never heard of, which the caller reports and never acts on.
//
// finished_at comes from job_history, which every terminalization writes; the
// COALESCE is for a row that predates the column, which reads as "closed at an
// unknown time" and is therefore never old enough.
func (q *Queries) ReadLeaseClosure(ctx context.Context, id string) (ReadLeaseClosureRow, error) {
	row := q.db.QueryRowContext(ctx, readLeaseClosure, id)
	var i ReadLeaseClosureRow
	err := row.Scan(&i.Phase, &i.FinishedAt)
	return i, err
}

const readLeaseEpoch = `-- name: ReadLeaseEpoch :one

SELECT epoch FROM leases WHERE id = $1
`

// The capacity ledger's central row.
//
// A LEASE IS THE UNIT OF CAPACITY, and every rule about not promising a machine
// billet does not have is expressed as a predicate on this table. Two of them
// recur in almost every statement and are worth knowing before reading any of
// them:
//
//	COALESCE(node, target_node)   `node` is where the work actually went and
//	                              `target_node` is where billet decided it
//	                              would go. Capacity is charged on the
//	                              coalesce, because a reservation aimed at a
//	                              machine has already spent that machine's
//	                              room -- counting only bound leases let a tier
//	                              escrow against the same host repeatedly in
//	                              the window before its first launch.
//
//	AND epoch = @epoch            The fence. A holder declared dead and replaced
//	                              must not keep writing to a lease somebody else
//	                              now owns, so every write that acts on a row a
//	                              caller read presents the epoch it read.
//
// One lease's current fencing token.
//
// sql.ErrNoRows means the lease is gone, which callers report as
// ErrLeaseNotFound rather than as a read failure.
func (q *Queries) ReadLeaseEpoch(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, readLeaseEpoch, id)
	var epoch int64
	err := row.Scan(&epoch)
	return epoch, err
}

const readLeaseJob = `-- name: ReadLeaseJob :one
SELECT tier, run_id, request_id FROM leases WHERE id = $1
`

type ReadLeaseJobRow struct {
	Tier      string
	RunID     sql.NullInt64
	RequestID sql.NullInt64
}

// The tier and job identity one lease carries.
func (q *Queries) ReadLeaseJob(ctx context.Context, id string) (ReadLeaseJobRow, error) {
	row := q.db.QueryRowContext(ctx, readLeaseJob, id)
	var i ReadLeaseJobRow
	err := row.Scan(&i.Tier, &i.RunID, &i.RequestID)
	return i, err
}

const reclaimLease = `-- name: ReclaimLease :exec
UPDATE leases
   SET phase = $1, epoch = epoch + 1,
       held_at = CASE WHEN CAST($1 AS TEXT) = CAST($2 AS TEXT)
                       AND held_at = '' THEN CAST($3 AS TEXT) ELSE held_at END
 WHERE id = $4 AND epoch = $5
`

type ReclaimLeaseParams struct {
	Phase      string
	Quarantine string
	HeldAt     string
	ID         string
	Epoch      int64
}

// Terminalize or quarantine an expired lease, bumping the fence.
//
// THE EPOCH BUMP IS THE POINT. A holder that comes back -- a paused process, a
// healed partition -- finds its writes refused rather than silently operating on
// a lease somebody else now owns.
//
// held_at IS SET ONLY ON THE WAY INTO QUARANTINE, and only if it is empty: that
// is when the proof obligation starts, and a lease reaped twice must not have its
// age reset.
func (q *Queries) ReclaimLease(ctx context.Context, arg ReclaimLeaseParams) error {
	_, err := q.db.ExecContext(ctx, reclaimLease,
		arg.Phase,
		arg.Quarantine,
		arg.HeldAt,
		arg.ID,
		arg.Epoch,
	)
	return err
}

const refreshLeaseHolder = `-- name: RefreshLeaseHolder :exec
UPDATE leases SET holder_incarnation = $1
 WHERE id = $2 AND epoch = $3 AND holder_incarnation <> $1
`

type RefreshLeaseHolderParams struct {
	HolderIncarnation string
	ID                string
	Epoch             int64
}

// Re-record which process holds a lease already in a held phase.
//
// FOR A REPORT OF A HOLD THE LEASE IS ALREADY IN. A restart adopts a teardown
// or custody it finds and reports the same phase; the idempotent report writes
// nothing else, and without this the process that died would stay the durable
// holder while its replacement renews and tends the compute. Fenced on the
// epoch like every other write, and a no-op when nothing changed.
func (q *Queries) RefreshLeaseHolder(ctx context.Context, arg RefreshLeaseHolderParams) error {
	_, err := q.db.ExecContext(ctx, refreshLeaseHolder, arg.HolderIncarnation, arg.ID, arg.Epoch)
	return err
}

const resizeLease = `-- name: ResizeLease :exec
UPDATE leases SET vcpu = $1, memory = $2, instance_type = $3,
       price_micros_per_hour = $4
 WHERE id = $5 AND epoch = $6
`

type ResizeLeaseParams struct {
	Vcpu               int64
	Memory             int64
	InstanceType       string
	PriceMicrosPerHour int64
	ID                 string
	Epoch              int64
}

// Authorise a remote fallback shape, atomically with the budget check above it.
//
// A LATER FALLBACK IS A NEW PURCHASE DECISION, so its larger resource vector must
// fit before the launch request is allowed onto the wire -- never reconciled
// afterwards.
//
// THE PRICE MOVES WITH THE SHAPE: a fallback is a different purchase at a
// different rate, and the history records what was bought.
func (q *Queries) ResizeLease(ctx context.Context, arg ResizeLeaseParams) error {
	_, err := q.db.ExecContext(ctx, resizeLease,
		arg.Vcpu,
		arg.Memory,
		arg.InstanceType,
		arg.PriceMicrosPerHour,
		arg.ID,
		arg.Epoch,
	)
	return err
}

const setLeasePhase = `-- name: SetLeasePhase :exec
UPDATE leases SET phase = $1 WHERE id = $2 AND epoch = $3
`

type SetLeasePhaseParams struct {
	Phase string
	ID    string
	Epoch int64
}

// Move a lease to a phase the caller has already validated.
func (q *Queries) SetLeasePhase(ctx context.Context, arg SetLeasePhaseParams) error {
	_, err := q.db.ExecContext(ctx, setLeasePhase, arg.Phase, arg.ID, arg.Epoch)
	return err
}

const totalUsage = `-- name: TotalUsage :one
SELECT CAST(COALESCE(SUM(vcpu), 0) AS BIGINT) AS vcpu,
       CAST(COALESCE(SUM(memory), 0) AS BIGINT) AS memory,
       CAST(COUNT(*) AS BIGINT) AS leases
  FROM leases WHERE phase NOT IN ('done','failed')
`

type TotalUsageRow struct {
	Vcpu   int64
	Memory int64
	Leases int64
}

// What the whole deployment has committed.
func (q *Queries) TotalUsage(ctx context.Context) (TotalUsageRow, error) {
	row := q.db.QueryRowContext(ctx, totalUsage)
	var i TotalUsageRow
	err := row.Scan(&i.Vcpu, &i.Memory, &i.Leases)
	return i, err
}
