// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listenercapacity.sql

package ledgerdb

import (
	"context"
)

const readListenerCapacity = `-- name: ReadListenerCapacity :one
SELECT tier, observed_at, snapshot FROM listener_capacity WHERE tier = $1
`

func (q *Queries) ReadListenerCapacity(ctx context.Context, tier string) (ListenerCapacity, error) {
	row := q.db.QueryRowContext(ctx, readListenerCapacity, tier)
	var i ListenerCapacity
	err := row.Scan(&i.Tier, &i.ObservedAt, &i.Snapshot)
	return i, err
}

const recordListenerCapacity = `-- name: RecordListenerCapacity :exec
INSERT INTO listener_capacity (tier, observed_at, snapshot)
VALUES ($1, $2, $3)
ON CONFLICT (tier) DO UPDATE SET
    observed_at = excluded.observed_at,
    snapshot = excluded.snapshot
`

type RecordListenerCapacityParams struct {
	Tier       string
	ObservedAt string
	Snapshot   string
}

func (q *Queries) RecordListenerCapacity(ctx context.Context, arg RecordListenerCapacityParams) error {
	_, err := q.db.ExecContext(ctx, recordListenerCapacity, arg.Tier, arg.ObservedAt, arg.Snapshot)
	return err
}
