// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package ledgerdb

import (
	"context"
)

const listAppliedMigrations = `-- name: ListAppliedMigrations :many
SELECT version, name, checksum FROM schema_migrations ORDER BY version
`

type ListAppliedMigrationsRow struct {
	Version  int64
	Name     string
	Checksum string
}

// Every migration this ledger has recorded, oldest first.
//
// ORDERED so two readings of one ledger compare and serialise identically; the
// migrator itself keys on version and does not depend on the order.
func (q *Queries) ListAppliedMigrations(ctx context.Context) ([]ListAppliedMigrationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppliedMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppliedMigrationsRow
	for rows.Next() {
		var i ListAppliedMigrationsRow
		if err := rows.Scan(&i.Version, &i.Name, &i.Checksum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMigration = `-- name: RecordMigration :exec
INSERT INTO schema_migrations (version, name, checksum, applied_at)
VALUES ($1, $2, $3, $4)
`

type RecordMigrationParams struct {
	Version   int64
	Name      string
	Checksum  string
	AppliedAt string
}

// Record one migration as applied, in the same transaction that applied it.
//
// The checksum is over the statement BYTES, so this row is what a later open
// compares against to refuse an edited migration.
func (q *Queries) RecordMigration(ctx context.Context, arg RecordMigrationParams) error {
	_, err := q.db.ExecContext(ctx, recordMigration,
		arg.Version,
		arg.Name,
		arg.Checksum,
		arg.AppliedAt,
	)
	return err
}
