// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ledgerdb

type Admission struct {
	ID         int64
	Mode       string
	Generation int64
	Provenance string
	Reason     string
	Actor      string
	ChangedAt  string
}

type ControllerRetirement struct {
	Deployment   string
	Retiring     string
	Survivor     string
	Run          string
	State        string
	TransitionID string
	ReservedAt   string
	UpdatedAt    string
	CompletedBy  string
	CompletedAt  string
}

type CredentialSweep struct {
	Region       string
	Path         string
	SweptAt      string
	Removed      int64
	RemovedTotal int64
	Kept         int64
	Unaccounted  int64
	ForeignNames int64
	Error        string
}

type ForceDestroy struct {
	Generation          int64
	AdmissionGeneration int64
	State               string
	Reason              string
	Actor               string
	RequestedAt         string
	CompletedAt         string
}

type IssuedCert struct {
	Serial   string
	Node     string
	Source   string
	NotAfter string
	IssuedAt string
}

type ListenerCapacity struct {
	Tier       string
	ObservedAt string
	Snapshot   string
}

type NodeEnrollment struct {
	Name        string
	Fingerprint string
	CsrPem      string
	CertPem     string
	State       string
	RequestedAt string
	DecidedAt   string
	Source      string
}

type PoolRunner struct {
	LeaseID            string
	Tier               string
	LaunchRequestID    int64
	RunnerID           int64
	RunnerName         string
	Status             string
	ActualRequestID    int64
	RunID              int64
	JobID              string
	SourceAcknowledged int64
	UpdatedAt          string
	JobOwner           string
	JobRepository      string
	JobWorkflowRef     string
	JobEvent           string
}

type RevokedCert struct {
	Serial    string
	Node      string
	Reason    string
	RevokedAt string
}

type Rollout struct {
	ID              string
	Generation      int64
	Channel         string
	TargetVersion   string
	TargetDigest    string
	Policy          string
	ControllerPhase string
	PriorVersion    string
	State           string
	CreatedBy       string
	CreatedAt       string
	FinishedAt      string
	TerminalReason  string
}
