// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const countLiveWorkOnNode = `-- name: CountLiveWorkOnNode :one
SELECT CAST(COUNT(*) AS BIGINT) FROM leases
 WHERE COALESCE(node, target_node) = CAST($1 AS TEXT)
   AND phase NOT IN ('done','failed')
   AND (phase IN ('launching','online','busy','custody','teardown','quarantine')
        OR expires_at > $2)
`

type CountLiveWorkOnNodeParams struct {
	Node string
	Now  string
}

// How much work on one host would be invalidated by a placement change.
//
// STRICTER THAN CountOutstandingLeasesOnNode: an escrow that has already expired
// holds no compute and is about to be reaped, so it must not block a host from
// correcting its own registration -- but anything past `launching` has compute
// behind it whatever its TTL says.
func (q *Queries) CountLiveWorkOnNode(ctx context.Context, arg CountLiveWorkOnNodeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveWorkOnNode, arg.Node, arg.Now)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOutstandingLeasesOnNode = `-- name: CountOutstandingLeasesOnNode :one
SELECT CAST(COUNT(*) AS BIGINT) FROM leases
 WHERE COALESCE(node, target_node) = CAST($1 AS TEXT) AND phase NOT IN ('done','failed')
`

// How many leases still charge capacity against one host.
//
// COALESCE(node, target_node), the way the rest of this package attributes a
// lease: an escrow AIMED at a machine has already committed that machine's room
// whether or not a container has started.
func (q *Queries) CountOutstandingLeasesOnNode(ctx context.Context, node string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOutstandingLeasesOnNode, node)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const decommissionNode = `-- name: DecommissionNode :exec
UPDATE nodes
   SET decommissioned_at = $1, decommission_proven = $2,
       decommission_actor = $3, drained = 1, live = 0
 WHERE name = $4
`

type DecommissionNodeParams struct {
	DecommissionedAt   string
	DecommissionProven int64
	DecommissionActor  string
	Name               string
}

// Stop expecting one host to answer.
//
// decommission_proven RECORDS WHETHER ANYTHING PROVED IT WAS IDLE, and a forced
// exclusion writes 0 rather than being omitted: an exclusion that cannot be told
// from a proof is the whole membership rule defeated. `drained = 1` is what both
// placement queries and the floor arithmetic already read.
func (q *Queries) DecommissionNode(ctx context.Context, arg DecommissionNodeParams) error {
	_, err := q.db.ExecContext(ctx, decommissionNode,
		arg.DecommissionedAt,
		arg.DecommissionProven,
		arg.DecommissionActor,
		arg.Name,
	)
	return err
}

const deleteEveryNodeInventory = `-- name: DeleteEveryNodeInventory :exec
DELETE FROM node_inventory
`

// And forget what they last said they were running.
//
// A REPORT RECEIVED BY A PREVIOUS PROCESS SAYS NOTHING ABOUT NOW, and the node
// epoch does NOT move on a plane restart -- so without this the record would
// survive with a matching epoch and read as current to everything that consults
// it.
func (q *Queries) DeleteEveryNodeInventory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteEveryNodeInventory)
	return err
}

const fleetClaimHolder = `-- name: FleetClaimHolder :one
SELECT name FROM nodes
 WHERE codebuild_fleet = $1 AND name <> $2
   AND (decommissioned_at = '' OR decommission_proven = 0)
 ORDER BY name
 LIMIT 1
`

type FleetClaimHolderParams struct {
	Fleet string
	Name  string
}

// Another host that still claims one reserved CodeBuild fleet.
//
// A RESERVED FLEET IS ONE SHARED POOL, so two nodes naming it each register its
// whole capacity and the deployment promises GitHub more concurrent jobs than AWS
// will run. Only the control plane can see that, because the two config files are
// on two machines.
//
// WHAT RELEASES A CLAIM IS decommission_proven = 1, NOT LIVENESS AND NOT AN
// EXCLUSION. Liveness says nothing about remote compute -- a control plane start
// marks every host not-live while its builds keep running -- and `--force`
// records decommission_proven = 0 precisely because nothing could be asked. The
// ordinary replacement needs none of this because it reuses the node NAME, which
// the `name <> @name` clause excludes.
func (q *Queries) FleetClaimHolder(ctx context.Context, arg FleetClaimHolderParams) (string, error) {
	row := q.db.QueryRowContext(ctx, fleetClaimHolder, arg.Fleet, arg.Name)
	var name string
	err := row.Scan(&name)
	return name, err
}

const forgetEveryNode = `-- name: ForgetEveryNode :exec
UPDATE nodes SET live = 0
`

// Mark the whole fleet unreachable, which is what a control-plane start knows.
//
// IT REMOVES NOTHING. A node row is the durable placement identity of a machine,
// and a plane that has just started has no judgement about any host -- not that
// the host is gone.
func (q *Queries) ForgetEveryNode(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetEveryNode)
	return err
}

const listCodeBuildRegistrationPaths = `-- name: ListCodeBuildRegistrationPaths :many
SELECT name, codebuild_region, codebuild_jit_path, decommissioned_at
  FROM nodes
 WHERE provider = $1
 ORDER BY name
`

type ListCodeBuildRegistrationPathsRow struct {
	Name             string
	CodebuildRegion  string
	CodebuildJitPath string
	DecommissionedAt string
}

// Every codebuild host and the Parameter Store path it stages registrations under.
//
// DECOMMISSIONED HOSTS INCLUDED, deliberately. The control plane sweeps these paths
// for registrations a dead node never removed, and a host that has been taken out
// of the fleet is exactly the one with nobody left to clean up after it. Rows with
// an empty path are included too: a host that registered before it could name its
// path is one `billet status` has to NAME as unswept rather than count as clean.
//
// The provider is a parameter rather than a literal, so there is no second
// spelling of the backend name to drift.
func (q *Queries) ListCodeBuildRegistrationPaths(ctx context.Context, provider string) ([]ListCodeBuildRegistrationPathsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCodeBuildRegistrationPaths, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCodeBuildRegistrationPathsRow
	for rows.Next() {
		var i ListCodeBuildRegistrationPathsRow
		if err := rows.Scan(
			&i.Name,
			&i.CodebuildRegion,
			&i.CodebuildJitPath,
			&i.DecommissionedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeWireVersions = `-- name: ListNodeWireVersions :many
SELECT name, live, node_release, wire_min, wire_max, wire_version, epoch,
       node_digest
  FROM nodes
 ORDER BY name
`

type ListNodeWireVersionsRow struct {
	Name        string
	Live        int64
	NodeRelease string
	WireMin     int64
	WireMax     int64
	WireVersion int64
	Epoch       int64
	NodeDigest  string
}

// What each host's registration said about its build, and what was negotiated.
func (q *Queries) ListNodeWireVersions(ctx context.Context) ([]ListNodeWireVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeWireVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeWireVersionsRow
	for rows.Next() {
		var i ListNodeWireVersionsRow
		if err := rows.Scan(
			&i.Name,
			&i.Live,
			&i.NodeRelease,
			&i.WireMin,
			&i.WireMax,
			&i.WireVersion,
			&i.Epoch,
			&i.NodeDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingRemoteShapes = `-- name: ListOutstandingRemoteShapes :many
SELECT COALESCE(l.node, l.target_node) AS node, l.instance_type,
       CAST(COUNT(*) AS BIGINT) AS outstanding
  FROM leases l
  JOIN nodes n ON n.name = COALESCE(l.node, l.target_node)
 WHERE n.provider IN ('ec2','codebuild') AND l.phase NOT IN ('done','failed')
 GROUP BY COALESCE(l.node, l.target_node), l.instance_type
`

type ListOutstandingRemoteShapesRow struct {
	Node         sql.NullString
	InstanceType string
	Outstanding  int64
}

// What each remote host currently has running, by the shape it was charged for.
//
// THE SHAPE, NOT THE TIER REQUEST. A remote lease is charged for the instance
// placement actually bought, so a cost report keyed on anything else understates
// a fallback. Same pinned provider list as ListRemoteCostNodes.
func (q *Queries) ListOutstandingRemoteShapes(ctx context.Context) ([]ListOutstandingRemoteShapesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutstandingRemoteShapes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutstandingRemoteShapesRow
	for rows.Next() {
		var i ListOutstandingRemoteShapesRow
		if err := rows.Scan(&i.Node, &i.InstanceType, &i.Outstanding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceableNodes = `-- name: ListPlaceableNodes :many
SELECT name, provider, site, total_vcpu, total_memory, ec2_shapes
  FROM nodes
 WHERE live = 1 AND drained = 0
 ORDER BY name
`

type ListPlaceableNodesRow struct {
	Name        string
	Provider    string
	Site        string
	TotalVcpu   int64
	TotalMemory int64
	Ec2Shapes   string
}

// The hosts a lease may be placed on at all.
//
// ORDERED BY NAME, because Go map iteration is not and this list decides
// placement: an unordered candidate set makes the same fleet produce different
// answers on different runs, which is untestable and unexplainable in a log.
//
// ONE STATEMENT FOR BOTH READERS. eligibleNodes filters it down to a tier's
// acceptable providers in Go and liveNodes takes the whole fleet, because a
// floor belonging to one tier is held on the hosts THAT tier could use and the
// asking tier may not share them -- so the two differ in what they do with the
// rows, never in which rows exist.
//
// `drained = 0` IS REDUNDANT WITH `live = 1` IN EVERY STATE REACHABLE TODAY, and
// that is said here rather than left for somebody to discover: a decommission
// writes drained = 1 and live = 0 together, and a re-registration clears both
// together, so no API path produces a live host that is drained. Measured --
// deleting either half of this predicate fails no test in internal/alloc, while
// deleting `live = 1` alone does. It stays because the two columns answer
// different questions (can this host be reached, and does anybody still expect
// it to serve), and the next path that sets liveness without going through
// registration must not silently start placing work on an excluded host.
func (q *Queries) ListPlaceableNodes(ctx context.Context) ([]ListPlaceableNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaceableNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaceableNodesRow
	for rows.Next() {
		var i ListPlaceableNodesRow
		if err := rows.Scan(
			&i.Name,
			&i.Provider,
			&i.Site,
			&i.TotalVcpu,
			&i.TotalMemory,
			&i.Ec2Shapes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegisteredNodes = `-- name: ListRegisteredNodes :many

SELECT name, provider, site, live,
       decommissioned_at, decommission_proven, decommission_actor
  FROM nodes
 ORDER BY name
`

type ListRegisteredNodesRow struct {
	Name               string
	Provider           string
	Site               string
	Live               int64
	DecommissionedAt   string
	DecommissionProven int64
	DecommissionActor  string
}

// Registered hosts: the durable placement identity of one compute machine.
//
// A NODE ROW OUTLIVES THE HOST'S CONNECTION. `live` is this control plane's
// judgement and is cleared for the whole fleet whenever one starts, so nothing
// here may read an absent or not-live host as a host that is gone. What removes
// a machine from the set a drain expects to hear from is a decommission, and
// `drained` is the column that records it.
// Every host the deployment has recorded, offline ones included.
func (q *Queries) ListRegisteredNodes(ctx context.Context) ([]ListRegisteredNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRegisteredNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegisteredNodesRow
	for rows.Next() {
		var i ListRegisteredNodesRow
		if err := rows.Scan(
			&i.Name,
			&i.Provider,
			&i.Site,
			&i.Live,
			&i.DecommissionedAt,
			&i.DecommissionProven,
			&i.DecommissionActor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemoteCostNodes = `-- name: ListRemoteCostNodes :many
SELECT name, provider, total_vcpu, total_memory, ec2_shapes
  FROM nodes
 WHERE provider IN ('ec2','codebuild')
 ORDER BY name
`

type ListRemoteCostNodesRow struct {
	Name        string
	Provider    string
	TotalVcpu   int64
	TotalMemory int64
	Ec2Shapes   string
}

// Every host whose compute is bought rather than owned.
//
// THE PROVIDER LIST IS A LITERAL AND IT IS PINNED. sqlc.slice() is not available
// on SQLite, so this cannot take config.RemoteProviders() as a bound list --
// and a literal that drifts from that function is a backend whose cost stops
// being reported at all, which reads as a fleet that costs nothing.
// TestTheRemoteProviderListMatchesTheQueries is what keeps the two the same.
func (q *Queries) ListRemoteCostNodes(ctx context.Context) ([]ListRemoteCostNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRemoteCostNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRemoteCostNodesRow
	for rows.Next() {
		var i ListRemoteCostNodesRow
		if err := rows.Scan(
			&i.Name,
			&i.Provider,
			&i.TotalVcpu,
			&i.TotalMemory,
			&i.Ec2Shapes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeNotLive = `-- name: MarkNodeNotLive :exec
UPDATE nodes SET live = 0 WHERE name = $1 AND epoch = $2
`

type MarkNodeNotLiveParams struct {
	Name  string
	Epoch int64
}

// Record that the control plane has given up on one host.
//
// FENCED ON THE EPOCH. Registration commits to the ledger BEFORE it takes the
// plane's mutex, and expiry holds that mutex while dropping the old entry -- so a
// host that restarts quickly could commit its new registration and then be marked
// dead by the expiry of the incarnation it replaced. A no-op once the epoch has
// moved, which is the point.
func (q *Queries) MarkNodeNotLive(ctx context.Context, arg MarkNodeNotLiveParams) error {
	_, err := q.db.ExecContext(ctx, markNodeNotLive, arg.Name, arg.Epoch)
	return err
}

const readLeaseTargetSize = `-- name: ReadLeaseTargetSize :one
SELECT l.target_node, l.vcpu, l.memory, n.live
  FROM leases l LEFT JOIN nodes n ON n.name = l.target_node
 WHERE l.id = $1
`

type ReadLeaseTargetSizeRow struct {
	TargetNode sql.NullString
	Vcpu       int64
	Memory     int64
	Live       sql.NullInt64
}

// One lease's target host, its cost, and whether that host is reachable.
//
// LEFT JOIN, because a target naming a host the ledger has never heard of is the
// same situation as one it has forgotten: there is nowhere for that reservation
// to go, and an inner join would report the lease as absent instead.
func (q *Queries) ReadLeaseTargetSize(ctx context.Context, id string) (ReadLeaseTargetSizeRow, error) {
	row := q.db.QueryRowContext(ctx, readLeaseTargetSize, id)
	var i ReadLeaseTargetSizeRow
	err := row.Scan(
		&i.TargetNode,
		&i.Vcpu,
		&i.Memory,
		&i.Live,
	)
	return i, err
}

const readNodeCapacity = `-- name: ReadNodeCapacity :one
SELECT total_vcpu, total_memory, ec2_shapes FROM nodes WHERE name = $1
`

type ReadNodeCapacityRow struct {
	TotalVcpu   int64
	TotalMemory int64
	Ec2Shapes   string
}

// What one host has, and the shapes it can buy.
func (q *Queries) ReadNodeCapacity(ctx context.Context, name string) (ReadNodeCapacityRow, error) {
	row := q.db.QueryRowContext(ctx, readNodeCapacity, name)
	var i ReadNodeCapacityRow
	err := row.Scan(&i.TotalVcpu, &i.TotalMemory, &i.Ec2Shapes)
	return i, err
}

const readNodeEpoch = `-- name: ReadNodeEpoch :one
SELECT epoch FROM nodes WHERE name = $1
`

// One host's registration fence.
//
// A REGISTRATION BUMPS IT AND NOTHING ELSE DOES, so a value that has not moved
// proves the answer is about the same incarnation the caller was talking to.
// sql.ErrNoRows means the host is not in the fleet, which is not the same as a
// host whose epoch has moved and must not be reported as one.
func (q *Queries) ReadNodeEpoch(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, readNodeEpoch, name)
	var epoch int64
	err := row.Scan(&epoch)
	return epoch, err
}

const readNodeIncarnation = `-- name: ReadNodeIncarnation :one
SELECT incarnation FROM nodes WHERE name = $1
`

// The process one host presented at its current registration, or ” for a host
// that never presented one.
//
// THE DURABLE NAME OF A PROCESS, which the epoch is not: the epoch moves on
// every registration and the same process registers again after a
// control-plane restart. A lease records this at Bind and on entry to custody
// or teardown, so a report can say whether the process holding it is the one
// the host runs now. sql.ErrNoRows means the host is not in the fleet.
func (q *Queries) ReadNodeIncarnation(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, readNodeIncarnation, name)
	var incarnation string
	err := row.Scan(&incarnation)
	return incarnation, err
}

const readNodeLiveness = `-- name: ReadNodeLiveness :one
SELECT live FROM nodes WHERE name = $1
`

// Whether the deployment can currently reach one host.
//
// sql.ErrNoRows means the host was never registered, which the caller reports
// differently from a host that is simply not answering.
func (q *Queries) ReadNodeLiveness(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, readNodeLiveness, name)
	var live int64
	err := row.Scan(&live)
	return live, err
}

const readNodeProvider = `-- name: ReadNodeProvider :one
SELECT provider FROM nodes WHERE name = $1
`

// The backend one host reported at registration.
//
// THE REGISTERED ONE, NEVER A CATALOGUE'S CLAIM. Placement asks whether a lease's
// acceptable backends include what the machine itself said it runs; a firecracker
// lease cannot run on a Tart host whatever the config says.
func (q *Queries) ReadNodeProvider(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, readNodeProvider, name)
	var provider string
	err := row.Scan(&provider)
	return provider, err
}

const readNodeRegistration = `-- name: ReadNodeRegistration :one
SELECT provider, site, ec2_shapes, codebuild_fleet FROM nodes WHERE name = $1
`

type ReadNodeRegistrationRow struct {
	Provider       string
	Site           string
	Ec2Shapes      string
	CodebuildFleet string
}

// The facts a re-registration has to be checked against.
func (q *Queries) ReadNodeRegistration(ctx context.Context, name string) (ReadNodeRegistrationRow, error) {
	row := q.db.QueryRowContext(ctx, readNodeRegistration, name)
	var i ReadNodeRegistrationRow
	err := row.Scan(
		&i.Provider,
		&i.Site,
		&i.Ec2Shapes,
		&i.CodebuildFleet,
	)
	return i, err
}

const readNodeSize = `-- name: ReadNodeSize :one
SELECT total_vcpu, total_memory FROM nodes WHERE name = $1
`

type ReadNodeSizeRow struct {
	TotalVcpu   int64
	TotalMemory int64
}

// What one host says it has.
func (q *Queries) ReadNodeSize(ctx context.Context, name string) (ReadNodeSizeRow, error) {
	row := q.db.QueryRowContext(ctx, readNodeSize, name)
	var i ReadNodeSizeRow
	err := row.Scan(&i.TotalVcpu, &i.TotalMemory)
	return i, err
}

const upsertNodeRegistration = `-- name: UpsertNodeRegistration :one
INSERT INTO nodes
   (name, provider, site, total_vcpu, total_memory, ec2_shapes, last_seen_at, live,
    node_release, wire_min, wire_max, wire_version, node_digest, codebuild_fleet,
    codebuild_jit_path, codebuild_region, incarnation, epoch)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1,
        $8, $9, $10, $11, $12,
        $13, $14, $15, $16, 1)
ON CONFLICT (name) DO UPDATE SET
   provider     = excluded.provider,
   site         = excluded.site,
   total_vcpu   = excluded.total_vcpu,
   total_memory = excluded.total_memory,
   ec2_shapes   = excluded.ec2_shapes,
   last_seen_at = excluded.last_seen_at,
   live         = 1,
   node_release = excluded.node_release,
   wire_min     = excluded.wire_min,
   wire_max     = excluded.wire_max,
   wire_version = excluded.wire_version,
   node_digest  = excluded.node_digest,
   codebuild_fleet = excluded.codebuild_fleet,
   codebuild_jit_path = excluded.codebuild_jit_path,
   codebuild_region   = excluded.codebuild_region,
   incarnation  = excluded.incarnation,
   epoch        = nodes.epoch + 1,
   decommissioned_at   = '',
   decommission_proven = 0,
   decommission_actor  = '',
   drained             = 0
RETURNING epoch
`

type UpsertNodeRegistrationParams struct {
	Name             string
	Provider         string
	Site             string
	TotalVcpu        int64
	TotalMemory      int64
	Ec2Shapes        string
	LastSeenAt       string
	NodeRelease      string
	WireMin          int64
	WireMax          int64
	WireVersion      int64
	NodeDigest       string
	CodebuildFleet   string
	CodebuildJitPath string
	CodebuildRegion  string
	Incarnation      string
}

// Register a host, or re-register one, and return its new fence.
//
// THE EPOCH ALWAYS MOVES, which is what makes it the fleet's one causal signal: a
// registration is the only thing that bumps it, so a value that has not changed
// proves an answer is about the same incarnation.
//
// A HOST THAT COMES BACK IS A MEMBER AGAIN. A decommission is a person asserting
// a machine is gone; the machine registering is that assertion being contradicted
// by the machine itself, and an exclusion nobody remembers would hide a live host
// from every later drain forever. `drained` is cleared with it, because that is
// the column placement and the floor arithmetic read.
func (q *Queries) UpsertNodeRegistration(ctx context.Context, arg UpsertNodeRegistrationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertNodeRegistration,
		arg.Name,
		arg.Provider,
		arg.Site,
		arg.TotalVcpu,
		arg.TotalMemory,
		arg.Ec2Shapes,
		arg.LastSeenAt,
		arg.NodeRelease,
		arg.WireMin,
		arg.WireMax,
		arg.WireVersion,
		arg.NodeDigest,
		arg.CodebuildFleet,
		arg.CodebuildJitPath,
		arg.CodebuildRegion,
		arg.Incarnation,
	)
	var epoch int64
	err := row.Scan(&epoch)
	return epoch, err
}

const usageByNode = `-- name: UsageByNode :many
SELECT COALESCE(node, target_node, '') AS node,
       CAST(COALESCE(SUM(vcpu), 0) AS BIGINT) AS vcpu,
       CAST(COALESCE(SUM(memory), 0) AS BIGINT) AS memory,
       CAST(COALESCE(SUM(macos_slot), 0) AS BIGINT) AS macos_slots
  FROM leases
 WHERE phase NOT IN ('done','failed')
 GROUP BY COALESCE(node, target_node, '')
`

type UsageByNodeRow struct {
	Node       string
	Vcpu       int64
	Memory     int64
	MacosSlots int64
}

// Every host's committed capacity, keyed the way a lease is attributed.
func (q *Queries) UsageByNode(ctx context.Context) ([]UsageByNodeRow, error) {
	rows, err := q.db.QueryContext(ctx, usageByNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageByNodeRow
	for rows.Next() {
		var i UsageByNodeRow
		if err := rows.Scan(
			&i.Node,
			&i.Vcpu,
			&i.Memory,
			&i.MacosSlots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageOnNode = `-- name: UsageOnNode :one
SELECT CAST(COALESCE(SUM(vcpu), 0) AS BIGINT) AS vcpu,
       CAST(COALESCE(SUM(memory), 0) AS BIGINT) AS memory,
       CAST(COUNT(*) AS BIGINT) AS leases
  FROM leases
 WHERE phase NOT IN ('done','failed')
   AND COALESCE(node, target_node) = CAST($1 AS TEXT)
`

type UsageOnNodeRow struct {
	Vcpu   int64
	Memory int64
	Leases int64
}

// One host's committed capacity.
func (q *Queries) UsageOnNode(ctx context.Context, node string) (UsageOnNodeRow, error) {
	row := q.db.QueryRowContext(ctx, usageOnNode, node)
	var i UsageOnNodeRow
	err := row.Scan(&i.Vcpu, &i.Memory, &i.Leases)
	return i, err
}

const withdrawNode = `-- name: WithdrawNode :execrows
UPDATE nodes SET live = 0
 WHERE name = $1 AND epoch = $2 AND incarnation = $3
`

type WithdrawNodeParams struct {
	Name        string
	Epoch       int64
	Incarnation string
}

// Record that one host said it is leaving, and take it out of placement.
//
// FENCED ON THE EPOCH AND THE INCARNATION, and both are needed. The epoch is the
// registration fence -- a withdrawal that arrives after the host has registered
// again matches nothing -- and the incarnation is the durable name of the
// PROCESS, so a superseded process that still holds the certificate cannot take
// its replacement out of the fleet. Zero rows is the caller's answer that the
// fence moved.
//
// ONLY `live`. A withdrawal is not a decommission (drained, decommissioned_at
// and the proof columns are untouched), releases no lease, and leaves the
// host's inventory and barrier run alone -- the next registration discards
// those, exactly as it does after silence. What changes is that ListPlaceableNodes
// stops offering the host at once instead of after the silence window.
func (q *Queries) WithdrawNode(ctx context.Context, arg WithdrawNodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, withdrawNode, arg.Name, arg.Epoch, arg.Incarnation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
