// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poolrunners.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const acknowledgePoolRunnerSource = `-- name: AcknowledgePoolRunnerSource :exec
UPDATE pool_runners SET source_acknowledged = 1, updated_at = $1
 WHERE lease_id = $2
`

type AcknowledgePoolRunnerSourceParams struct {
	UpdatedAt string
	LeaseID   string
}

// Record that GitHub cannot redeliver the completion that used this member.
func (q *Queries) AcknowledgePoolRunnerSource(ctx context.Context, arg AcknowledgePoolRunnerSourceParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgePoolRunnerSource, arg.UpdatedAt, arg.LeaseID)
	return err
}

const bindPoolRunnerJob = `-- name: BindPoolRunnerJob :exec
UPDATE pool_runners
   SET actual_request_id = $1, run_id = $2, job_id = $3,
       updated_at = $4
 WHERE lease_id = $5
`

type BindPoolRunnerJobParams struct {
	ActualRequestID int64
	RunID           int64
	JobID           string
	UpdatedAt       string
	LeaseID         string
}

// Fill in the job a recovered busy member turned out to be running.
//
// IT DOES NOT TOUCH status OR runner_id, and the reason is narrower than it
// looks: the caller reads the row and reaches this in ONE transaction, so a
// status written here could not differ from the one it just read. What the
// narrow projection buys is that the statement cannot be reused, later, on a
// path that has not established the member is busy -- measured, adding
// `status = 'busy'` here changes no observable behaviour today.
func (q *Queries) BindPoolRunnerJob(ctx context.Context, arg BindPoolRunnerJobParams) error {
	_, err := q.db.ExecContext(ctx, bindPoolRunnerJob,
		arg.ActualRequestID,
		arg.RunID,
		arg.JobID,
		arg.UpdatedAt,
		arg.LeaseID,
	)
	return err
}

const claimPoolRunnerForRetirement = `-- name: ClaimPoolRunnerForRetirement :execresult
UPDATE pool_runners SET status = 'retiring', updated_at = $1
 WHERE lease_id = $2 AND status IN ('idle','busy')
`

type ClaimPoolRunnerForRetirementParams struct {
	UpdatedAt string
	LeaseID   string
}

// Claim a member for teardown, refusing one that is already past it.
//
// THE STATUS FILTER IS THE CLAIM, so this is :execresult: zero rows affected is
// how the caller learns the member was already retiring, retired, or gone, and
// it then reads the row to say which. An :exec could not tell those apart.
func (q *Queries) ClaimPoolRunnerForRetirement(ctx context.Context, arg ClaimPoolRunnerForRetirementParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimPoolRunnerForRetirement, arg.UpdatedAt, arg.LeaseID)
}

const deletePoolRunner = `-- name: DeletePoolRunner :exec
DELETE FROM pool_runners WHERE lease_id = $1
`

// Forget the settlement metadata, after compute and capacity are both gone.
func (q *Queries) DeletePoolRunner(ctx context.Context, leaseID string) error {
	_, err := q.db.ExecContext(ctx, deletePoolRunner, leaseID)
	return err
}

const insertPoolRunner = `-- name: InsertPoolRunner :exec

INSERT INTO pool_runners
     (lease_id, tier, launch_request_id, runner_id, runner_name, status, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7)
`

type InsertPoolRunnerParams struct {
	LeaseID         string
	Tier            string
	LaunchRequestID int64
	RunnerID        int64
	RunnerName      string
	Status          string
	UpdatedAt       string
}

// Pool runners: one GitHub registration backed by one compute lease.
//
// A SCALE-SET RUNNER IS A POOL MEMBER, NOT THE JOB THAT CAUSED SCALE-UP, and
// this table is where that distinction is made durable. launch_request_id is the
// request billet launched for; actual_request_id, run_id and job_id are the job
// GitHub's own JobStarted says the runner actually consumed. Those two are
// routinely different, and the second set is authoritative about the compute.
//
// THE PROJECTIONS INCLUDE updated_at, which nothing reads, and that is
// deliberate: selecting exactly the table's columns in exactly its order makes
// sqlc return the model struct, so all three reads share one type and one
// mapping function rather than three Row types that must be kept identical.
// Record one pool member.
//
// THE STATUS IS A PARAMETER because a member is journaled at three different
// points: idle when billet registers what it launched, busy when recovery finds
// a legacy registration GitHub says is working, and retiring when recovery is
// claiming one for teardown and no row existed. The table's CHECK is what keeps
// the vocabulary closed.
func (q *Queries) InsertPoolRunner(ctx context.Context, arg InsertPoolRunnerParams) error {
	_, err := q.db.ExecContext(ctx, insertPoolRunner,
		arg.LeaseID,
		arg.Tier,
		arg.LaunchRequestID,
		arg.RunnerID,
		arg.RunnerName,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const listPoolRunnersInTier = `-- name: ListPoolRunnersInTier :many
SELECT lease_id, tier, launch_request_id, runner_id, runner_name, status,
       actual_request_id, run_id, job_id, source_acknowledged, updated_at
  FROM pool_runners WHERE tier = $1 ORDER BY updated_at, lease_id
`

// Every durable member of one tier's GitHub runner pool.
func (q *Queries) ListPoolRunnersInTier(ctx context.Context, tier string) ([]PoolRunner, error) {
	rows, err := q.db.QueryContext(ctx, listPoolRunnersInTier, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolRunner
	for rows.Next() {
		var i PoolRunner
		if err := rows.Scan(
			&i.LeaseID,
			&i.Tier,
			&i.LaunchRequestID,
			&i.RunnerID,
			&i.RunnerName,
			&i.Status,
			&i.ActualRequestID,
			&i.RunID,
			&i.JobID,
			&i.SourceAcknowledged,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPoolRunnerBusy = `-- name: MarkPoolRunnerBusy :exec
UPDATE pool_runners
   SET runner_id = $1, status = 'busy', updated_at = $2
 WHERE lease_id = $3
`

type MarkPoolRunnerBusyParams struct {
	RunnerID  int64
	UpdatedAt string
	LeaseID   string
}

// Journal a recovered legacy registration as working, without a job identity.
//
// THE EMPTY JOB FIELDS ARE A RESERVATION FOR THIS EXACT PHYSICAL RUNNER, not a
// competing binding, which is why they are left alone rather than zeroed: a
// delayed JobStarted fills them through BindPoolRunnerJob.
func (q *Queries) MarkPoolRunnerBusy(ctx context.Context, arg MarkPoolRunnerBusyParams) error {
	_, err := q.db.ExecContext(ctx, markPoolRunnerBusy, arg.RunnerID, arg.UpdatedAt, arg.LeaseID)
	return err
}

const markPoolRunnerRetired = `-- name: MarkPoolRunnerRetired :exec
UPDATE pool_runners SET status = 'retired', updated_at = $1
 WHERE lease_id = $2
`

type MarkPoolRunnerRetiredParams struct {
	UpdatedAt string
	LeaseID   string
}

// Record that compute settled while GitHub may still redeliver the completion.
//
// THE ROW SURVIVES, which is the point: a redelivery must resolve to the same
// compute even after teardown and capacity release have both completed.
func (q *Queries) MarkPoolRunnerRetired(ctx context.Context, arg MarkPoolRunnerRetiredParams) error {
	_, err := q.db.ExecContext(ctx, markPoolRunnerRetired, arg.UpdatedAt, arg.LeaseID)
	return err
}

const markPoolRunnerRetiring = `-- name: MarkPoolRunnerRetiring :exec
UPDATE pool_runners SET status = 'retiring', updated_at = $1
 WHERE lease_id = $2
`

type MarkPoolRunnerRetiringParams struct {
	UpdatedAt string
	LeaseID   string
}

// Claim a member for teardown, having already decided it may be claimed.
func (q *Queries) MarkPoolRunnerRetiring(ctx context.Context, arg MarkPoolRunnerRetiringParams) error {
	_, err := q.db.ExecContext(ctx, markPoolRunnerRetiring, arg.UpdatedAt, arg.LeaseID)
	return err
}

const readPoolRunnerByLease = `-- name: ReadPoolRunnerByLease :one
SELECT lease_id, tier, launch_request_id, runner_id, runner_name, status,
       actual_request_id, run_id, job_id, source_acknowledged, updated_at
  FROM pool_runners WHERE lease_id = $1
`

// The pool member backed by one lease.
//
// THE COMPUTE AUTHORITY WHEN NO MESSAGE CARRIES A RUNNER NAME. Read inside the
// write transaction by every mutation below, against the row that write acts on.
func (q *Queries) ReadPoolRunnerByLease(ctx context.Context, leaseID string) (PoolRunner, error) {
	row := q.db.QueryRowContext(ctx, readPoolRunnerByLease, leaseID)
	var i PoolRunner
	err := row.Scan(
		&i.LeaseID,
		&i.Tier,
		&i.LaunchRequestID,
		&i.RunnerID,
		&i.RunnerName,
		&i.Status,
		&i.ActualRequestID,
		&i.RunID,
		&i.JobID,
		&i.SourceAcknowledged,
		&i.UpdatedAt,
	)
	return i, err
}

const readPoolRunnerByName = `-- name: ReadPoolRunnerByName :one
SELECT lease_id, tier, launch_request_id, runner_id, runner_name, status,
       actual_request_id, run_id, job_id, source_acknowledged, updated_at
  FROM pool_runners WHERE runner_name = $1
`

// GitHub's runner identity resolved to billet's compute lease.
func (q *Queries) ReadPoolRunnerByName(ctx context.Context, runnerName string) (PoolRunner, error) {
	row := q.db.QueryRowContext(ctx, readPoolRunnerByName, runnerName)
	var i PoolRunner
	err := row.Scan(
		&i.LeaseID,
		&i.Tier,
		&i.LaunchRequestID,
		&i.RunnerID,
		&i.RunnerName,
		&i.Status,
		&i.ActualRequestID,
		&i.RunID,
		&i.JobID,
		&i.SourceAcknowledged,
		&i.UpdatedAt,
	)
	return i, err
}

const readPoolRunnerSettlementByRequest = `-- name: ReadPoolRunnerSettlementByRequest :one
SELECT lease_id, status, source_acknowledged FROM pool_runners
 WHERE tier = $1 AND launch_request_id = $2
`

type ReadPoolRunnerSettlementByRequestParams struct {
	Tier            string
	LaunchRequestID int64
}

type ReadPoolRunnerSettlementByRequestRow struct {
	LeaseID            string
	Status             string
	SourceAcknowledged int64
}

// What settling one launch request needs to know.
//
// ONE STATEMENT FOR BOTH SETTLEMENT PATHS. A completion settles the physical
// runner and an acknowledgement records that GitHub cannot redeliver; each reads
// two of these three columns, and splitting them into two queries would be two
// statements that must agree about how a request identifies a member.
func (q *Queries) ReadPoolRunnerSettlementByRequest(ctx context.Context, arg ReadPoolRunnerSettlementByRequestParams) (ReadPoolRunnerSettlementByRequestRow, error) {
	row := q.db.QueryRowContext(ctx, readPoolRunnerSettlementByRequest, arg.Tier, arg.LaunchRequestID)
	var i ReadPoolRunnerSettlementByRequestRow
	err := row.Scan(&i.LeaseID, &i.Status, &i.SourceAcknowledged)
	return i, err
}

const startPoolRunner = `-- name: StartPoolRunner :exec
UPDATE pool_runners
   SET runner_id = $1, status = 'busy', actual_request_id = $2,
       run_id = $3, job_id = $4, updated_at = $5
 WHERE lease_id = $6
`

type StartPoolRunnerParams struct {
	RunnerID        int64
	ActualRequestID int64
	RunID           int64
	JobID           string
	UpdatedAt       string
	LeaseID         string
}

// Bind an idle member to the job GitHub gave it.
func (q *Queries) StartPoolRunner(ctx context.Context, arg StartPoolRunnerParams) error {
	_, err := q.db.ExecContext(ctx, startPoolRunner,
		arg.RunnerID,
		arg.ActualRequestID,
		arg.RunID,
		arg.JobID,
		arg.UpdatedAt,
		arg.LeaseID,
	)
	return err
}
