// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quarantine.sql

package ledgerdb

import (
	"context"
	"database/sql"
)

const correctProvisionalHistory = `-- name: CorrectProvisionalHistory :exec
UPDATE job_history SET conclusion = $1, failure_reason = '' WHERE lease_id = $2
`

type CorrectProvisionalHistoryParams struct {
	Conclusion sql.NullString
	LeaseID    string
}

// The same correction, in the history row.
func (q *Queries) CorrectProvisionalHistory(ctx context.Context, arg CorrectProvisionalHistoryParams) error {
	_, err := q.db.ExecContext(ctx, correctProvisionalHistory, arg.Conclusion, arg.LeaseID)
	return err
}

const correctProvisionalLease = `-- name: CorrectProvisionalLease :exec
UPDATE leases SET phase = $1, failure_reason = '' WHERE id = $2
`

type CorrectProvisionalLeaseParams struct {
	Phase string
	ID    string
}

// Replace inventory's provisional verdict with GitHub's own.
//
// ONLY INVENTORY'S PROVISIONAL VERDICT MAY BE CORRECTED, which the caller checks
// by comparing failure_reason: an operator or a node can independently fail a
// quarantined lease at a later epoch too, so epoch order is a fence and never
// provenance.
func (q *Queries) CorrectProvisionalLease(ctx context.Context, arg CorrectProvisionalLeaseParams) error {
	_, err := q.db.ExecContext(ctx, correctProvisionalLease, arg.Phase, arg.ID)
	return err
}

const expireLease = `-- name: ExpireLease :exec
UPDATE leases SET expires_at = $1 WHERE id = $2
`

type ExpireLeaseParams struct {
	ExpiresAt string
	ID        string
}

// Move a lease's expiry, which is how a test drives the real reaper.
func (q *Queries) ExpireLease(ctx context.Context, arg ExpireLeaseParams) error {
	_, err := q.db.ExecContext(ctx, expireLease, arg.ExpiresAt, arg.ID)
	return err
}

const fenceQuarantinedLease = `-- name: FenceQuarantinedLease :exec
UPDATE leases SET phase = $1, epoch = epoch + 1 WHERE id = $2 AND epoch = $3
`

type FenceQuarantinedLeaseParams struct {
	Phase string
	ID    string
	Epoch int64
}

// Settle a quarantined lease, refusing one whose epoch moved.
//
// THE EPOCH IS IN THE WHERE, unlike the two above: this is the operator's force
// path, which read the lease and then decided, so the write must not land on a
// row something else has since taken over.
func (q *Queries) FenceQuarantinedLease(ctx context.Context, arg FenceQuarantinedLeaseParams) error {
	_, err := q.db.ExecContext(ctx, fenceQuarantinedLease, arg.Phase, arg.ID, arg.Epoch)
	return err
}

const listHeldLeases = `-- name: ListHeldLeases :many

SELECT l.id, l.tier, COALESCE(l.node, l.target_node, '') AS node, l.phase, l.vcpu,
       l.memory, l.held_at, l.force_release, l.holder_incarnation,
       n.incarnation AS node_incarnation, n.live AS node_live,
       n.last_seen_at AS node_seen_at
  FROM leases l
  LEFT JOIN nodes n ON n.name = COALESCE(l.node, l.target_node)
 WHERE l.phase IN ($1, $2, $3)
 ORDER BY l.held_at, l.id
`

type ListHeldLeasesParams struct {
	Custody    string
	Teardown   string
	Quarantine string
}

type ListHeldLeasesRow struct {
	ID                string
	Tier              string
	Node              string
	Phase             string
	Vcpu              int64
	Memory            int64
	HeldAt            string
	ForceRelease      int64
	HolderIncarnation string
	NodeIncarnation   sql.NullString
	NodeLive          sql.NullInt64
	NodeSeenAt        sql.NullString
}

// Quarantine and custody: capacity held because compute could not be confirmed
// gone.
//
// NOTHING HERE FREES CAPACITY ON A TIMEOUT. A quarantined lease is released by a
// proof -- an inventory taken under the registration this deployment is talking
// to, a node reporting a destroy, or an operator asserting a machine is never
// coming back. Every statement that terminalizes one is fenced by something that
// postdates the observation it acts on.
//
// THE PHASES ARE PARAMETERS, NOT LITERALS. They are Go constants and passing them
// means there is no second spelling of the vocabulary to drift from.
// Every operator-visible proof obligation, oldest first.
//
// WITH ITS HOST'S CURRENT PROCESS BESIDE THE HOLDER'S, so the report can say
// whether the process that took the obligation is the one the deployment talks
// to now. LEFT JOIN, because a lease may name a host the ledger has never
// registered, and that lease is held all the same.
func (q *Queries) ListHeldLeases(ctx context.Context, arg ListHeldLeasesParams) ([]ListHeldLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listHeldLeases, arg.Custody, arg.Teardown, arg.Quarantine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeldLeasesRow
	for rows.Next() {
		var i ListHeldLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Tier,
			&i.Node,
			&i.Phase,
			&i.Vcpu,
			&i.Memory,
			&i.HeldAt,
			&i.ForceRelease,
			&i.HolderIncarnation,
			&i.NodeIncarnation,
			&i.NodeLive,
			&i.NodeSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInventories = `-- name: ListNodeInventories :many
SELECT n.name, n.live, n.epoch, i.node_epoch, i.running, i.received_at
  FROM nodes n
  LEFT JOIN node_inventory i ON i.node = n.name
 ORDER BY n.name
`

type ListNodeInventoriesRow struct {
	Name       string
	Live       int64
	Epoch      int64
	NodeEpoch  sql.NullInt64
	Running    sql.NullInt64
	ReceivedAt sql.NullString
}

// What every known host last said it was running.
//
// NULLABLE RATHER THAN COALESCED TO A SENTINEL. A host with no row and a host
// reporting a number must not arrive as the same type, or the distinction has to
// be recovered by comparing against a magic value -- which is how an absent
// report becomes a zero somewhere downstream. The LEFT JOIN is what produces the
// nulls, and the caller compares i.node_epoch against n.epoch, because a report
// from before the host reconnected is not this host's current word.
func (q *Queries) ListNodeInventories(ctx context.Context) ([]ListNodeInventoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeInventories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeInventoriesRow
	for rows.Next() {
		var i ListNodeInventoriesRow
		if err := rows.Scan(
			&i.Name,
			&i.Live,
			&i.Epoch,
			&i.NodeEpoch,
			&i.Running,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuarantinedLeaseIDsOn = `-- name: ListQuarantinedLeaseIDsOn :many
SELECT id FROM leases
 WHERE phase = $1 AND COALESCE(node, target_node) = CAST($2 AS TEXT)
   AND (CAST($3 AS TEXT) = '' OR expires_at < CAST($3 AS TEXT))
`

type ListQuarantinedLeaseIDsOnParams struct {
	Phase   string
	Node    string
	Settled string
}

// The quarantined leases attributed to one host, optionally only those that
// expired before an instant.
//
// THE EMPTY SETTLED VALUE MEANS UNFILTERED, expressed in SQL rather than by
// building the statement two ways: a node asking which of its containers
// something is still waiting for must see EVERY quarantine, and a young one is
// exactly the one it must not destroy. A narrowing applied in one branch and
// forgotten in another is how that goes wrong.
func (q *Queries) ListQuarantinedLeaseIDsOn(ctx context.Context, arg ListQuarantinedLeaseIDsOnParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listQuarantinedLeaseIDsOn, arg.Phase, arg.Node, arg.Settled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuarantinedLeases = `-- name: ListQuarantinedLeases :many
SELECT id, tier, COALESCE(node, target_node, '') AS node, vcpu, memory, heartbeat_at
  FROM leases WHERE phase = $1 ORDER BY heartbeat_at
`

type ListQuarantinedLeasesRow struct {
	ID          string
	Tier        string
	Node        string
	Vcpu        int64
	Memory      int64
	HeartbeatAt string
}

// The leases holding capacity for compute nobody has accounted for, oldest
// first.
//
// WHAT AN OPERATOR LOOKS AT WHEN CAPACITY IS MISSING: a quarantined lease is the
// one thing that shrinks a fleet without anything having failed.
func (q *Queries) ListQuarantinedLeases(ctx context.Context, phase string) ([]ListQuarantinedLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuarantinedLeases, phase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuarantinedLeasesRow
	for rows.Next() {
		var i ListQuarantinedLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Tier,
			&i.Node,
			&i.Vcpu,
			&i.Memory,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningLeasesWithReplacedHolder = `-- name: ListRunningLeasesWithReplacedHolder :many
SELECT l.id, l.tier, COALESCE(l.node, l.target_node, '') AS node, l.phase, l.vcpu,
       l.memory, l.holder_incarnation, l.heartbeat_at,
       n.incarnation AS node_incarnation, n.live AS node_live,
       n.last_seen_at AS node_seen_at
  FROM leases l
  JOIN nodes n ON n.name = COALESCE(l.node, l.target_node)
 WHERE l.phase IN ($1, $2, $3)
   AND l.holder_incarnation <> '' AND n.incarnation <> ''
   AND n.incarnation <> l.holder_incarnation
 ORDER BY l.heartbeat_at, l.id
`

type ListRunningLeasesWithReplacedHolderParams struct {
	Launching string
	Online    string
	Busy      string
}

type ListRunningLeasesWithReplacedHolderRow struct {
	ID                string
	Tier              string
	Node              string
	Phase             string
	Vcpu              int64
	Memory            int64
	HolderIncarnation string
	HeartbeatAt       string
	NodeIncarnation   string
	NodeLive          int64
	NodeSeenAt        string
}

// Every lease in a running phase whose holding process is not the one its host
// registered with, oldest renewal first.
//
// THE SHAPE AN OPERATOR ONCE HAD NOTHING TO READ ABOUT: a completion bound to a
// process that died, its lease renewed by the listener and reported held by
// nobody. The process that was given the work is not the one this host's commands
// reach; the lease is still charged, and what settles it is its expiry and the
// host's inventory. INCARNATIONS, NOT EPOCHS: the epoch moves on every
// registration and the same process registers again after a control-plane
// restart, so comparing epochs would report every surviving lease as replaced
// after each one. An empty incarnation on either side was never recorded and is
// not compared.
func (q *Queries) ListRunningLeasesWithReplacedHolder(ctx context.Context, arg ListRunningLeasesWithReplacedHolderParams) ([]ListRunningLeasesWithReplacedHolderRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningLeasesWithReplacedHolder, arg.Launching, arg.Online, arg.Busy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningLeasesWithReplacedHolderRow
	for rows.Next() {
		var i ListRunningLeasesWithReplacedHolderRow
		if err := rows.Scan(
			&i.ID,
			&i.Tier,
			&i.Node,
			&i.Phase,
			&i.Vcpu,
			&i.Memory,
			&i.HolderIncarnation,
			&i.HeartbeatAt,
			&i.NodeIncarnation,
			&i.NodeLive,
			&i.NodeSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readLeaseSettlement = `-- name: ReadLeaseSettlement :one
SELECT phase, epoch, failure_reason FROM leases WHERE id = $1
`

type ReadLeaseSettlementRow struct {
	Phase         string
	Epoch         int64
	FailureReason string
}

// What settling one lease against a completion needs to know.
func (q *Queries) ReadLeaseSettlement(ctx context.Context, id string) (ReadLeaseSettlementRow, error) {
	row := q.db.QueryRowContext(ctx, readLeaseSettlement, id)
	var i ReadLeaseSettlementRow
	err := row.Scan(&i.Phase, &i.Epoch, &i.FailureReason)
	return i, err
}

const requestForceRelease = `-- name: RequestForceRelease :exec
UPDATE leases
   SET force_release = 1,
       failure_reason = CASE WHEN failure_reason = '' THEN CAST($1 AS TEXT)
                             ELSE failure_reason END
 WHERE id = $2 AND epoch = $3
`

type RequestForceReleaseParams struct {
	Reason string
	ID     string
	Epoch  int64
}

// Ask a live custody holder to give up a lease.
//
// IT DOES NOT TERMINALIZE. Custody and teardown have a process that still
// believes it owns the proof obligation; this makes its next heartbeat return
// ErrForceRelease so that process drops its record and releases the lease
// itself, rather than the ledger changing underneath it.
//
// THE OPERATOR'S ASSERTION IS RECORDED AS THE REASON, in the same statement,
// unless a reason is already there: the holder releases the lease as failed
// and the history would otherwise carry a failure nothing explains.
func (q *Queries) RequestForceRelease(ctx context.Context, arg RequestForceReleaseParams) error {
	_, err := q.db.ExecContext(ctx, requestForceRelease, arg.Reason, arg.ID, arg.Epoch)
	return err
}

const terminalizeQuarantinedLease = `-- name: TerminalizeQuarantinedLease :exec
UPDATE leases SET phase = $1, epoch = epoch + 1 WHERE id = $2
`

type TerminalizeQuarantinedLeaseParams struct {
	Phase string
	ID    string
}

// Settle a quarantined lease with the caller's outcome, bumping the fence.
//
// THE OUTCOME IS THE CALLER'S. A listener resolving one after a completion knows
// the job finished; a node cleaning up compute it could not account for, and an
// operator forcing a machine that is never coming back, both know the opposite.
// Recording every one of them as failed puts a lie in the history of a job
// GitHub reported completed.
func (q *Queries) TerminalizeQuarantinedLease(ctx context.Context, arg TerminalizeQuarantinedLeaseParams) error {
	_, err := q.db.ExecContext(ctx, terminalizeQuarantinedLease, arg.Phase, arg.ID)
	return err
}

const terminalizeQuarantinedLeaseWithReason = `-- name: TerminalizeQuarantinedLeaseWithReason :exec
UPDATE leases
   SET phase = 'failed', epoch = epoch + 1, failure_reason = $1
 WHERE id = $2
`

type TerminalizeQuarantinedLeaseWithReasonParams struct {
	FailureReason string
	ID            string
}

// Fail a quarantined lease whose guest an inventory did not contain.
//
// SEPARATE FROM THE STATEMENT ABOVE because it also records WHY, and that reason
// may be the provisional marker a later GitHub completion is allowed to correct.
func (q *Queries) TerminalizeQuarantinedLeaseWithReason(ctx context.Context, arg TerminalizeQuarantinedLeaseWithReasonParams) error {
	_, err := q.db.ExecContext(ctx, terminalizeQuarantinedLeaseWithReason, arg.FailureReason, arg.ID)
	return err
}

const upsertNodeInventory = `-- name: UpsertNodeInventory :exec
INSERT INTO node_inventory (node, node_epoch, received_at, running)
VALUES ($1, $2, $3, $4)
ON CONFLICT(node) DO UPDATE SET
     node_epoch = excluded.node_epoch,
     received_at = excluded.received_at,
     running = excluded.running
`

type UpsertNodeInventoryParams struct {
	Node       string
	NodeEpoch  int64
	ReceivedAt string
	Running    int64
}

// Record what a host last said it was running.
//
// EVIDENCE, NOT PROOF. The node lists its provider and THEN posts, so
// received_at is when the report ARRIVED and never when the snapshot was taken --
// a launch can be dispatched to that host immediately afterwards. Nothing may
// read this as clearance.
func (q *Queries) UpsertNodeInventory(ctx context.Context, arg UpsertNodeInventoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeInventory,
		arg.Node,
		arg.NodeEpoch,
		arg.ReceivedAt,
		arg.Running,
	)
	return err
}
