// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocation.sql

package ledgerdb

import (
	"context"
)

const certRevocation = `-- name: CertRevocation :one
SELECT CAST(1 AS BIGINT) FROM revoked_certs WHERE serial = $1
`

// Whether this serial has been withdrawn.
//
// ABSENCE IS sql.ErrNoRows, which the caller separates from a read error. A
// database fault must not answer "not revoked": that would make an unreadable
// ledger equivalent to an empty one, which is the whole check switched off by a
// transient fault.
func (q *Queries) CertRevocation(ctx context.Context, serial string) (int64, error) {
	row := q.db.QueryRowContext(ctx, certRevocation, serial)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listRevokedCerts = `-- name: ListRevokedCerts :many
SELECT serial, node, reason, revoked_at FROM revoked_certs ORDER BY revoked_at DESC
`

// What has been withdrawn, newest first.
func (q *Queries) ListRevokedCerts(ctx context.Context) ([]RevokedCert, error) {
	rows, err := q.db.QueryContext(ctx, listRevokedCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevokedCert
	for rows.Next() {
		var i RevokedCert
		if err := rows.Scan(
			&i.Serial,
			&i.Node,
			&i.Reason,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveCertsFor = `-- name: LiveCertsFor :many
SELECT i.serial, i.node, i.source, i.not_after, i.issued_at
  FROM issued_certs i
  LEFT JOIN revoked_certs r ON r.serial = i.serial
 WHERE i.node = $1 AND r.serial IS NULL AND i.not_after > $2
 ORDER BY i.issued_at DESC
`

type LiveCertsForParams struct {
	Node string
	Now  string
}

// The credentials one node holds that are neither expired nor already revoked.
func (q *Queries) LiveCertsFor(ctx context.Context, arg LiveCertsForParams) ([]IssuedCert, error) {
	rows, err := q.db.QueryContext(ctx, liveCertsFor, arg.Node, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssuedCert
	for rows.Next() {
		var i IssuedCert
		if err := rows.Scan(
			&i.Serial,
			&i.Node,
			&i.Source,
			&i.NotAfter,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeRevocationCutoff = `-- name: NodeRevocationCutoff :one
SELECT revoked_before FROM node_revocations WHERE node = $1
`

// The instant before which every certificate for this name is refused.
//
// sql.ErrNoRows means no cutoff was ever recorded for the node, which is not the
// same as a cutoff of zero and is why this is not a COALESCE.
func (q *Queries) NodeRevocationCutoff(ctx context.Context, node string) (string, error) {
	row := q.db.QueryRowContext(ctx, nodeRevocationCutoff, node)
	var revoked_before string
	err := row.Scan(&revoked_before)
	return revoked_before, err
}

const recordIssuedCert = `-- name: RecordIssuedCert :exec

INSERT INTO issued_certs (serial, node, source, not_after, issued_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (serial) DO NOTHING
`

type RecordIssuedCertParams struct {
	Serial   string
	Node     string
	Source   string
	NotAfter string
	IssuedAt string
}

// Certificates this deployment issued, and the ones it has taken back.
//
// TWO REVOCATION MECHANISMS, and both are here because neither is sufficient
// alone: a serial names one credential, which is the right granularity because a
// node name is legitimately re-issued to a replacement machine; a per-node cutoff
// reaches the credentials billet never recorded, which is the only handle a
// deployment upgraded from a version that did not record serials has.
// Write down a credential at the moment it is handed out.
//
// DO NOTHING rather than DO UPDATE: a serial identifies one credential, so a
// second insert under the same serial is a retry rather than a new fact.
func (q *Queries) RecordIssuedCert(ctx context.Context, arg RecordIssuedCertParams) error {
	_, err := q.db.ExecContext(ctx, recordIssuedCert,
		arg.Serial,
		arg.Node,
		arg.Source,
		arg.NotAfter,
		arg.IssuedAt,
	)
	return err
}

const recordNodeRevocation = `-- name: RecordNodeRevocation :exec
INSERT INTO node_revocations (node, revoked_before, reason, revoked_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (node) DO UPDATE SET
  revoked_before = excluded.revoked_before,
  reason         = excluded.reason,
  revoked_at     = excluded.revoked_at
`

type RecordNodeRevocationParams struct {
	Node          string
	RevokedBefore string
	Reason        string
	RevokedAt     string
}

// Refuse every certificate for this name minted before an instant.
//
// UPSERT, because a node revoked twice moves its cutoff forward. The reason and
// the timestamp move with it, so the row describes the revocation in force
// rather than the first one ever recorded.
func (q *Queries) RecordNodeRevocation(ctx context.Context, arg RecordNodeRevocationParams) error {
	_, err := q.db.ExecContext(ctx, recordNodeRevocation,
		arg.Node,
		arg.RevokedBefore,
		arg.Reason,
		arg.RevokedAt,
	)
	return err
}

const revokeCert = `-- name: RevokeCert :exec
INSERT INTO revoked_certs (serial, node, reason, revoked_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (serial) DO NOTHING
`

type RevokeCertParams struct {
	Serial    string
	Node      string
	Reason    string
	RevokedAt string
}

// Withdraw one certificate, idempotently.
//
// Revoking twice is not an error: an operator who is not sure whether the first
// attempt landed must be able to run it again.
func (q *Queries) RevokeCert(ctx context.Context, arg RevokeCertParams) error {
	_, err := q.db.ExecContext(ctx, revokeCert,
		arg.Serial,
		arg.Node,
		arg.Reason,
		arg.RevokedAt,
	)
	return err
}
