// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollouts.sql

package ledgerdb

import (
	"context"
)

const advanceRolloutController = `-- name: AdvanceRolloutController :exec
UPDATE rollouts SET controller_phase = $1
 WHERE id = $2 AND controller_phase = $3
`

type AdvanceRolloutControllerParams struct {
	ControllerPhase string
	ID              string
	ExpectPhase     string
}

// Move the control plane's own phase, refusing if it moved underneath us.
//
// THE PHASE IS IN THE WHERE as well as the SET. The caller read it inside this
// transaction and validated the transition; repeating it here means the write
// can never land on a row it did not read.
func (q *Queries) AdvanceRolloutController(ctx context.Context, arg AdvanceRolloutControllerParams) error {
	_, err := q.db.ExecContext(ctx, advanceRolloutController, arg.ControllerPhase, arg.ID, arg.ExpectPhase)
	return err
}

const advanceRolloutNode = `-- name: AdvanceRolloutNode :exec
UPDATE rollout_nodes
   SET phase = $1, attempts = $2, next_attempt_at = $3,
       blocker = $4, rollback_result = $5,
       exempt_reason = $6,
       prior_release = CASE WHEN CAST($7 AS TEXT) = ''
                            THEN prior_release ELSE CAST($7 AS TEXT) END,
       dispatch_epoch = CASE WHEN CAST($8 AS BIGINT) = 0
                            THEN dispatch_epoch ELSE CAST($8 AS BIGINT) END,
       converged_digest = CASE WHEN CAST($9 AS TEXT) = ''
                              THEN converged_digest ELSE CAST($9 AS TEXT) END,
       updated_at = $10
 WHERE rollout_id = $11 AND node = $12 AND phase = $13
`

type AdvanceRolloutNodeParams struct {
	Phase           string
	Attempts        int64
	NextAttemptAt   string
	Blocker         string
	RollbackResult  string
	ExemptReason    string
	PriorRelease    string
	DispatchEpoch   int64
	ConvergedDigest string
	UpdatedAt       string
	RolloutID       string
	Node            string
	ExpectPhase     string
}

// Move one host through the rollout state machine.
//
// THE THREE CASE COLUMNS ARE WRITE-ONCE-OR-KEEP, not optional parameters: a
// prior release, a dispatch epoch and a converged digest are each recorded by
// whichever pass first learns them, and every later pass passes nothing and must
// not erase what is there. Expressed in SQL rather than by building the
// statement two ways, because a branch applied in one path and forgotten in
// another is how a rollback loses the release it was meant to return to.
func (q *Queries) AdvanceRolloutNode(ctx context.Context, arg AdvanceRolloutNodeParams) error {
	_, err := q.db.ExecContext(ctx, advanceRolloutNode,
		arg.Phase,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.Blocker,
		arg.RollbackResult,
		arg.ExemptReason,
		arg.PriorRelease,
		arg.DispatchEpoch,
		arg.ConvergedDigest,
		arg.UpdatedAt,
		arg.RolloutID,
		arg.Node,
		arg.ExpectPhase,
	)
	return err
}

const finishRollout = `-- name: FinishRollout :exec
UPDATE rollouts
   SET state = $1, finished_at = $2, terminal_reason = $3
 WHERE id = $4 AND state = $5
`

type FinishRolloutParams struct {
	State          string
	FinishedAt     string
	TerminalReason string
	ID             string
	ExpectState    string
}

// Close a rollout, refusing one that is no longer open.
func (q *Queries) FinishRollout(ctx context.Context, arg FinishRolloutParams) error {
	_, err := q.db.ExecContext(ctx, finishRollout,
		arg.State,
		arg.FinishedAt,
		arg.TerminalReason,
		arg.ID,
		arg.ExpectState,
	)
	return err
}

const highestRolloutGeneration = `-- name: HighestRolloutGeneration :one

SELECT CAST(COALESCE(MAX(generation), 0) AS BIGINT) FROM rollouts
`

// Rollout queries: one durable fleet decision, and where every component of it
// has got to.
//
// THE STATEMENTS HERE ARE internal/rollout's, NOT internal/state's, and that is
// deliberate: the ledger's SQL lives in one directory so the guards that police
// it -- the prepare-against-the-migrated-schema check, the read/write
// classification, the ASCII rule and the wildcard ban -- cover every domain
// rather than only the ones that happened to be converted first.
// internal/rollout binds them through state.ReadQueries / state.WriteQueries.
// The highest generation any rollout has ever carried.
//
// CAST(COALESCE(...)) because sqlc types a bare MAX() -- and a bare
// COALESCE(MAX(), 0) -- as interface{}. Zero on an empty table, so the caller's
// +1 makes the first rollout generation 1, which the table's CHECK requires.
func (q *Queries) HighestRolloutGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, highestRolloutGeneration)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertRollout = `-- name: InsertRollout :exec
INSERT INTO rollouts
     (id, generation, channel, target_version, target_digest, policy,
      controller_phase, prior_version, state, created_by, created_at,
      finished_at, terminal_reason)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        '', '')
`

type InsertRolloutParams struct {
	ID              string
	Generation      int64
	Channel         string
	TargetVersion   string
	TargetDigest    string
	Policy          string
	ControllerPhase string
	PriorVersion    string
	State           string
	CreatedBy       string
	CreatedAt       string
}

// Record one fleet decision.
//
// finished_at and terminal_reason are written empty rather than parameterised:
// a rollout being inserted has not finished, and there is no value a caller
// could legitimately pass.
func (q *Queries) InsertRollout(ctx context.Context, arg InsertRolloutParams) error {
	_, err := q.db.ExecContext(ctx, insertRollout,
		arg.ID,
		arg.Generation,
		arg.Channel,
		arg.TargetVersion,
		arg.TargetDigest,
		arg.Policy,
		arg.ControllerPhase,
		arg.PriorVersion,
		arg.State,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertRolloutNode = `-- name: InsertRolloutNode :exec
INSERT INTO rollout_nodes
     (rollout_id, node, phase, attempts, next_attempt_at, blocker,
      prior_release, rollback_result, exempt_reason, updated_at,
      dispatch_epoch, converged_digest)
VALUES ($1, $2, $3, 0, '', '', '', '', '', $4, 0, '')
`

type InsertRolloutNodeParams struct {
	RolloutID string
	Node      string
	Phase     string
	UpdatedAt string
}

// Enrol one host in a rollout, at the phase every host starts in.
//
// The set of hosts is a SNAPSHOT taken when the rollout starts, so this is only
// ever called from Start: a host that registers later is running whatever it was
// installed with and is not part of a decision taken before it existed.
func (q *Queries) InsertRolloutNode(ctx context.Context, arg InsertRolloutNodeParams) error {
	_, err := q.db.ExecContext(ctx, insertRolloutNode,
		arg.RolloutID,
		arg.Node,
		arg.Phase,
		arg.UpdatedAt,
	)
	return err
}

const listRolloutHistory = `-- name: ListRolloutHistory :many
SELECT id, generation, channel, target_version, target_digest, policy,
       controller_phase, prior_version, state, created_by, created_at,
       finished_at, terminal_reason
  FROM rollouts ORDER BY generation DESC LIMIT CAST($1 AS BIGINT)
`

// Rollouts newest first, for the operator's report.
func (q *Queries) ListRolloutHistory(ctx context.Context, maxRows int64) ([]Rollout, error) {
	rows, err := q.db.QueryContext(ctx, listRolloutHistory, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rollout
	for rows.Next() {
		var i Rollout
		if err := rows.Scan(
			&i.ID,
			&i.Generation,
			&i.Channel,
			&i.TargetVersion,
			&i.TargetDigest,
			&i.Policy,
			&i.ControllerPhase,
			&i.PriorVersion,
			&i.State,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.TerminalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolloutNodePhases = `-- name: ListRolloutNodePhases :many
SELECT node, phase FROM rollout_nodes
 WHERE rollout_id = $1 ORDER BY node
`

type ListRolloutNodePhasesRow struct {
	Node  string
	Phase string
}

// Just the phase of every host in one rollout, for the completion check.
//
// SEPARATE FROM ListRolloutNodes because the completion check reads every host
// on every pass and needs two columns of the eleven; the projection is the
// difference between a cheap question and the whole table.
func (q *Queries) ListRolloutNodePhases(ctx context.Context, rolloutID string) ([]ListRolloutNodePhasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolloutNodePhases, rolloutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolloutNodePhasesRow
	for rows.Next() {
		var i ListRolloutNodePhasesRow
		if err := rows.Scan(&i.Node, &i.Phase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolloutNodes = `-- name: ListRolloutNodes :many
SELECT node, phase, attempts, next_attempt_at, blocker, prior_release,
       rollback_result, exempt_reason, updated_at, dispatch_epoch,
       converged_digest
  FROM rollout_nodes WHERE rollout_id = $1 ORDER BY node
`

type ListRolloutNodesRow struct {
	Node            string
	Phase           string
	Attempts        int64
	NextAttemptAt   string
	Blocker         string
	PriorRelease    string
	RollbackResult  string
	ExemptReason    string
	UpdatedAt       string
	DispatchEpoch   int64
	ConvergedDigest string
}

// Where every host in one rollout has got to, in a stable order.
func (q *Queries) ListRolloutNodes(ctx context.Context, rolloutID string) ([]ListRolloutNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolloutNodes, rolloutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolloutNodesRow
	for rows.Next() {
		var i ListRolloutNodesRow
		if err := rows.Scan(
			&i.Node,
			&i.Phase,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.Blocker,
			&i.PriorRelease,
			&i.RollbackResult,
			&i.ExemptReason,
			&i.UpdatedAt,
			&i.DispatchEpoch,
			&i.ConvergedDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readNewestRolloutForTarget = `-- name: ReadNewestRolloutForTarget :one
SELECT id, generation, channel, target_version, target_digest, policy,
       controller_phase, prior_version, state, created_by, created_at,
       finished_at, terminal_reason
  FROM rollouts WHERE target_digest = $1 ORDER BY generation DESC LIMIT 1
`

// The newest rollout, in any state, to one manifest digest: what an automatic
// start consults before it would restart bytes an operator abandoned.
func (q *Queries) ReadNewestRolloutForTarget(ctx context.Context, targetDigest string) (Rollout, error) {
	row := q.db.QueryRowContext(ctx, readNewestRolloutForTarget, targetDigest)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.Channel,
		&i.TargetVersion,
		&i.TargetDigest,
		&i.Policy,
		&i.ControllerPhase,
		&i.PriorVersion,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.TerminalReason,
	)
	return i, err
}

const readRolloutControllerPhase = `-- name: ReadRolloutControllerPhase :one
SELECT controller_phase FROM rollouts WHERE id = $1
`

// Where the control plane itself has got to in one rollout.
func (q *Queries) ReadRolloutControllerPhase(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, readRolloutControllerPhase, id)
	var controller_phase string
	err := row.Scan(&controller_phase)
	return controller_phase, err
}

const readRolloutInState = `-- name: ReadRolloutInState :one
SELECT id, generation, channel, target_version, target_digest, policy,
       controller_phase, prior_version, state, created_by, created_at,
       finished_at, terminal_reason
  FROM rollouts WHERE state = $1
`

// The rollout in one state.
//
// A :one AND ONLY SAFE FOR 'open', which is the single state carrying a partial
// unique index (rollouts_open). Its one caller passes StateOpen; a caller that
// passed 'completed' would get an arbitrary one of many rows, which is why the
// state stays a parameter naming the Go constant rather than a literal here that
// would read as a guarantee this statement cannot make.
func (q *Queries) ReadRolloutInState(ctx context.Context, state string) (Rollout, error) {
	row := q.db.QueryRowContext(ctx, readRolloutInState, state)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.Channel,
		&i.TargetVersion,
		&i.TargetDigest,
		&i.Policy,
		&i.ControllerPhase,
		&i.PriorVersion,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.TerminalReason,
	)
	return i, err
}

const readRolloutNodeProgress = `-- name: ReadRolloutNodeProgress :one
SELECT phase, attempts FROM rollout_nodes
 WHERE rollout_id = $1 AND node = $2
`

type ReadRolloutNodeProgressParams struct {
	RolloutID string
	Node      string
}

type ReadRolloutNodeProgressRow struct {
	Phase    string
	Attempts int64
}

// One host's phase and attempt count, read against the row a write will act on.
func (q *Queries) ReadRolloutNodeProgress(ctx context.Context, arg ReadRolloutNodeProgressParams) (ReadRolloutNodeProgressRow, error) {
	row := q.db.QueryRowContext(ctx, readRolloutNodeProgress, arg.RolloutID, arg.Node)
	var i ReadRolloutNodeProgressRow
	err := row.Scan(&i.Phase, &i.Attempts)
	return i, err
}
