// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scaleset.sql

package ledgerdb

import (
	"context"
)

const deleteMovedScaleSet = `-- name: DeleteMovedScaleSet :exec
DELETE FROM scale_set
 WHERE org = $1 AND scale_set_id = $2
   AND NOT (runner_group = $3 AND label = $4)
`

type DeleteMovedScaleSetParams struct {
	Org         string
	ScaleSetID  int64
	RunnerGroup string
	Label       string
}

// Forget a record whose scale set id now answers to a different name.
//
// A scale set deleted and recreated outside billet keeps its name and takes a
// new id; one RENAMED keeps its id under a new name. This removes the stale
// (group, label) so the orphan report does not name an object that is gone.
func (q *Queries) DeleteMovedScaleSet(ctx context.Context, arg DeleteMovedScaleSetParams) error {
	_, err := q.db.ExecContext(ctx, deleteMovedScaleSet,
		arg.Org,
		arg.ScaleSetID,
		arg.RunnerGroup,
		arg.Label,
	)
	return err
}

const deleteScaleSet = `-- name: DeleteScaleSet :exec
DELETE FROM scale_set WHERE org = $1 AND runner_group = $2 AND label = $3
`

type DeleteScaleSetParams struct {
	Org         string
	RunnerGroup string
	Label       string
}

// Drop the record for a scale set billet has deleted.
func (q *Queries) DeleteScaleSet(ctx context.Context, arg DeleteScaleSetParams) error {
	_, err := q.db.ExecContext(ctx, deleteScaleSet, arg.Org, arg.RunnerGroup, arg.Label)
	return err
}

const listScaleSets = `-- name: ListScaleSets :many
SELECT org, runner_group, label, scale_set_id FROM scale_set
 WHERE org = $1 ORDER BY runner_group, label
`

type ListScaleSetsRow struct {
	Org         string
	RunnerGroup string
	Label       string
	ScaleSetID  int64
}

// Every scale set billet recorded creating for one organization.
func (q *Queries) ListScaleSets(ctx context.Context, org string) ([]ListScaleSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScaleSets, org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScaleSetsRow
	for rows.Next() {
		var i ListScaleSetsRow
		if err := rows.Scan(
			&i.Org,
			&i.RunnerGroup,
			&i.Label,
			&i.ScaleSetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScaleSet = `-- name: UpsertScaleSet :exec
INSERT INTO scale_set (org, runner_group, label, scale_set_id, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org, runner_group, label) DO UPDATE SET scale_set_id = excluded.scale_set_id
`

type UpsertScaleSetParams struct {
	Org         string
	RunnerGroup string
	Label       string
	ScaleSetID  int64
	CreatedAt   string
}

// Remember that billet created this scale set.
//
// The id is REFRESHED rather than kept: the server reconciles every tier on
// every start, so this runs constantly against rows that already exist, and a
// stale id would send an operator looking for an object that no longer exists.
func (q *Queries) UpsertScaleSet(ctx context.Context, arg UpsertScaleSetParams) error {
	_, err := q.db.ExecContext(ctx, upsertScaleSet,
		arg.Org,
		arg.RunnerGroup,
		arg.Label,
		arg.ScaleSetID,
		arg.CreatedAt,
	)
	return err
}
